In [1]:
import requests
import json
import pandas as pd

In [2]:
from api_key import my_api_key

In [3]:
from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv("API_KEY")

# Bitcoin

In [4]:

import requests

url = f'https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_WEEKLY&symbol=BTC&market=EUR&apikey={api_key}'
response_btc = requests.get(url)
response_btc

In [5]:
import json

status_code = response_btc.status_code
Bitcoin = response_btc.json()

print(json.dumps(Bitcoin, indent=2))

{
  "Meta Data": {
    "1. Information": "Weekly Prices and Volumes for Digital Currency",
    "2. Digital Currency Code": "BTC",
    "3. Digital Currency Name": "Bitcoin",
    "4. Market Code": "EUR",
    "5. Market Name": "Euro",
    "6. Last Refreshed": "2025-04-03 00:00:00",
    "7. Time Zone": "UTC"
  },
  "Time Series (Digital Currency Weekly)": {
    "2025-04-03": {
      "1. open": "76102.60000000",
      "2. high": "81300.00000000",
      "3. low": "75042.00000000",
      "4. close": "76365.98000000",
      "5. volume": "1511.75857276"
    },
    "2025-03-30": {
      "1. open": "79441.34000000",
      "2. high": "82091.43000000",
      "3. low": "75432.48000000",
      "4. close": "76135.85000000",
      "5. volume": "2003.05822813"
    },
    "2025-03-23": {
      "1. open": "75935.10000000",
      "2. high": "80150.77000000",
      "3. low": "74226.31000000",
      "4. close": "79452.90000000",
      "5. volume": "2004.67925658"
    },
    "2025-03-16": {
      "1. open": "74334.78000000",
      "2. high": "78476.10000000",
      "3. low": "70570.00000000",
      "4. close": "75928.62000000",
      "5. volume": "3317.85059693"
    },
    "2025-03-09": {
      "1. open": "90634.87000000",
      "2. high": "90798.09000000",
      "3. low": "73680.00000000",
      "4. close": "74310.03000000",
      "5. volume": "4567.15724730"
    },
    "2025-03-02": {
      "1. open": "91900.51000000",
      "2. high": "92078.26000000",
      "3. low": "75141.16000000",
      "4. close": "90642.23000000",
      "5. volume": "5817.43954029"
    },
    "2025-02-23": {
      "1. open": "91620.25000000",
      "2. high": "94977.61000000",
      "3. low": "89368.01000000",
      "4. close": "91874.60000000",
      "5. volume": "1663.37913607"
    },
    "2025-02-16": {
      "1. open": "93636.05000000",
      "2. high": "95586.34000000",
      "3. low": "91150.00000000",
      "4. close": "91634.19000000",
      "5. volume": "1897.10832421"
    },
    "2025-02-09": {
      "1. open": "95431.64000000",
      "2. high": "99421.84000000",
      "3. low": "89248.90000000",
      "4. close": "93607.15000000",
      "5. volume": "3166.38457836"
    },
    "2025-02-02": {
      "1. open": "98050.00000000",
      "2. high": "102000.00000000",
      "3. low": "93414.78000000",
      "4. close": "95427.29000000",
      "5. volume": "2910.03861451"
    },
    "2025-01-26": {
      "1. open": "98539.45000000",
      "2. high": "105951.19000000",
      "3. low": "96436.00000000",
      "4. close": "98088.57000000",
      "5. volume": "3658.55695193"
    },
    "2025-01-19": {
      "1. open": "92284.22000000",
      "2. high": "103599.98000000",
      "3. low": "87437.71000000",
      "4. close": "98574.14000000",
      "5. volume": "3343.99758658"
    },
    "2025-01-12": {
      "1. open": "95456.12000000",
      "2. high": "98960.78000000",
      "3. low": "88606.32000000",
      "4. close": "92337.55000000",
      "5. volume": "2445.36645429"
    },
    "2025-01-05": {
      "1. open": "89692.71000000",
      "2. high": "96143.44000000",
      "3. low": "87834.22000000",
      "4. close": "95451.75000000",
      "5. volume": "2005.55539841"
    },
    "2024-12-29": {
      "1. open": "91182.16000000",
      "2. high": "96129.98000000",
      "3. low": "88832.59000000",
      "4. close": "89702.09000000",
      "5. volume": "2344.01826091"
    },
    "2024-12-22": {
      "1. open": "99120.98000000",
      "2. high": "103000.00000000",
      "3. low": "88421.18000000",
      "4. close": "91204.69000000",
      "5. volume": "4072.70477282"
    },
    "2024-12-15": {
      "1. open": "95662.16000000",
      "2. high": "99800.00000000",
      "3. low": "89217.53000000",
      "4. close": "99111.37000000",
      "5. volume": "2699.63992449"
    },
    "2024-12-08": {
      "1. open": "92096.25000000",
      "2. high": "98456.03000000",
      "3. low": "86600.00000000",
      "4. close": "95685.97000000",
      "5. volume": "3394.00176391"
    },
    "2024-12-01": {
      "1. open": "93388.13000000",
      "2. high": "94400.00000000",
      "3. low": "86543.90000000",
      "4. close": "92099.58000000",
      "5. volume": "3804.20978625"
    },
    "2024-11-24": {
      "1. open": "85046.28000000",
      "2. high": "95501.25000000",
      "3. low": "84594.12000000",
      "4. close": "93391.61000000",
      "5. volume": "5630.82466588"
    },
    "2024-11-17": {
      "1. open": "74780.73000000",
      "2. high": "88000.00000000",
      "3. low": "74639.10000000",
      "4. close": "85016.99000000",
      "5. volume": "6663.35849385"
    },
    "2024-11-10": {
      "1. open": "63408.26000000",
      "2. high": "75699.99000000",
      "3. low": "61410.68000000",
      "4. close": "74757.19000000",
      "5. volume": "3545.72577803"
    },
    "2024-11-03": {
      "1. open": "62928.68000000",
      "2. high": "68000.00000000",
      "3. low": "62351.09000000",
      "4. close": "63426.11000000",
      "5. volume": "2261.17772077"
    },
    "2024-10-27": {
      "1. open": "63445.78000000",
      "2. high": "63900.00000000",
      "3. low": "60465.00000000",
      "4. close": "62928.34000000",
      "5. volume": "1786.10966199"
    },
    "2024-10-20": {
      "1. open": "57516.93000000",
      "2. high": "63779.18000000",
      "3. low": "57148.57000000",
      "4. close": "63433.63000000",
      "5. volume": "2063.91962502"
    },
    "2024-10-13": {
      "1. open": "57256.48000000",
      "2. high": "58723.00000000",
      "3. low": "53904.09000000",
      "4. close": "57519.27000000",
      "5. volume": "1245.49032033"
    },
    "2024-10-06": {
      "1. open": "58752.02000000",
      "2. high": "58757.86000000",
      "3. low": "54237.15000000",
      "4. close": "57248.79000000",
      "5. volume": "1637.16110423"
    },
    "2024-09-29": {
      "1. open": "56988.75000000",
      "2. high": "59528.74000000",
      "3. low": "56080.15000000",
      "4. close": "58742.25000000",
      "5. volume": "1390.31440855"
    },
    "2024-09-22": {
      "1. open": "53320.98000000",
      "2. high": "57414.44000000",
      "3. low": "51650.17000000",
      "4. close": "57001.09000000",
      "5. volume": "1655.13071181"
    },
    "2024-09-15": {
      "1. open": "49526.79000000",
      "2. high": "54781.85000000",
      "3. low": "49315.32000000",
      "4. close": "53343.95000000",
      "5. volume": "1707.00085554"
    },
    "2024-09-08": {
      "1. open": "51911.95000000",
      "2. high": "54065.45000000",
      "3. low": "47428.66000000",
      "4. close": "49505.02000000",
      "5. volume": "2198.29055177"
    },
    "2024-09-01": {
      "1. open": "57406.50000000",
      "2. high": "57632.29000000",
      "3. low": "51802.75000000",
      "4. close": "51931.36000000",
      "5. volume": "1877.16287658"
    },
    "2024-08-25": {
      "1. open": "53049.34000000",
      "2. high": "58113.94000000",
      "3. low": "52408.27000000",
      "4. close": "57402.19000000",
      "5. volume": "2010.86924833"
    },
    "2024-08-18": {
      "1. open": "53822.14000000",
      "2. high": "56141.89000000",
      "3. low": "51195.03000000",
      "4. close": "53046.89000000",
      "5. volume": "1836.96086527"
    },
    "2024-08-11": {
      "1. open": "53330.01000000",
      "2. high": "57499.00000000",
      "3. low": "45021.36000000",
      "4. close": "53835.66000000",
      "5. volume": "5859.41666575"
    },
    "2024-08-04": {
      "1. open": "62866.50000000",
      "2. high": "64749.00000000",
      "3. low": "52521.27000000",
      "4. close": "53309.69000000",
      "5. volume": "3522.97605496"
    },
    "2024-07-28": {
      "1. open": "62526.97000000",
      "2. high": "63876.72000000",
      "3. low": "58512.00000000",
      "4. close": "62854.02000000",
      "5. volume": "1840.76222947"
    },
    "2024-07-21": {
      "1. open": "55876.94000000",
      "2. high": "62721.17000000",
      "3. low": "55750.00000000",
      "4. close": "62529.01000000",
      "5. volume": "2216.33637267"
    },
    "2024-07-14": {
      "1. open": "51589.15000000",
      "2. high": "56400.63000000",
      "3. low": "50144.21000000",
      "4. close": "55876.86000000",
      "5. volume": "5468.18414888"
    },
    "2024-07-07": {
      "1. open": "58416.69000000",
      "2. high": "59467.74000000",
      "3. low": "49437.20000000",
      "4. close": "51589.15000000",
      "5. volume": "3660.07676506"
    },
    "2024-06-30": {
      "1. open": "59127.81000000",
      "2. high": "59261.30000000",
      "3. low": "54419.19000000",
      "4. close": "58407.41000000",
      "5. volume": "2451.79270208"
    },
    "2024-06-23": {
      "1. open": "62279.16000000",
      "2. high": "62696.68000000",
      "3. low": "59085.16000000",
      "4. close": "59107.12000000",
      "5. volume": "1526.55665651"
    },
    "2024-06-16": {
      "1. open": "64664.14000000",
      "2. high": "65298.24000000",
      "3. low": "60801.06000000",
      "4. close": "62262.17000000",
      "5. volume": "1826.63665226"
    },
    "2024-06-09": {
      "1. open": "62428.48000000",
      "2. high": "66132.47000000",
      "3. low": "62283.90000000",
      "4. close": "64648.18000000",
      "5. volume": "1890.77051357"
    },
    "2024-06-02": {
      "1. open": "63145.80000000",
      "2. high": "64989.91000000",
      "3. low": "61440.00000000",
      "4. close": "62452.47000000",
      "5. volume": "1558.52996222"
    },
    "2024-05-26": {
      "1. open": "60930.51000000",
      "2. high": "65933.02000000",
      "3. low": "60750.00000000",
      "4. close": "63138.93000000",
      "5. volume": "2469.25527144"
    },
    "2024-05-19": {
      "1. open": "57085.97000000",
      "2. high": "62261.43000000",
      "3. low": "56418.03000000",
      "4. close": "60927.75000000",
      "5. volume": "2144.93191604"
    },
    "2024-05-12": {
      "1. open": "59515.05000000",
      "2. high": "60834.00000000",
      "3. low": "55876.05000000",
      "4. close": "57075.98000000",
      "5. volume": "2126.96316157"
    },
    "2024-05-05": {
      "1. open": "58965.50000000",
      "2. high": "60365.57000000",
      "3. low": "52943.49000000",
      "4. close": "59506.98000000",
      "5. volume": "4178.03884138"
    },
    "2024-04-28": {
      "1. open": "60985.08000000",
      "2. high": "63134.63000000",
      "3. low": "58411.49000000",
      "4. close": "58947.56000000",
      "5. volume": "2398.39662537"
    }
  }
}

In [6]:
for x in Bitcoin:
  print(x)

Meta Data
Time Series (Digital Currency Weekly)

In [6]:
status_code = response_btc.status_code
data = response_btc.json()
print(json.dumps(Bitcoin["Time Series (Digital Currency Weekly)"]))

{"2025-04-02": {"1. open": "76102.60000000", "2. high": "79232.59000000", "3. low": "75042.00000000", "4. close": "78757.05000000", "5. volume": "807.71891735"}, "2025-03-30": {"1. open": "79441.34000000", "2. high": "82091.43000000", "3. low": "75432.48000000", "4. close": "76135.85000000", "5. volume": "2003.05822813"}, "2025-03-23": {"1. open": "75935.10000000", "2. high": "80150.77000000", "3. low": "74226.31000000", "4. close": "79452.90000000", "5. volume": "2004.67925658"}, "2025-03-16": {"1. open": "74334.78000000", "2. high": "78476.10000000", "3. low": "70570.00000000", "4. close": "75928.62000000", "5. volume": "3317.85059693"}, "2025-03-09": {"1. open": "90634.87000000", "2. high": "90798.09000000", "3. low": "73680.00000000", "4. close": "74310.03000000", "5. volume": "4567.15724730"}, "2025-03-02": {"1. open": "91900.51000000", "2. high": "92078.26000000", "3. low": "75141.16000000", "4. close": "90642.23000000", "5. volume": "5817.43954029"}, "2025-02-23": {"1. open": "91620.25000000", "2. high": "94977.61000000", "3. low": "89368.01000000", "4. close": "91874.60000000", "5. volume": "1663.37913607"}, "2025-02-16": {"1. open": "93636.05000000", "2. high": "95586.34000000", "3. low": "91150.00000000", "4. close": "91634.19000000", "5. volume": "1897.10832421"}, "2025-02-09": {"1. open": "95431.64000000", "2. high": "99421.84000000", "3. low": "89248.90000000", "4. close": "93607.15000000", "5. volume": "3166.38457836"}, "2025-02-02": {"1. open": "98050.00000000", "2. high": "102000.00000000", "3. low": "93414.78000000", "4. close": "95427.29000000", "5. volume": "2910.03861451"}, "2025-01-26": {"1. open": "98539.45000000", "2. high": "105951.19000000", "3. low": "96436.00000000", "4. close": "98088.57000000", "5. volume": "3658.55695193"}, "2025-01-19": {"1. open": "92284.22000000", "2. high": "103599.98000000", "3. low": "87437.71000000", "4. close": "98574.14000000", "5. volume": "3343.99758658"}, "2025-01-12": {"1. open": "95456.12000000", "2. high": "98960.78000000", "3. low": "88606.32000000", "4. close": "92337.55000000", "5. volume": "2445.36645429"}, "2025-01-05": {"1. open": "89692.71000000", "2. high": "96143.44000000", "3. low": "87834.22000000", "4. close": "95451.75000000", "5. volume": "2005.55539841"}, "2024-12-29": {"1. open": "91182.16000000", "2. high": "96129.98000000", "3. low": "88832.59000000", "4. close": "89702.09000000", "5. volume": "2344.01826091"}, "2024-12-22": {"1. open": "99120.98000000", "2. high": "103000.00000000", "3. low": "88421.18000000", "4. close": "91204.69000000", "5. volume": "4072.70477282"}, "2024-12-15": {"1. open": "95662.16000000", "2. high": "99800.00000000", "3. low": "89217.53000000", "4. close": "99111.37000000", "5. volume": "2699.63992449"}, "2024-12-08": {"1. open": "92096.25000000", "2. high": "98456.03000000", "3. low": "86600.00000000", "4. close": "95685.97000000", "5. volume": "3394.00176391"}, "2024-12-01": {"1. open": "93388.13000000", "2. high": "94400.00000000", "3. low": "86543.90000000", "4. close": "92099.58000000", "5. volume": "3804.20978625"}, "2024-11-24": {"1. open": "85046.28000000", "2. high": "95501.25000000", "3. low": "84594.12000000", "4. close": "93391.61000000", "5. volume": "5630.82466588"}, "2024-11-17": {"1. open": "74780.73000000", "2. high": "88000.00000000", "3. low": "74639.10000000", "4. close": "85016.99000000", "5. volume": "6663.35849385"}, "2024-11-10": {"1. open": "63408.26000000", "2. high": "75699.99000000", "3. low": "61410.68000000", "4. close": "74757.19000000", "5. volume": "3545.72577803"}, "2024-11-03": {"1. open": "62928.68000000", "2. high": "68000.00000000", "3. low": "62351.09000000", "4. close": "63426.11000000", "5. volume": "2261.17772077"}, "2024-10-27": {"1. open": "63445.78000000", "2. high": "63900.00000000", "3. low": "60465.00000000", "4. close": "62928.34000000", "5. volume": "1786.10966199"}, "2024-10-20": {"1. open": "57516.93000000", "2. high": "63779.18000000", "3. low": "57148.57000000", "4. close": "63433.63000000", "5. volume": "2063.91962502"}, "2024-10-13": {"1. open": "57256.48000000", "2. high": "58723.00000000", "3. low": "53904.09000000", "4. close": "57519.27000000", "5. volume": "1245.49032033"}, "2024-10-06": {"1. open": "58752.02000000", "2. high": "58757.86000000", "3. low": "54237.15000000", "4. close": "57248.79000000", "5. volume": "1637.16110423"}, "2024-09-29": {"1. open": "56988.75000000", "2. high": "59528.74000000", "3. low": "56080.15000000", "4. close": "58742.25000000", "5. volume": "1390.31440855"}, "2024-09-22": {"1. open": "53320.98000000", "2. high": "57414.44000000", "3. low": "51650.17000000", "4. close": "57001.09000000", "5. volume": "1655.13071181"}, "2024-09-15": {"1. open": "49526.79000000", "2. high": "54781.85000000", "3. low": "49315.32000000", "4. close": "53343.95000000", "5. volume": "1707.00085554"}, "2024-09-08": {"1. open": "51911.95000000", "2. high": "54065.45000000", "3. low": "47428.66000000", "4. close": "49505.02000000", "5. volume": "2198.29055177"}, "2024-09-01": {"1. open": "57406.50000000", "2. high": "57632.29000000", "3. low": "51802.75000000", "4. close": "51931.36000000", "5. volume": "1877.16287658"}, "2024-08-25": {"1. open": "53049.34000000", "2. high": "58113.94000000", "3. low": "52408.27000000", "4. close": "57402.19000000", "5. volume": "2010.86924833"}, "2024-08-18": {"1. open": "53822.14000000", "2. high": "56141.89000000", "3. low": "51195.03000000", "4. close": "53046.89000000", "5. volume": "1836.96086527"}, "2024-08-11": {"1. open": "53330.01000000", "2. high": "57499.00000000", "3. low": "45021.36000000", "4. close": "53835.66000000", "5. volume": "5859.41666575"}, "2024-08-04": {"1. open": "62866.50000000", "2. high": "64749.00000000", "3. low": "52521.27000000", "4. close": "53309.69000000", "5. volume": "3522.97605496"}, "2024-07-28": {"1. open": "62526.97000000", "2. high": "63876.72000000", "3. low": "58512.00000000", "4. close": "62854.02000000", "5. volume": "1840.76222947"}, "2024-07-21": {"1. open": "55876.94000000", "2. high": "62721.17000000", "3. low": "55750.00000000", "4. close": "62529.01000000", "5. volume": "2216.33637267"}, "2024-07-14": {"1. open": "51589.15000000", "2. high": "56400.63000000", "3. low": "50144.21000000", "4. close": "55876.86000000", "5. volume": "5468.18414888"}, "2024-07-07": {"1. open": "58416.69000000", "2. high": "59467.74000000", "3. low": "49437.20000000", "4. close": "51589.15000000", "5. volume": "3660.07676506"}, "2024-06-30": {"1. open": "59127.81000000", "2. high": "59261.30000000", "3. low": "54419.19000000", "4. close": "58407.41000000", "5. volume": "2451.79270208"}, "2024-06-23": {"1. open": "62279.16000000", "2. high": "62696.68000000", "3. low": "59085.16000000", "4. close": "59107.12000000", "5. volume": "1526.55665651"}, "2024-06-16": {"1. open": "64664.14000000", "2. high": "65298.24000000", "3. low": "60801.06000000", "4. close": "62262.17000000", "5. volume": "1826.63665226"}, "2024-06-09": {"1. open": "62428.48000000", "2. high": "66132.47000000", "3. low": "62283.90000000", "4. close": "64648.18000000", "5. volume": "1890.77051357"}, "2024-06-02": {"1. open": "63145.80000000", "2. high": "64989.91000000", "3. low": "61440.00000000", "4. close": "62452.47000000", "5. volume": "1558.52996222"}, "2024-05-26": {"1. open": "60930.51000000", "2. high": "65933.02000000", "3. low": "60750.00000000", "4. close": "63138.93000000", "5. volume": "2469.25527144"}, "2024-05-19": {"1. open": "57085.97000000", "2. high": "62261.43000000", "3. low": "56418.03000000", "4. close": "60927.75000000", "5. volume": "2144.93191604"}, "2024-05-12": {"1. open": "59515.05000000", "2. high": "60834.00000000", "3. low": "55876.05000000", "4. close": "57075.98000000", "5. volume": "2126.96316157"}, "2024-05-05": {"1. open": "58965.50000000", "2. high": "60365.57000000", "3. low": "52943.49000000", "4. close": "59506.98000000", "5. volume": "4178.03884138"}, "2024-04-28": {"1. open": "60985.08000000", "2. high": "63134.63000000", "3. low": "58411.49000000", "4. close": "58947.56000000", "5. volume": "2398.39662537"}}

In [6]:
Bitcoin["Time Series (Digital Currency Weekly)"]

{'2025-04-03': {'1. open': '76102.60000000',
  '2. high': '81300.00000000',
  '3. low': '75042.00000000',
  '4. close': '76365.98000000',
  '5. volume': '1511.75857276'},
 '2025-03-30': {'1. open': '79441.34000000',
  '2. high': '82091.43000000',
  '3. low': '75432.48000000',
  '4. close': '76135.85000000',
  '5. volume': '2003.05822813'},
 '2025-03-23': {'1. open': '75935.10000000',
  '2. high': '80150.77000000',
  '3. low': '74226.31000000',
  '4. close': '79452.90000000',
  '5. volume': '2004.67925658'},
 '2025-03-16': {'1. open': '74334.78000000',
  '2. high': '78476.10000000',
  '3. low': '70570.00000000',
  '4. close': '75928.62000000',
  '5. volume': '3317.85059693'},
 '2025-03-09': {'1. open': '90634.87000000',
  '2. high': '90798.09000000',
  '3. low': '73680.00000000',
  '4. close': '74310.03000000',
  '5. volume': '4567.15724730'},
 '2025-03-02': {'1. open': '91900.51000000',
  '2. high': '92078.26000000',
  '3. low': '75141.16000000',
  '4. close': '90642.23000000',
  '5. volume': '5817.43954029'},
 '2025-02-23': {'1. open': '91620.25000000',
  '2. high': '94977.61000000',
  '3. low': '89368.01000000',
  '4. close': '91874.60000000',
  '5. volume': '1663.37913607'},
 '2025-02-16': {'1. open': '93636.05000000',
  '2. high': '95586.34000000',
  '3. low': '91150.00000000',
  '4. close': '91634.19000000',
  '5. volume': '1897.10832421'},
 '2025-02-09': {'1. open': '95431.64000000',
  '2. high': '99421.84000000',
  '3. low': '89248.90000000',
  '4. close': '93607.15000000',
  '5. volume': '3166.38457836'},
 '2025-02-02': {'1. open': '98050.00000000',
  '2. high': '102000.00000000',
  '3. low': '93414.78000000',
  '4. close': '95427.29000000',
  '5. volume': '2910.03861451'},
 '2025-01-26': {'1. open': '98539.45000000',
  '2. high': '105951.19000000',
  '3. low': '96436.00000000',
  '4. close': '98088.57000000',
  '5. volume': '3658.55695193'},
 '2025-01-19': {'1. open': '92284.22000000',
  '2. high': '103599.98000000',
  '3. low': '87437.71000000',
  '4. close': '98574.14000000',
  '5. volume': '3343.99758658'},
 '2025-01-12': {'1. open': '95456.12000000',
  '2. high': '98960.78000000',
  '3. low': '88606.32000000',
  '4. close': '92337.55000000',
  '5. volume': '2445.36645429'},
 '2025-01-05': {'1. open': '89692.71000000',
  '2. high': '96143.44000000',
  '3. low': '87834.22000000',
  '4. close': '95451.75000000',
  '5. volume': '2005.55539841'},
 '2024-12-29': {'1. open': '91182.16000000',
  '2. high': '96129.98000000',
  '3. low': '88832.59000000',
  '4. close': '89702.09000000',
  '5. volume': '2344.01826091'},
 '2024-12-22': {'1. open': '99120.98000000',
  '2. high': '103000.00000000',
  '3. low': '88421.18000000',
  '4. close': '91204.69000000',
  '5. volume': '4072.70477282'},
 '2024-12-15': {'1. open': '95662.16000000',
  '2. high': '99800.00000000',
  '3. low': '89217.53000000',
  '4. close': '99111.37000000',
  '5. volume': '2699.63992449'},
 '2024-12-08': {'1. open': '92096.25000000',
  '2. high': '98456.03000000',
  '3. low': '86600.00000000',
  '4. close': '95685.97000000',
  '5. volume': '3394.00176391'},
 '2024-12-01': {'1. open': '93388.13000000',
  '2. high': '94400.00000000',
  '3. low': '86543.90000000',
  '4. close': '92099.58000000',
  '5. volume': '3804.20978625'},
 '2024-11-24': {'1. open': '85046.28000000',
  '2. high': '95501.25000000',
  '3. low': '84594.12000000',
  '4. close': '93391.61000000',
  '5. volume': '5630.82466588'},
 '2024-11-17': {'1. open': '74780.73000000',
  '2. high': '88000.00000000',
  '3. low': '74639.10000000',
  '4. close': '85016.99000000',
  '5. volume': '6663.35849385'},
 '2024-11-10': {'1. open': '63408.26000000',
  '2. high': '75699.99000000',
  '3. low': '61410.68000000',
  '4. close': '74757.19000000',
  '5. volume': '3545.72577803'},
 '2024-11-03': {'1. open': '62928.68000000',
  '2. high': '68000.00000000',
  '3. low': '62351.09000000',
  '4. close': '63426.11000000',
  '5. volume': '2261.17772077'},
 '2024-10-27': {'1. open': '63445.78000000',
  '2. high': '63900.00000000',
  '3. low': '60465.00000000',
  '4. close': '62928.34000000',
  '5. volume': '1786.10966199'},
 '2024-10-20': {'1. open': '57516.93000000',
  '2. high': '63779.18000000',
  '3. low': '57148.57000000',
  '4. close': '63433.63000000',
  '5. volume': '2063.91962502'},
 '2024-10-13': {'1. open': '57256.48000000',
  '2. high': '58723.00000000',
  '3. low': '53904.09000000',
  '4. close': '57519.27000000',
  '5. volume': '1245.49032033'},
 '2024-10-06': {'1. open': '58752.02000000',
  '2. high': '58757.86000000',
  '3. low': '54237.15000000',
  '4. close': '57248.79000000',
  '5. volume': '1637.16110423'},
 '2024-09-29': {'1. open': '56988.75000000',
  '2. high': '59528.74000000',
  '3. low': '56080.15000000',
  '4. close': '58742.25000000',
  '5. volume': '1390.31440855'},
 '2024-09-22': {'1. open': '53320.98000000',
  '2. high': '57414.44000000',
  '3. low': '51650.17000000',
  '4. close': '57001.09000000',
  '5. volume': '1655.13071181'},
 '2024-09-15': {'1. open': '49526.79000000',
  '2. high': '54781.85000000',
  '3. low': '49315.32000000',
  '4. close': '53343.95000000',
  '5. volume': '1707.00085554'},
 '2024-09-08': {'1. open': '51911.95000000',
  '2. high': '54065.45000000',
  '3. low': '47428.66000000',
  '4. close': '49505.02000000',
  '5. volume': '2198.29055177'},
 '2024-09-01': {'1. open': '57406.50000000',
  '2. high': '57632.29000000',
  '3. low': '51802.75000000',
  '4. close': '51931.36000000',
  '5. volume': '1877.16287658'},
 '2024-08-25': {'1. open': '53049.34000000',
  '2. high': '58113.94000000',
  '3. low': '52408.27000000',
  '4. close': '57402.19000000',
  '5. volume': '2010.86924833'},
 '2024-08-18': {'1. open': '53822.14000000',
  '2. high': '56141.89000000',
  '3. low': '51195.03000000',
  '4. close': '53046.89000000',
  '5. volume': '1836.96086527'},
 '2024-08-11': {'1. open': '53330.01000000',
  '2. high': '57499.00000000',
  '3. low': '45021.36000000',
  '4. close': '53835.66000000',
  '5. volume': '5859.41666575'},
 '2024-08-04': {'1. open': '62866.50000000',
  '2. high': '64749.00000000',
  '3. low': '52521.27000000',
  '4. close': '53309.69000000',
  '5. volume': '3522.97605496'},
 '2024-07-28': {'1. open': '62526.97000000',
  '2. high': '63876.72000000',
  '3. low': '58512.00000000',
  '4. close': '62854.02000000',
  '5. volume': '1840.76222947'},
 '2024-07-21': {'1. open': '55876.94000000',
  '2. high': '62721.17000000',
  '3. low': '55750.00000000',
  '4. close': '62529.01000000',
  '5. volume': '2216.33637267'},
 '2024-07-14': {'1. open': '51589.15000000',
  '2. high': '56400.63000000',
  '3. low': '50144.21000000',
  '4. close': '55876.86000000',
  '5. volume': '5468.18414888'},
 '2024-07-07': {'1. open': '58416.69000000',
  '2. high': '59467.74000000',
  '3. low': '49437.20000000',
  '4. close': '51589.15000000',
  '5. volume': '3660.07676506'},
 '2024-06-30': {'1. open': '59127.81000000',
  '2. high': '59261.30000000',
  '3. low': '54419.19000000',
  '4. close': '58407.41000000',
  '5. volume': '2451.79270208'},
 '2024-06-23': {'1. open': '62279.16000000',
  '2. high': '62696.68000000',
  '3. low': '59085.16000000',
  '4. close': '59107.12000000',
  '5. volume': '1526.55665651'},
 '2024-06-16': {'1. open': '64664.14000000',
  '2. high': '65298.24000000',
  '3. low': '60801.06000000',
  '4. close': '62262.17000000',
  '5. volume': '1826.63665226'},
 '2024-06-09': {'1. open': '62428.48000000',
  '2. high': '66132.47000000',
  '3. low': '62283.90000000',
  '4. close': '64648.18000000',
  '5. volume': '1890.77051357'},
 '2024-06-02': {'1. open': '63145.80000000',
  '2. high': '64989.91000000',
  '3. low': '61440.00000000',
  '4. close': '62452.47000000',
  '5. volume': '1558.52996222'},
 '2024-05-26': {'1. open': '60930.51000000',
  '2. high': '65933.02000000',
  '3. low': '60750.00000000',
  '4. close': '63138.93000000',
  '5. volume': '2469.25527144'},
 '2024-05-19': {'1. open': '57085.97000000',
  '2. high': '62261.43000000',
  '3. low': '56418.03000000',
  '4. close': '60927.75000000',
  '5. volume': '2144.93191604'},
 '2024-05-12': {'1. open': '59515.05000000',
  '2. high': '60834.00000000',
  '3. low': '55876.05000000',
  '4. close': '57075.98000000',
  '5. volume': '2126.96316157'},
 '2024-05-05': {'1. open': '58965.50000000',
  '2. high': '60365.57000000',
  '3. low': '52943.49000000',
  '4. close': '59506.98000000',
  '5. volume': '4178.03884138'},
 '2024-04-28': {'1. open': '60985.08000000',
  '2. high': '63134.63000000',
  '3. low': '58411.49000000',
  '4. close': '58947.56000000',
  '5. volume': '2398.39662537'}}

In [9]:
for x, obj in Bitcoin.items():
    print(x)
    
    for y in obj:
        print(y + ':', obj[y])

Meta Data
1. Information: Weekly Prices and Volumes for Digital Currency
2. Digital Currency Code: BTC
3. Digital Currency Name: Bitcoin
4. Market Code: EUR
5. Market Name: Euro
6. Last Refreshed: 2025-04-02 00:00:00
7. Time Zone: UTC
Time Series (Digital Currency Weekly)
2025-04-02: {'1. open': '76102.60000000', '2. high': '79232.59000000', '3. low': '75042.00000000', '4. close': '78757.05000000', '5. volume': '807.71891735'}
2025-03-30: {'1. open': '79441.34000000', '2. high': '82091.43000000', '3. low': '75432.48000000', '4. close': '76135.85000000', '5. volume': '2003.05822813'}
2025-03-23: {'1. open': '75935.10000000', '2. high': '80150.77000000', '3. low': '74226.31000000', '4. close': '79452.90000000', '5. volume': '2004.67925658'}
2025-03-16: {'1. open': '74334.78000000', '2. high': '78476.10000000', '3. low': '70570.00000000', '4. close': '75928.62000000', '5. volume': '3317.85059693'}
2025-03-09: {'1. open': '90634.87000000', '2. high': '90798.09000000', '3. low': '73680.00000000', '4. close': '74310.03000000', '5. volume': '4567.15724730'}
2025-03-02: {'1. open': '91900.51000000', '2. high': '92078.26000000', '3. low': '75141.16000000', '4. close': '90642.23000000', '5. volume': '5817.43954029'}
2025-02-23: {'1. open': '91620.25000000', '2. high': '94977.61000000', '3. low': '89368.01000000', '4. close': '91874.60000000', '5. volume': '1663.37913607'}
2025-02-16: {'1. open': '93636.05000000', '2. high': '95586.34000000', '3. low': '91150.00000000', '4. close': '91634.19000000', '5. volume': '1897.10832421'}
2025-02-09: {'1. open': '95431.64000000', '2. high': '99421.84000000', '3. low': '89248.90000000', '4. close': '93607.15000000', '5. volume': '3166.38457836'}
2025-02-02: {'1. open': '98050.00000000', '2. high': '102000.00000000', '3. low': '93414.78000000', '4. close': '95427.29000000', '5. volume': '2910.03861451'}
2025-01-26: {'1. open': '98539.45000000', '2. high': '105951.19000000', '3. low': '96436.00000000', '4. close': '98088.57000000', '5. volume': '3658.55695193'}
2025-01-19: {'1. open': '92284.22000000', '2. high': '103599.98000000', '3. low': '87437.71000000', '4. close': '98574.14000000', '5. volume': '3343.99758658'}
2025-01-12: {'1. open': '95456.12000000', '2. high': '98960.78000000', '3. low': '88606.32000000', '4. close': '92337.55000000', '5. volume': '2445.36645429'}
2025-01-05: {'1. open': '89692.71000000', '2. high': '96143.44000000', '3. low': '87834.22000000', '4. close': '95451.75000000', '5. volume': '2005.55539841'}
2024-12-29: {'1. open': '91182.16000000', '2. high': '96129.98000000', '3. low': '88832.59000000', '4. close': '89702.09000000', '5. volume': '2344.01826091'}
2024-12-22: {'1. open': '99120.98000000', '2. high': '103000.00000000', '3. low': '88421.18000000', '4. close': '91204.69000000', '5. volume': '4072.70477282'}
2024-12-15: {'1. open': '95662.16000000', '2. high': '99800.00000000', '3. low': '89217.53000000', '4. close': '99111.37000000', '5. volume': '2699.63992449'}
2024-12-08: {'1. open': '92096.25000000', '2. high': '98456.03000000', '3. low': '86600.00000000', '4. close': '95685.97000000', '5. volume': '3394.00176391'}
2024-12-01: {'1. open': '93388.13000000', '2. high': '94400.00000000', '3. low': '86543.90000000', '4. close': '92099.58000000', '5. volume': '3804.20978625'}
2024-11-24: {'1. open': '85046.28000000', '2. high': '95501.25000000', '3. low': '84594.12000000', '4. close': '93391.61000000', '5. volume': '5630.82466588'}
2024-11-17: {'1. open': '74780.73000000', '2. high': '88000.00000000', '3. low': '74639.10000000', '4. close': '85016.99000000', '5. volume': '6663.35849385'}
2024-11-10: {'1. open': '63408.26000000', '2. high': '75699.99000000', '3. low': '61410.68000000', '4. close': '74757.19000000', '5. volume': '3545.72577803'}
2024-11-03: {'1. open': '62928.68000000', '2. high': '68000.00000000', '3. low': '62351.09000000', '4. close': '63426.11000000', '5. volume': '2261.17772077'}
2024-10-27: {'1. open': '63445.78000000', '2. high': '63900.00000000', '3. low': '60465.00000000', '4. close': '62928.34000000', '5. volume': '1786.10966199'}
2024-10-20: {'1. open': '57516.93000000', '2. high': '63779.18000000', '3. low': '57148.57000000', '4. close': '63433.63000000', '5. volume': '2063.91962502'}
2024-10-13: {'1. open': '57256.48000000', '2. high': '58723.00000000', '3. low': '53904.09000000', '4. close': '57519.27000000', '5. volume': '1245.49032033'}
2024-10-06: {'1. open': '58752.02000000', '2. high': '58757.86000000', '3. low': '54237.15000000', '4. close': '57248.79000000', '5. volume': '1637.16110423'}
2024-09-29: {'1. open': '56988.75000000', '2. high': '59528.74000000', '3. low': '56080.15000000', '4. close': '58742.25000000', '5. volume': '1390.31440855'}
2024-09-22: {'1. open': '53320.98000000', '2. high': '57414.44000000', '3. low': '51650.17000000', '4. close': '57001.09000000', '5. volume': '1655.13071181'}
2024-09-15: {'1. open': '49526.79000000', '2. high': '54781.85000000', '3. low': '49315.32000000', '4. close': '53343.95000000', '5. volume': '1707.00085554'}
2024-09-08: {'1. open': '51911.95000000', '2. high': '54065.45000000', '3. low': '47428.66000000', '4. close': '49505.02000000', '5. volume': '2198.29055177'}
2024-09-01: {'1. open': '57406.50000000', '2. high': '57632.29000000', '3. low': '51802.75000000', '4. close': '51931.36000000', '5. volume': '1877.16287658'}
2024-08-25: {'1. open': '53049.34000000', '2. high': '58113.94000000', '3. low': '52408.27000000', '4. close': '57402.19000000', '5. volume': '2010.86924833'}
2024-08-18: {'1. open': '53822.14000000', '2. high': '56141.89000000', '3. low': '51195.03000000', '4. close': '53046.89000000', '5. volume': '1836.96086527'}
2024-08-11: {'1. open': '53330.01000000', '2. high': '57499.00000000', '3. low': '45021.36000000', '4. close': '53835.66000000', '5. volume': '5859.41666575'}
2024-08-04: {'1. open': '62866.50000000', '2. high': '64749.00000000', '3. low': '52521.27000000', '4. close': '53309.69000000', '5. volume': '3522.97605496'}
2024-07-28: {'1. open': '62526.97000000', '2. high': '63876.72000000', '3. low': '58512.00000000', '4. close': '62854.02000000', '5. volume': '1840.76222947'}
2024-07-21: {'1. open': '55876.94000000', '2. high': '62721.17000000', '3. low': '55750.00000000', '4. close': '62529.01000000', '5. volume': '2216.33637267'}
2024-07-14: {'1. open': '51589.15000000', '2. high': '56400.63000000', '3. low': '50144.21000000', '4. close': '55876.86000000', '5. volume': '5468.18414888'}
2024-07-07: {'1. open': '58416.69000000', '2. high': '59467.74000000', '3. low': '49437.20000000', '4. close': '51589.15000000', '5. volume': '3660.07676506'}
2024-06-30: {'1. open': '59127.81000000', '2. high': '59261.30000000', '3. low': '54419.19000000', '4. close': '58407.41000000', '5. volume': '2451.79270208'}
2024-06-23: {'1. open': '62279.16000000', '2. high': '62696.68000000', '3. low': '59085.16000000', '4. close': '59107.12000000', '5. volume': '1526.55665651'}
2024-06-16: {'1. open': '64664.14000000', '2. high': '65298.24000000', '3. low': '60801.06000000', '4. close': '62262.17000000', '5. volume': '1826.63665226'}
2024-06-09: {'1. open': '62428.48000000', '2. high': '66132.47000000', '3. low': '62283.90000000', '4. close': '64648.18000000', '5. volume': '1890.77051357'}
2024-06-02: {'1. open': '63145.80000000', '2. high': '64989.91000000', '3. low': '61440.00000000', '4. close': '62452.47000000', '5. volume': '1558.52996222'}
2024-05-26: {'1. open': '60930.51000000', '2. high': '65933.02000000', '3. low': '60750.00000000', '4. close': '63138.93000000', '5. volume': '2469.25527144'}
2024-05-19: {'1. open': '57085.97000000', '2. high': '62261.43000000', '3. low': '56418.03000000', '4. close': '60927.75000000', '5. volume': '2144.93191604'}
2024-05-12: {'1. open': '59515.05000000', '2. high': '60834.00000000', '3. low': '55876.05000000', '4. close': '57075.98000000', '5. volume': '2126.96316157'}
2024-05-05: {'1. open': '58965.50000000', '2. high': '60365.57000000', '3. low': '52943.49000000', '4. close': '59506.98000000', '5. volume': '4178.03884138'}
2024-04-28: {'1. open': '60985.08000000', '2. high': '63134.63000000', '3. low': '58411.49000000', '4. close': '58947.56000000', '5. volume': '2398.39662537'}

In [8]:
import json
import pandas as pd

# Assuming response_btc is your API response
status_code = response_btc.status_code
data = response_btc.json()

# Print the raw data to understand its structure (debugging)
print(json.dumps(data, indent=2))

# Initialize lists to store data
dates = []
opens = []
highs = []
lows = []
closes = []
volumes = []

# Extract metadata
meta_data = data.get("Meta Data", {})
digital_currency_name = meta_data.get("Digital Currency Name", "Bitcoin")

# Extract time series data
time_series_key = "Time Series (Digital Currency Weekly)"
time_series = data.get(time_series_key, {})

for date_str, values in time_series.items():
    dates.append(date_str)
    opens.append(float(values.get("1. open", 0)))
    highs.append(float(values.get("2. high", 0)))
    lows.append(float(values.get("3. low", 0)))
    closes.append(float(values.get("4. close", 0)))
    volumes.append(float(values.get("5. volume", 0)))

# Create DataFrame
BitcoinDF = pd.DataFrame({
    "date": dates,
    "open": opens,
    "high": highs,
    "low": lows,
    "close": closes,
    "volume": volumes,
    "currency_name": digital_currency_name
})

# Convert date column to datetime and sort
BitcoinDF['date'] = pd.to_datetime(BitcoinDF['date'])
BitcoinDF = BitcoinDF.sort_values('date', ascending=False)

# Display the DataFrame
print(BitcoinDF.head())

# Optional: Save to CSV
BitcoinDF.to_csv('Bitcoin_Weekly_Prices.csv', index=False)

{
  "Meta Data": {
    "1. Information": "Weekly Prices and Volumes for Digital Currency",
    "2. Digital Currency Code": "BTC",
    "3. Digital Currency Name": "Bitcoin",
    "4. Market Code": "EUR",
    "5. Market Name": "Euro",
    "6. Last Refreshed": "2025-04-03 00:00:00",
    "7. Time Zone": "UTC"
  },
  "Time Series (Digital Currency Weekly)": {
    "2025-04-03": {
      "1. open": "76102.60000000",
      "2. high": "81300.00000000",
      "3. low": "75042.00000000",
      "4. close": "76365.98000000",
      "5. volume": "1511.75857276"
    },
    "2025-03-30": {
      "1. open": "79441.34000000",
      "2. high": "82091.43000000",
      "3. low": "75432.48000000",
      "4. close": "76135.85000000",
      "5. volume": "2003.05822813"
    },
    "2025-03-23": {
      "1. open": "75935.10000000",
      "2. high": "80150.77000000",
      "3. low": "74226.31000000",
      "4. close": "79452.90000000",
      "5. volume": "2004.67925658"
    },
    "2025-03-16": {
      "1. open": "74334.78000000",
      "2. high": "78476.10000000",
      "3. low": "70570.00000000",
      "4. close": "75928.62000000",
      "5. volume": "3317.85059693"
    },
    "2025-03-09": {
      "1. open": "90634.87000000",
      "2. high": "90798.09000000",
      "3. low": "73680.00000000",
      "4. close": "74310.03000000",
      "5. volume": "4567.15724730"
    },
    "2025-03-02": {
      "1. open": "91900.51000000",
      "2. high": "92078.26000000",
      "3. low": "75141.16000000",
      "4. close": "90642.23000000",
      "5. volume": "5817.43954029"
    },
    "2025-02-23": {
      "1. open": "91620.25000000",
      "2. high": "94977.61000000",
      "3. low": "89368.01000000",
      "4. close": "91874.60000000",
      "5. volume": "1663.37913607"
    },
    "2025-02-16": {
      "1. open": "93636.05000000",
      "2. high": "95586.34000000",
      "3. low": "91150.00000000",
      "4. close": "91634.19000000",
      "5. volume": "1897.10832421"
    },
    "2025-02-09": {
      "1. open": "95431.64000000",
      "2. high": "99421.84000000",
      "3. low": "89248.90000000",
      "4. close": "93607.15000000",
      "5. volume": "3166.38457836"
    },
    "2025-02-02": {
      "1. open": "98050.00000000",
      "2. high": "102000.00000000",
      "3. low": "93414.78000000",
      "4. close": "95427.29000000",
      "5. volume": "2910.03861451"
    },
    "2025-01-26": {
      "1. open": "98539.45000000",
      "2. high": "105951.19000000",
      "3. low": "96436.00000000",
      "4. close": "98088.57000000",
      "5. volume": "3658.55695193"
    },
    "2025-01-19": {
      "1. open": "92284.22000000",
      "2. high": "103599.98000000",
      "3. low": "87437.71000000",
      "4. close": "98574.14000000",
      "5. volume": "3343.99758658"
    },
    "2025-01-12": {
      "1. open": "95456.12000000",
      "2. high": "98960.78000000",
      "3. low": "88606.32000000",
      "4. close": "92337.55000000",
      "5. volume": "2445.36645429"
    },
    "2025-01-05": {
      "1. open": "89692.71000000",
      "2. high": "96143.44000000",
      "3. low": "87834.22000000",
      "4. close": "95451.75000000",
      "5. volume": "2005.55539841"
    },
    "2024-12-29": {
      "1. open": "91182.16000000",
      "2. high": "96129.98000000",
      "3. low": "88832.59000000",
      "4. close": "89702.09000000",
      "5. volume": "2344.01826091"
    },
    "2024-12-22": {
      "1. open": "99120.98000000",
      "2. high": "103000.00000000",
      "3. low": "88421.18000000",
      "4. close": "91204.69000000",
      "5. volume": "4072.70477282"
    },
    "2024-12-15": {
      "1. open": "95662.16000000",
      "2. high": "99800.00000000",
      "3. low": "89217.53000000",
      "4. close": "99111.37000000",
      "5. volume": "2699.63992449"
    },
    "2024-12-08": {
      "1. open": "92096.25000000",
      "2. high": "98456.03000000",
      "3. low": "86600.00000000",
      "4. close": "95685.97000000",
      "5. volume": "3394.00176391"
    },
    "2024-12-01": {
      "1. open": "93388.13000000",
      "2. high": "94400.00000000",
      "3. low": "86543.90000000",
      "4. close": "92099.58000000",
      "5. volume": "3804.20978625"
    },
    "2024-11-24": {
      "1. open": "85046.28000000",
      "2. high": "95501.25000000",
      "3. low": "84594.12000000",
      "4. close": "93391.61000000",
      "5. volume": "5630.82466588"
    },
    "2024-11-17": {
      "1. open": "74780.73000000",
      "2. high": "88000.00000000",
      "3. low": "74639.10000000",
      "4. close": "85016.99000000",
      "5. volume": "6663.35849385"
    },
    "2024-11-10": {
      "1. open": "63408.26000000",
      "2. high": "75699.99000000",
      "3. low": "61410.68000000",
      "4. close": "74757.19000000",
      "5. volume": "3545.72577803"
    },
    "2024-11-03": {
      "1. open": "62928.68000000",
      "2. high": "68000.00000000",
      "3. low": "62351.09000000",
      "4. close": "63426.11000000",
      "5. volume": "2261.17772077"
    },
    "2024-10-27": {
      "1. open": "63445.78000000",
      "2. high": "63900.00000000",
      "3. low": "60465.00000000",
      "4. close": "62928.34000000",
      "5. volume": "1786.10966199"
    },
    "2024-10-20": {
      "1. open": "57516.93000000",
      "2. high": "63779.18000000",
      "3. low": "57148.57000000",
      "4. close": "63433.63000000",
      "5. volume": "2063.91962502"
    },
    "2024-10-13": {
      "1. open": "57256.48000000",
      "2. high": "58723.00000000",
      "3. low": "53904.09000000",
      "4. close": "57519.27000000",
      "5. volume": "1245.49032033"
    },
    "2024-10-06": {
      "1. open": "58752.02000000",
      "2. high": "58757.86000000",
      "3. low": "54237.15000000",
      "4. close": "57248.79000000",
      "5. volume": "1637.16110423"
    },
    "2024-09-29": {
      "1. open": "56988.75000000",
      "2. high": "59528.74000000",
      "3. low": "56080.15000000",
      "4. close": "58742.25000000",
      "5. volume": "1390.31440855"
    },
    "2024-09-22": {
      "1. open": "53320.98000000",
      "2. high": "57414.44000000",
      "3. low": "51650.17000000",
      "4. close": "57001.09000000",
      "5. volume": "1655.13071181"
    },
    "2024-09-15": {
      "1. open": "49526.79000000",
      "2. high": "54781.85000000",
      "3. low": "49315.32000000",
      "4. close": "53343.95000000",
      "5. volume": "1707.00085554"
    },
    "2024-09-08": {
      "1. open": "51911.95000000",
      "2. high": "54065.45000000",
      "3. low": "47428.66000000",
      "4. close": "49505.02000000",
      "5. volume": "2198.29055177"
    },
    "2024-09-01": {
      "1. open": "57406.50000000",
      "2. high": "57632.29000000",
      "3. low": "51802.75000000",
      "4. close": "51931.36000000",
      "5. volume": "1877.16287658"
    },
    "2024-08-25": {
      "1. open": "53049.34000000",
      "2. high": "58113.94000000",
      "3. low": "52408.27000000",
      "4. close": "57402.19000000",
      "5. volume": "2010.86924833"
    },
    "2024-08-18": {
      "1. open": "53822.14000000",
      "2. high": "56141.89000000",
      "3. low": "51195.03000000",
      "4. close": "53046.89000000",
      "5. volume": "1836.96086527"
    },
    "2024-08-11": {
      "1. open": "53330.01000000",
      "2. high": "57499.00000000",
      "3. low": "45021.36000000",
      "4. close": "53835.66000000",
      "5. volume": "5859.41666575"
    },
    "2024-08-04": {
      "1. open": "62866.50000000",
      "2. high": "64749.00000000",
      "3. low": "52521.27000000",
      "4. close": "53309.69000000",
      "5. volume": "3522.97605496"
    },
    "2024-07-28": {
      "1. open": "62526.97000000",
      "2. high": "63876.72000000",
      "3. low": "58512.00000000",
      "4. close": "62854.02000000",
      "5. volume": "1840.76222947"
    },
    "2024-07-21": {
      "1. open": "55876.94000000",
      "2. high": "62721.17000000",
      "3. low": "55750.00000000",
      "4. close": "62529.01000000",
      "5. volume": "2216.33637267"
    },
    "2024-07-14": {
      "1. open": "51589.15000000",
      "2. high": "56400.63000000",
      "3. low": "50144.21000000",
      "4. close": "55876.86000000",
      "5. volume": "5468.18414888"
    },
    "2024-07-07": {
      "1. open": "58416.69000000",
      "2. high": "59467.74000000",
      "3. low": "49437.20000000",
      "4. close": "51589.15000000",
      "5. volume": "3660.07676506"
    },
    "2024-06-30": {
      "1. open": "59127.81000000",
      "2. high": "59261.30000000",
      "3. low": "54419.19000000",
      "4. close": "58407.41000000",
      "5. volume": "2451.79270208"
    },
    "2024-06-23": {
      "1. open": "62279.16000000",
      "2. high": "62696.68000000",
      "3. low": "59085.16000000",
      "4. close": "59107.12000000",
      "5. volume": "1526.55665651"
    },
    "2024-06-16": {
      "1. open": "64664.14000000",
      "2. high": "65298.24000000",
      "3. low": "60801.06000000",
      "4. close": "62262.17000000",
      "5. volume": "1826.63665226"
    },
    "2024-06-09": {
      "1. open": "62428.48000000",
      "2. high": "66132.47000000",
      "3. low": "62283.90000000",
      "4. close": "64648.18000000",
      "5. volume": "1890.77051357"
    },
    "2024-06-02": {
      "1. open": "63145.80000000",
      "2. high": "64989.91000000",
      "3. low": "61440.00000000",
      "4. close": "62452.47000000",
      "5. volume": "1558.52996222"
    },
    "2024-05-26": {
      "1. open": "60930.51000000",
      "2. high": "65933.02000000",
      "3. low": "60750.00000000",
      "4. close": "63138.93000000",
      "5. volume": "2469.25527144"
    },
    "2024-05-19": {
      "1. open": "57085.97000000",
      "2. high": "62261.43000000",
      "3. low": "56418.03000000",
      "4. close": "60927.75000000",
      "5. volume": "2144.93191604"
    },
    "2024-05-12": {
      "1. open": "59515.05000000",
      "2. high": "60834.00000000",
      "3. low": "55876.05000000",
      "4. close": "57075.98000000",
      "5. volume": "2126.96316157"
    },
    "2024-05-05": {
      "1. open": "58965.50000000",
      "2. high": "60365.57000000",
      "3. low": "52943.49000000",
      "4. close": "59506.98000000",
      "5. volume": "4178.03884138"
    },
    "2024-04-28": {
      "1. open": "60985.08000000",
      "2. high": "63134.63000000",
      "3. low": "58411.49000000",
      "4. close": "58947.56000000",
      "5. volume": "2398.39662537"
    }
  }
}
        date      open      high       low     close       volume  \
0 2025-04-03  76102.60  81300.00  75042.00  76365.98  1511.758573
1 2025-03-30  79441.34  82091.43  75432.48  76135.85  2003.058228
2 2025-03-23  75935.10  80150.77  74226.31  79452.90  2004.679257
3 2025-03-16  74334.78  78476.10  70570.00  75928.62  3317.850597
4 2025-03-09  90634.87  90798.09  73680.00  74310.03  4567.157247

  currency_name
0       Bitcoin
1       Bitcoin
2       Bitcoin
3       Bitcoin
4       Bitcoin

In [9]:
Bitcoin_df = pd.read_csv('Bitcoin_Weekly_Prices.csv', sep=',')

In [10]:
Bitcoin_df

,date,open,high,low,close,volume,currency_name
0,2025-04-03,76102.60,81300.00,75042.00,76365.98,1511.758573,Bitcoin
1,2025-03-30,79441.34,82091.43,75432.48,76135.85,2003.058228,Bitcoin
2,2025-03-23,75935.10,80150.77,74226.31,79452.90,2004.679257,Bitcoin
3,2025-03-16,74334.78,78476.10,70570.00,75928.62,3317.850597,Bitcoin
4,2025-03-09,90634.87,90798.09,73680.00,74310.03,4567.157247,Bitcoin
5,2025-03-02,91900.51,92078.26,75141.16,90642.23,5817.439540,Bitcoin
6,2025-02-23,91620.25,94977.61,89368.01,91874.60,1663.379136,Bitcoin
7,2025-02-16,93636.05,95586.34,91150.00,91634.19,1897.108324,Bitcoin
8,2025-02-09,95431.64,99421.84,89248.90,93607.15,3166.384578,Bitcoin
9,2025-02-02,98050.00,102000.00,93414.78,95427.29,2910.038615,Bitcoin
10,2025-01-26,98539.45,105951.19,96436.00,98088.57,3658.556952,Bitcoin
11,2025-01-19,92284.22,103599.98,87437.71,98574.14,3343.997587,Bitcoin
12,2025-01-12,95456.12,98960.78,88606.32,92337.55,2445.366454,Bitcoin
13,2025-01-05,89692.71,96143.44,87834.22,95451.75,2005.555398,Bitcoin
14,2024-12-29,91182.16,96129.98,88832.59,89702.09,2344.018261,Bitcoin
15,2024-12-22,99120.98,103000.00,88421.18,91204.69,4072.704773,Bitcoin
16,2024-12-15,95662.16,99800.00,89217.53,99111.37,2699.639924,Bitcoin
17,2024-12-08,92096.25,98456.03,86600.00,95685.97,3394.001764,Bitcoin
18,2024-12-01,93388.13,94400.00,86543.90,92099.58,3804.209786,Bitcoin
19,2024-11-24,85046.28,95501.25,84594.12,93391.61,5630.824666,Bitcoin
20,2024-11-17,74780.73,88000.00,74639.10,85016.99,6663.358494,Bitcoin
21,2024-11-10,63408.26,75699.99,61410.68,74757.19,3545.725778,Bitcoin
22,2024-11-03,62928.68,68000.00,62351.09,63426.11,2261.177721,Bitcoin
23,2024-10-27,63445.78,63900.00,60465.00,62928.34,1786.109662,Bitcoin
24,2024-10-20,57516.93,63779.18,57148.57,63433.63,2063.919625,Bitcoin
25,2024-10-13,57256.48,58723.00,53904.09,57519.27,1245.490320,Bitcoin
26,2024-10-06,58752.02,58757.86,54237.15,57248.79,1637.161104,Bitcoin
27,2024-09-29,56988.75,59528.74,56080.15,58742.25,1390.314409,Bitcoin
28,2024-09-22,53320.98,57414.44,51650.17,57001.09,1655.130712,Bitcoin
29,2024-09-15,49526.79,54781.85,49315.32,53343.95,1707.000856,Bitcoin
30,2024-09-08,51911.95,54065.45,47428.66,49505.02,2198.290552,Bitcoin
31,2024-09-01,57406.50,57632.29,51802.75,51931.36,1877.162877,Bitcoin
32,2024-08-25,53049.34,58113.94,52408.27,57402.19,2010.869248,Bitcoin
33,2024-08-18,53822.14,56141.89,51195.03,53046.89,1836.960865,Bitcoin
34,2024-08-11,53330.01,57499.00,45021.36,53835.66,5859.416666,Bitcoin
35,2024-08-04,62866.50,64749.00,52521.27,53309.69,3522.976055,Bitcoin
36,2024-07-28,62526.97,63876.72,58512.00,62854.02,1840.762229,Bitcoin
37,2024-07-21,55876.94,62721.17,55750.00,62529.01,2216.336373,Bitcoin
38,2024-07-14,51589.15,56400.63,50144.21,55876.86,5468.184149,Bitcoin
39,2024-07-07,58416.69,59467.74,49437.20,51589.15,3660.076765,Bitcoin
40,2024-06-30,59127.81,59261.30,54419.19,58407.41,2451.792702,Bitcoin
41,2024-06-23,62279.16,62696.68,59085.16,59107.12,1526.556657,Bitcoin
42,2024-06-16,64664.14,65298.24,60801.06,62262.17,1826.636652,Bitcoin
43,2024-06-09,62428.48,66132.47,62283.90,64648.18,1890.770514,Bitcoin
44,2024-06-02,63145.80,64989.91,61440.00,62452.47,1558.529962,Bitcoin
45,2024-05-26,60930.51,65933.02,60750.00,63138.93,2469.255271,Bitcoin
46,2024-05-19,57085.97,62261.43,56418.03,60927.75,2144.931916,Bitcoin
47,2024-05-12,59515.05,60834.00,55876.05,57075.98,2126.963162,Bitcoin
48,2024-05-05,58965.50,60365.57,52943.49,59506.98,4178.038841,Bitcoin
49,2024-04-28,60985.08,63134.63,58411.49,58947.56,2398.396625,Bitcoin

# Ethereum

In [11]:
import requests

urrl = f'https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_WEEKLY&symbol=ETH&market=EUR&apikey={api_key}'
response_eth = requests.get(urrl)
response_eth

In [12]:
import json

status_cd = response_eth.status_code
Ethereum = response_eth.json()

print(json.dumps(Ethereum, indent=2))

{
  "Meta Data": {
    "1. Information": "Weekly Prices and Volumes for Digital Currency",
    "2. Digital Currency Code": "ETH",
    "3. Digital Currency Name": "Ethereum",
    "4. Market Code": "EUR",
    "5. Market Name": "Euro",
    "6. Last Refreshed": "2025-04-03 00:00:00",
    "7. Time Zone": "UTC"
  },
  "Time Series (Digital Currency Weekly)": {
    "2025-04-03": {
      "1. open": "1670.57000000",
      "2. high": "1795.00000000",
      "3. low": "1640.81000000",
      "4. close": "1671.29000000",
      "5. volume": "47624.97437019"
    },
    "2025-03-30": {
      "1. open": "1849.23000000",
      "2. high": "1945.20000000",
      "3. low": "1635.00000000",
      "4. close": "1669.86000000",
      "5. volume": "64432.13343915"
    },
    "2025-03-23": {
      "1. open": "1735.03000000",
      "2. high": "1898.07000000",
      "3. low": "1710.92000000",
      "4. close": "1849.98000000",
      "5. volume": "49409.12563792"
    },
    "2025-03-16": {
      "1. open": "1860.63000000",
      "2. high": "1985.93000000",
      "3. low": "1616.86000000",
      "4. close": "1735.26000000",
      "5. volume": "95653.82797713"
    },
    "2025-03-09": {
      "1. open": "2421.48000000",
      "2. high": "2426.40000000",
      "3. low": "1832.78000000",
      "4. close": "1859.68000000",
      "5. volume": "92640.20045031"
    },
    "2025-03-02": {
      "1. open": "2691.28000000",
      "2. high": "2708.39000000",
      "3. low": "1994.22000000",
      "4. close": "2421.03000000",
      "5. volume": "109277.77896004"
    },
    "2025-02-23": {
      "1. open": "2538.61000000",
      "2. high": "2724.62000000",
      "3. low": "2494.06000000",
      "4. close": "2691.55000000",
      "5. volume": "52440.66009421"
    },
    "2025-02-16": {
      "1. open": "2551.22000000",
      "2. high": "2692.00000000",
      "3. low": "2464.06000000",
      "4. close": "2536.25000000",
      "5. volume": "45791.98430613"
    },
    "2025-02-09": {
      "1. open": "2802.52000000",
      "2. high": "2829.50000000",
      "3. low": "2096.82000000",
      "4. close": "2550.14000000",
      "5. volume": "94397.77872062"
    },
    "2025-02-02": {
      "1. open": "3084.11000000",
      "2. high": "3306.02000000",
      "3. low": "2685.00000000",
      "4. close": "2803.51000000",
      "5. volume": "51950.99674117"
    },
    "2025-01-26": {
      "1. open": "3126.82000000",
      "2. high": "3341.26000000",
      "3. low": "3055.19000000",
      "4. close": "3085.00000000",
      "5. volume": "55300.16186646"
    },
    "2025-01-19": {
      "1. open": "3190.49000000",
      "2. high": "3425.13000000",
      "3. low": "2859.75000000",
      "4. close": "3126.43000000",
      "5. volume": "58397.36166616"
    },
    "2025-01-12": {
      "1. open": "3531.09000000",
      "2. high": "3602.23000000",
      "3. low": "3068.70000000",
      "4. close": "3189.87000000",
      "5. volume": "35437.45312998"
    },
    "2025-01-05": {
      "1. open": "3210.28000000",
      "2. high": "3565.97000000",
      "3. low": "3169.38000000",
      "4. close": "3531.94000000",
      "5. volume": "29072.86905120"
    },
    "2024-12-29": {
      "1. open": "3144.69000000",
      "2. high": "3410.44000000",
      "3. low": "3083.63000000",
      "4. close": "3210.89000000",
      "5. volume": "31716.22005141"
    },
    "2024-12-22": {
      "1. open": "3758.94000000",
      "2. high": "3900.51000000",
      "3. low": "2976.34000000",
      "4. close": "3144.04000000",
      "5. volume": "60183.48100985"
    },
    "2024-12-15": {
      "1. open": "3788.62000000",
      "2. high": "3801.00000000",
      "3. low": "3305.40000000",
      "4. close": "3758.32000000",
      "5. volume": "41451.05880343"
    },
    "2024-12-08": {
      "1. open": "3512.76000000",
      "2. high": "3875.63000000",
      "3. low": "3327.15000000",
      "4. close": "3790.89000000",
      "5. volume": "46606.04831358"
    },
    "2024-12-01": {
      "1. open": "3204.58000000",
      "2. high": "3542.34000000",
      "3. low": "3110.07000000",
      "4. close": "3512.90000000",
      "5. volume": "58897.11908884"
    },
    "2024-11-24": {
      "1. open": "2911.05000000",
      "2. high": "3343.33000000",
      "3. low": "2872.97000000",
      "4. close": "3204.29000000",
      "5. volume": "66091.03495875"
    },
    "2024-11-17": {
      "1. open": "2962.19000000",
      "2. high": "3217.93000000",
      "3. low": "2850.00000000",
      "4. close": "2910.82000000",
      "5. volume": "56577.54048620"
    },
    "2024-11-10": {
      "1. open": "2265.08000000",
      "2. high": "3023.85000000",
      "3. low": "2168.00000000",
      "4. close": "2961.41000000",
      "5. volume": "39263.71150390"
    },
    "2024-11-03": {
      "1. open": "2319.86000000",
      "2. high": "2509.39000000",
      "3. low": "2228.48000000",
      "4. close": "2265.63000000",
      "5. volume": "20718.48257077"
    },
    "2024-10-27": {
      "1. open": "2525.24000000",
      "2. high": "2544.33000000",
      "3. low": "2205.79000000",
      "4. close": "2319.20000000",
      "5. volume": "16856.62731590"
    },
    "2024-10-20": {
      "1. open": "2258.88000000",
      "2. high": "2535.00000000",
      "3. low": "2236.62000000",
      "4. close": "2524.32000000",
      "5. volume": "17876.60600787"
    },
    "2024-10-13": {
      "1. open": "2223.27000000",
      "2. high": "2296.64000000",
      "3. low": "2133.00000000",
      "4. close": "2258.81000000",
      "5. volume": "19058.29908231"
    },
    "2024-10-06": {
      "1. open": "2379.75000000",
      "2. high": "2387.75000000",
      "3. low": "2096.92000000",
      "4. close": "2223.88000000",
      "5. volume": "25750.46005343"
    },
    "2024-09-29": {
      "1. open": "2313.12000000",
      "2. high": "2447.11000000",
      "3. low": "2277.50000000",
      "4. close": "2380.45000000",
      "5. volume": "21648.97035230"
    },
    "2024-09-22": {
      "1. open": "2089.07000000",
      "2. high": "2358.37000000",
      "3. low": "2032.31000000",
      "4. close": "2312.71000000",
      "5. volume": "19909.38317723"
    },
    "2024-09-15": {
      "1. open": "2073.84000000",
      "2. high": "2226.00000000",
      "3. low": "2059.25000000",
      "4. close": "2089.48000000",
      "5. volume": "17736.06546062"
    },
    "2024-09-08": {
      "1. open": "2196.38000000",
      "2. high": "2317.16000000",
      "3. low": "1941.70000000",
      "4. close": "2073.56000000",
      "5. volume": "25619.92768819"
    },
    "2024-09-01": {
      "1. open": "2454.13000000",
      "2. high": "2466.15000000",
      "3. low": "2143.88000000",
      "4. close": "2198.68000000",
      "5. volume": "17929.54490500"
    },
    "2024-08-25": {
      "1. open": "2370.70000000",
      "2. high": "2519.53000000",
      "3. low": "2282.50000000",
      "4. close": "2454.54000000",
      "5. volume": "17860.70373998"
    },
    "2024-08-18": {
      "1. open": "2342.05000000",
      "2. high": "2524.00000000",
      "3. low": "2296.05000000",
      "4. close": "2370.29000000",
      "5. volume": "22004.43441703"
    },
    "2024-08-11": {
      "1. open": "2464.78000000",
      "2. high": "2496.51000000",
      "3. low": "1941.08000000",
      "4. close": "2341.79000000",
      "5. volume": "58291.03423757"
    },
    "2024-08-04": {
      "1. open": "3012.93000000",
      "2. high": "3133.16000000",
      "3. low": "2416.00000000",
      "4. close": "2464.46000000",
      "5. volume": "27610.29385289"
    },
    "2024-07-28": {
      "1. open": "3242.55000000",
      "2. high": "3268.69000000",
      "3. low": "2847.47000000",
      "4. close": "3012.12000000",
      "5. volume": "24917.80756566"
    },
    "2024-07-21": {
      "1. open": "2981.52000000",
      "2. high": "3256.13000000",
      "3. low": "2971.41000000",
      "4. close": "3243.51000000",
      "5. volume": "17312.39731369"
    },
    "2024-07-14": {
      "1. open": "2705.94000000",
      "2. high": "3004.80000000",
      "3. low": "2608.00000000",
      "4. close": "2982.06000000",
      "5. volume": "23533.68332189"
    },
    "2024-07-07": {
      "1. open": "3199.02000000",
      "2. high": "3275.00000000",
      "3. low": "2597.21000000",
      "4. close": "2707.17000000",
      "5. volume": "24817.40909422"
    },
    "2024-06-30": {
      "1. open": "3198.48000000",
      "2. high": "3260.00000000",
      "3. low": "3014.81000000",
      "4. close": "3198.52000000",
      "5. volume": "18882.05470915"
    },
    "2024-06-23": {
      "1. open": "3385.45000000",
      "2. high": "3397.49000000",
      "3. low": "3126.55000000",
      "4. close": "3198.70000000",
      "5. volume": "18272.96603046"
    },
    "2024-06-16": {
      "1. open": "3440.33000000",
      "2. high": "3455.33000000",
      "3. low": "3145.43000000",
      "4. close": "3385.25000000",
      "5. volume": "23350.32012412"
    },
    "2024-06-09": {
      "1. open": "3482.64000000",
      "2. high": "3572.30000000",
      "3. low": "3315.32000000",
      "4. close": "3440.31000000",
      "5. volume": "19138.04014213"
    },
    "2024-06-02": {
      "1. open": "3526.77000000",
      "2. high": "3658.41000000",
      "3. low": "3424.17000000",
      "4. close": "3484.69000000",
      "5. volume": "20890.42698352"
    },
    "2024-05-26": {
      "1. open": "2823.87000000",
      "2. high": "3636.98000000",
      "3. low": "2802.80000000",
      "4. close": "3526.15000000",
      "5. volume": "41926.94799782"
    },
    "2024-05-19": {
      "1. open": "2721.16000000",
      "2. high": "2896.11000000",
      "3. low": "2644.76000000",
      "4. close": "2823.47000000",
      "5. volume": "24141.81977669"
    },
    "2024-05-12": {
      "1. open": "2915.58000000",
      "2. high": "2990.50000000",
      "3. low": "2673.14000000",
      "4. close": "2719.32000000",
      "5. volume": "19954.11023420"
    },
    "2024-05-05": {
      "1. open": "3047.27000000",
      "2. high": "3068.73000000",
      "3. low": "2636.70000000",
      "4. close": "2915.95000000",
      "5. volume": "32549.15746624"
    },
    "2024-04-28": {
      "1. open": "2955.71000000",
      "2. high": "3140.31000000",
      "3. low": "2865.00000000",
      "4. close": "3047.19000000",
      "5. volume": "22462.60494444"
    }
  }
}

In [13]:
import json

status_cd = response_eth.status_code
Ethereum = response_eth.json()

print(json.dumps(Ethereum, indent=2))

{
  "Meta Data": {
    "1. Information": "Weekly Prices and Volumes for Digital Currency",
    "2. Digital Currency Code": "ETH",
    "3. Digital Currency Name": "Ethereum",
    "4. Market Code": "EUR",
    "5. Market Name": "Euro",
    "6. Last Refreshed": "2025-04-03 00:00:00",
    "7. Time Zone": "UTC"
  },
  "Time Series (Digital Currency Weekly)": {
    "2025-04-03": {
      "1. open": "1670.57000000",
      "2. high": "1795.00000000",
      "3. low": "1640.81000000",
      "4. close": "1671.29000000",
      "5. volume": "47624.97437019"
    },
    "2025-03-30": {
      "1. open": "1849.23000000",
      "2. high": "1945.20000000",
      "3. low": "1635.00000000",
      "4. close": "1669.86000000",
      "5. volume": "64432.13343915"
    },
    "2025-03-23": {
      "1. open": "1735.03000000",
      "2. high": "1898.07000000",
      "3. low": "1710.92000000",
      "4. close": "1849.98000000",
      "5. volume": "49409.12563792"
    },
    "2025-03-16": {
      "1. open": "1860.63000000",
      "2. high": "1985.93000000",
      "3. low": "1616.86000000",
      "4. close": "1735.26000000",
      "5. volume": "95653.82797713"
    },
    "2025-03-09": {
      "1. open": "2421.48000000",
      "2. high": "2426.40000000",
      "3. low": "1832.78000000",
      "4. close": "1859.68000000",
      "5. volume": "92640.20045031"
    },
    "2025-03-02": {
      "1. open": "2691.28000000",
      "2. high": "2708.39000000",
      "3. low": "1994.22000000",
      "4. close": "2421.03000000",
      "5. volume": "109277.77896004"
    },
    "2025-02-23": {
      "1. open": "2538.61000000",
      "2. high": "2724.62000000",
      "3. low": "2494.06000000",
      "4. close": "2691.55000000",
      "5. volume": "52440.66009421"
    },
    "2025-02-16": {
      "1. open": "2551.22000000",
      "2. high": "2692.00000000",
      "3. low": "2464.06000000",
      "4. close": "2536.25000000",
      "5. volume": "45791.98430613"
    },
    "2025-02-09": {
      "1. open": "2802.52000000",
      "2. high": "2829.50000000",
      "3. low": "2096.82000000",
      "4. close": "2550.14000000",
      "5. volume": "94397.77872062"
    },
    "2025-02-02": {
      "1. open": "3084.11000000",
      "2. high": "3306.02000000",
      "3. low": "2685.00000000",
      "4. close": "2803.51000000",
      "5. volume": "51950.99674117"
    },
    "2025-01-26": {
      "1. open": "3126.82000000",
      "2. high": "3341.26000000",
      "3. low": "3055.19000000",
      "4. close": "3085.00000000",
      "5. volume": "55300.16186646"
    },
    "2025-01-19": {
      "1. open": "3190.49000000",
      "2. high": "3425.13000000",
      "3. low": "2859.75000000",
      "4. close": "3126.43000000",
      "5. volume": "58397.36166616"
    },
    "2025-01-12": {
      "1. open": "3531.09000000",
      "2. high": "3602.23000000",
      "3. low": "3068.70000000",
      "4. close": "3189.87000000",
      "5. volume": "35437.45312998"
    },
    "2025-01-05": {
      "1. open": "3210.28000000",
      "2. high": "3565.97000000",
      "3. low": "3169.38000000",
      "4. close": "3531.94000000",
      "5. volume": "29072.86905120"
    },
    "2024-12-29": {
      "1. open": "3144.69000000",
      "2. high": "3410.44000000",
      "3. low": "3083.63000000",
      "4. close": "3210.89000000",
      "5. volume": "31716.22005141"
    },
    "2024-12-22": {
      "1. open": "3758.94000000",
      "2. high": "3900.51000000",
      "3. low": "2976.34000000",
      "4. close": "3144.04000000",
      "5. volume": "60183.48100985"
    },
    "2024-12-15": {
      "1. open": "3788.62000000",
      "2. high": "3801.00000000",
      "3. low": "3305.40000000",
      "4. close": "3758.32000000",
      "5. volume": "41451.05880343"
    },
    "2024-12-08": {
      "1. open": "3512.76000000",
      "2. high": "3875.63000000",
      "3. low": "3327.15000000",
      "4. close": "3790.89000000",
      "5. volume": "46606.04831358"
    },
    "2024-12-01": {
      "1. open": "3204.58000000",
      "2. high": "3542.34000000",
      "3. low": "3110.07000000",
      "4. close": "3512.90000000",
      "5. volume": "58897.11908884"
    },
    "2024-11-24": {
      "1. open": "2911.05000000",
      "2. high": "3343.33000000",
      "3. low": "2872.97000000",
      "4. close": "3204.29000000",
      "5. volume": "66091.03495875"
    },
    "2024-11-17": {
      "1. open": "2962.19000000",
      "2. high": "3217.93000000",
      "3. low": "2850.00000000",
      "4. close": "2910.82000000",
      "5. volume": "56577.54048620"
    },
    "2024-11-10": {
      "1. open": "2265.08000000",
      "2. high": "3023.85000000",
      "3. low": "2168.00000000",
      "4. close": "2961.41000000",
      "5. volume": "39263.71150390"
    },
    "2024-11-03": {
      "1. open": "2319.86000000",
      "2. high": "2509.39000000",
      "3. low": "2228.48000000",
      "4. close": "2265.63000000",
      "5. volume": "20718.48257077"
    },
    "2024-10-27": {
      "1. open": "2525.24000000",
      "2. high": "2544.33000000",
      "3. low": "2205.79000000",
      "4. close": "2319.20000000",
      "5. volume": "16856.62731590"
    },
    "2024-10-20": {
      "1. open": "2258.88000000",
      "2. high": "2535.00000000",
      "3. low": "2236.62000000",
      "4. close": "2524.32000000",
      "5. volume": "17876.60600787"
    },
    "2024-10-13": {
      "1. open": "2223.27000000",
      "2. high": "2296.64000000",
      "3. low": "2133.00000000",
      "4. close": "2258.81000000",
      "5. volume": "19058.29908231"
    },
    "2024-10-06": {
      "1. open": "2379.75000000",
      "2. high": "2387.75000000",
      "3. low": "2096.92000000",
      "4. close": "2223.88000000",
      "5. volume": "25750.46005343"
    },
    "2024-09-29": {
      "1. open": "2313.12000000",
      "2. high": "2447.11000000",
      "3. low": "2277.50000000",
      "4. close": "2380.45000000",
      "5. volume": "21648.97035230"
    },
    "2024-09-22": {
      "1. open": "2089.07000000",
      "2. high": "2358.37000000",
      "3. low": "2032.31000000",
      "4. close": "2312.71000000",
      "5. volume": "19909.38317723"
    },
    "2024-09-15": {
      "1. open": "2073.84000000",
      "2. high": "2226.00000000",
      "3. low": "2059.25000000",
      "4. close": "2089.48000000",
      "5. volume": "17736.06546062"
    },
    "2024-09-08": {
      "1. open": "2196.38000000",
      "2. high": "2317.16000000",
      "3. low": "1941.70000000",
      "4. close": "2073.56000000",
      "5. volume": "25619.92768819"
    },
    "2024-09-01": {
      "1. open": "2454.13000000",
      "2. high": "2466.15000000",
      "3. low": "2143.88000000",
      "4. close": "2198.68000000",
      "5. volume": "17929.54490500"
    },
    "2024-08-25": {
      "1. open": "2370.70000000",
      "2. high": "2519.53000000",
      "3. low": "2282.50000000",
      "4. close": "2454.54000000",
      "5. volume": "17860.70373998"
    },
    "2024-08-18": {
      "1. open": "2342.05000000",
      "2. high": "2524.00000000",
      "3. low": "2296.05000000",
      "4. close": "2370.29000000",
      "5. volume": "22004.43441703"
    },
    "2024-08-11": {
      "1. open": "2464.78000000",
      "2. high": "2496.51000000",
      "3. low": "1941.08000000",
      "4. close": "2341.79000000",
      "5. volume": "58291.03423757"
    },
    "2024-08-04": {
      "1. open": "3012.93000000",
      "2. high": "3133.16000000",
      "3. low": "2416.00000000",
      "4. close": "2464.46000000",
      "5. volume": "27610.29385289"
    },
    "2024-07-28": {
      "1. open": "3242.55000000",
      "2. high": "3268.69000000",
      "3. low": "2847.47000000",
      "4. close": "3012.12000000",
      "5. volume": "24917.80756566"
    },
    "2024-07-21": {
      "1. open": "2981.52000000",
      "2. high": "3256.13000000",
      "3. low": "2971.41000000",
      "4. close": "3243.51000000",
      "5. volume": "17312.39731369"
    },
    "2024-07-14": {
      "1. open": "2705.94000000",
      "2. high": "3004.80000000",
      "3. low": "2608.00000000",
      "4. close": "2982.06000000",
      "5. volume": "23533.68332189"
    },
    "2024-07-07": {
      "1. open": "3199.02000000",
      "2. high": "3275.00000000",
      "3. low": "2597.21000000",
      "4. close": "2707.17000000",
      "5. volume": "24817.40909422"
    },
    "2024-06-30": {
      "1. open": "3198.48000000",
      "2. high": "3260.00000000",
      "3. low": "3014.81000000",
      "4. close": "3198.52000000",
      "5. volume": "18882.05470915"
    },
    "2024-06-23": {
      "1. open": "3385.45000000",
      "2. high": "3397.49000000",
      "3. low": "3126.55000000",
      "4. close": "3198.70000000",
      "5. volume": "18272.96603046"
    },
    "2024-06-16": {
      "1. open": "3440.33000000",
      "2. high": "3455.33000000",
      "3. low": "3145.43000000",
      "4. close": "3385.25000000",
      "5. volume": "23350.32012412"
    },
    "2024-06-09": {
      "1. open": "3482.64000000",
      "2. high": "3572.30000000",
      "3. low": "3315.32000000",
      "4. close": "3440.31000000",
      "5. volume": "19138.04014213"
    },
    "2024-06-02": {
      "1. open": "3526.77000000",
      "2. high": "3658.41000000",
      "3. low": "3424.17000000",
      "4. close": "3484.69000000",
      "5. volume": "20890.42698352"
    },
    "2024-05-26": {
      "1. open": "2823.87000000",
      "2. high": "3636.98000000",
      "3. low": "2802.80000000",
      "4. close": "3526.15000000",
      "5. volume": "41926.94799782"
    },
    "2024-05-19": {
      "1. open": "2721.16000000",
      "2. high": "2896.11000000",
      "3. low": "2644.76000000",
      "4. close": "2823.47000000",
      "5. volume": "24141.81977669"
    },
    "2024-05-12": {
      "1. open": "2915.58000000",
      "2. high": "2990.50000000",
      "3. low": "2673.14000000",
      "4. close": "2719.32000000",
      "5. volume": "19954.11023420"
    },
    "2024-05-05": {
      "1. open": "3047.27000000",
      "2. high": "3068.73000000",
      "3. low": "2636.70000000",
      "4. close": "2915.95000000",
      "5. volume": "32549.15746624"
    },
    "2024-04-28": {
      "1. open": "2955.71000000",
      "2. high": "3140.31000000",
      "3. low": "2865.00000000",
      "4. close": "3047.19000000",
      "5. volume": "22462.60494444"
    }
  }
}

In [15]:
import json
import pandas as pd

# Assuming response_btc is your API response
status_cd = response_eth.status_code
Ethereum = response_eth.json()

# Print the raw data to understand its structure (debugging)
print(json.dumps(Ethereum, indent=2))

# Initialize lists to store data
dates = []
opens = []
highs = []
lows = []
closes = []
volumes = []

# Extract metadata
meta_data = data.get("Meta Data", {})
digital_currency_name = meta_data.get("Digital Currency Name", "Ethereum")

# Extract time series data
time_series_key = "Time Series (Digital Currency Weekly)"
time_series = data.get(time_series_key, {})

for date_str, values in time_series.items():
    dates.append(date_str)
    opens.append(float(values.get("1. open", 0)))
    highs.append(float(values.get("2. high", 0)))
    lows.append(float(values.get("3. low", 0)))
    closes.append(float(values.get("4. close", 0)))
    volumes.append(float(values.get("5. volume", 0)))

# Create DataFrame
Ethereum = pd.DataFrame({
    "date": dates,
    "open": opens,
    "high": highs,
    "low": lows,
    "close": closes,
    "volume": volumes,
    "currency_name": digital_currency_name
})

# Convert date column to datetime and sort
Ethereum['date'] = pd.to_datetime(Ethereum['date'])
Ethereum = Ethereum.sort_values('date', ascending=False)

# Display the DataFrame
print(Ethereum.head())

# Optional: Save to CSV
Ethereum.to_csv('Ethereum_Weekly_Prices.csv', index=False)

{
  "Meta Data": {
    "1. Information": "Weekly Prices and Volumes for Digital Currency",
    "2. Digital Currency Code": "ETH",
    "3. Digital Currency Name": "Ethereum",
    "4. Market Code": "EUR",
    "5. Market Name": "Euro",
    "6. Last Refreshed": "2025-04-03 00:00:00",
    "7. Time Zone": "UTC"
  },
  "Time Series (Digital Currency Weekly)": {
    "2025-04-03": {
      "1. open": "1670.57000000",
      "2. high": "1795.00000000",
      "3. low": "1640.81000000",
      "4. close": "1671.29000000",
      "5. volume": "47624.97437019"
    },
    "2025-03-30": {
      "1. open": "1849.23000000",
      "2. high": "1945.20000000",
      "3. low": "1635.00000000",
      "4. close": "1669.86000000",
      "5. volume": "64432.13343915"
    },
    "2025-03-23": {
      "1. open": "1735.03000000",
      "2. high": "1898.07000000",
      "3. low": "1710.92000000",
      "4. close": "1849.98000000",
      "5. volume": "49409.12563792"
    },
    "2025-03-16": {
      "1. open": "1860.63000000",
      "2. high": "1985.93000000",
      "3. low": "1616.86000000",
      "4. close": "1735.26000000",
      "5. volume": "95653.82797713"
    },
    "2025-03-09": {
      "1. open": "2421.48000000",
      "2. high": "2426.40000000",
      "3. low": "1832.78000000",
      "4. close": "1859.68000000",
      "5. volume": "92640.20045031"
    },
    "2025-03-02": {
      "1. open": "2691.28000000",
      "2. high": "2708.39000000",
      "3. low": "1994.22000000",
      "4. close": "2421.03000000",
      "5. volume": "109277.77896004"
    },
    "2025-02-23": {
      "1. open": "2538.61000000",
      "2. high": "2724.62000000",
      "3. low": "2494.06000000",
      "4. close": "2691.55000000",
      "5. volume": "52440.66009421"
    },
    "2025-02-16": {
      "1. open": "2551.22000000",
      "2. high": "2692.00000000",
      "3. low": "2464.06000000",
      "4. close": "2536.25000000",
      "5. volume": "45791.98430613"
    },
    "2025-02-09": {
      "1. open": "2802.52000000",
      "2. high": "2829.50000000",
      "3. low": "2096.82000000",
      "4. close": "2550.14000000",
      "5. volume": "94397.77872062"
    },
    "2025-02-02": {
      "1. open": "3084.11000000",
      "2. high": "3306.02000000",
      "3. low": "2685.00000000",
      "4. close": "2803.51000000",
      "5. volume": "51950.99674117"
    },
    "2025-01-26": {
      "1. open": "3126.82000000",
      "2. high": "3341.26000000",
      "3. low": "3055.19000000",
      "4. close": "3085.00000000",
      "5. volume": "55300.16186646"
    },
    "2025-01-19": {
      "1. open": "3190.49000000",
      "2. high": "3425.13000000",
      "3. low": "2859.75000000",
      "4. close": "3126.43000000",
      "5. volume": "58397.36166616"
    },
    "2025-01-12": {
      "1. open": "3531.09000000",
      "2. high": "3602.23000000",
      "3. low": "3068.70000000",
      "4. close": "3189.87000000",
      "5. volume": "35437.45312998"
    },
    "2025-01-05": {
      "1. open": "3210.28000000",
      "2. high": "3565.97000000",
      "3. low": "3169.38000000",
      "4. close": "3531.94000000",
      "5. volume": "29072.86905120"
    },
    "2024-12-29": {
      "1. open": "3144.69000000",
      "2. high": "3410.44000000",
      "3. low": "3083.63000000",
      "4. close": "3210.89000000",
      "5. volume": "31716.22005141"
    },
    "2024-12-22": {
      "1. open": "3758.94000000",
      "2. high": "3900.51000000",
      "3. low": "2976.34000000",
      "4. close": "3144.04000000",
      "5. volume": "60183.48100985"
    },
    "2024-12-15": {
      "1. open": "3788.62000000",
      "2. high": "3801.00000000",
      "3. low": "3305.40000000",
      "4. close": "3758.32000000",
      "5. volume": "41451.05880343"
    },
    "2024-12-08": {
      "1. open": "3512.76000000",
      "2. high": "3875.63000000",
      "3. low": "3327.15000000",
      "4. close": "3790.89000000",
      "5. volume": "46606.04831358"
    },
    "2024-12-01": {
      "1. open": "3204.58000000",
      "2. high": "3542.34000000",
      "3. low": "3110.07000000",
      "4. close": "3512.90000000",
      "5. volume": "58897.11908884"
    },
    "2024-11-24": {
      "1. open": "2911.05000000",
      "2. high": "3343.33000000",
      "3. low": "2872.97000000",
      "4. close": "3204.29000000",
      "5. volume": "66091.03495875"
    },
    "2024-11-17": {
      "1. open": "2962.19000000",
      "2. high": "3217.93000000",
      "3. low": "2850.00000000",
      "4. close": "2910.82000000",
      "5. volume": "56577.54048620"
    },
    "2024-11-10": {
      "1. open": "2265.08000000",
      "2. high": "3023.85000000",
      "3. low": "2168.00000000",
      "4. close": "2961.41000000",
      "5. volume": "39263.71150390"
    },
    "2024-11-03": {
      "1. open": "2319.86000000",
      "2. high": "2509.39000000",
      "3. low": "2228.48000000",
      "4. close": "2265.63000000",
      "5. volume": "20718.48257077"
    },
    "2024-10-27": {
      "1. open": "2525.24000000",
      "2. high": "2544.33000000",
      "3. low": "2205.79000000",
      "4. close": "2319.20000000",
      "5. volume": "16856.62731590"
    },
    "2024-10-20": {
      "1. open": "2258.88000000",
      "2. high": "2535.00000000",
      "3. low": "2236.62000000",
      "4. close": "2524.32000000",
      "5. volume": "17876.60600787"
    },
    "2024-10-13": {
      "1. open": "2223.27000000",
      "2. high": "2296.64000000",
      "3. low": "2133.00000000",
      "4. close": "2258.81000000",
      "5. volume": "19058.29908231"
    },
    "2024-10-06": {
      "1. open": "2379.75000000",
      "2. high": "2387.75000000",
      "3. low": "2096.92000000",
      "4. close": "2223.88000000",
      "5. volume": "25750.46005343"
    },
    "2024-09-29": {
      "1. open": "2313.12000000",
      "2. high": "2447.11000000",
      "3. low": "2277.50000000",
      "4. close": "2380.45000000",
      "5. volume": "21648.97035230"
    },
    "2024-09-22": {
      "1. open": "2089.07000000",
      "2. high": "2358.37000000",
      "3. low": "2032.31000000",
      "4. close": "2312.71000000",
      "5. volume": "19909.38317723"
    },
    "2024-09-15": {
      "1. open": "2073.84000000",
      "2. high": "2226.00000000",
      "3. low": "2059.25000000",
      "4. close": "2089.48000000",
      "5. volume": "17736.06546062"
    },
    "2024-09-08": {
      "1. open": "2196.38000000",
      "2. high": "2317.16000000",
      "3. low": "1941.70000000",
      "4. close": "2073.56000000",
      "5. volume": "25619.92768819"
    },
    "2024-09-01": {
      "1. open": "2454.13000000",
      "2. high": "2466.15000000",
      "3. low": "2143.88000000",
      "4. close": "2198.68000000",
      "5. volume": "17929.54490500"
    },
    "2024-08-25": {
      "1. open": "2370.70000000",
      "2. high": "2519.53000000",
      "3. low": "2282.50000000",
      "4. close": "2454.54000000",
      "5. volume": "17860.70373998"
    },
    "2024-08-18": {
      "1. open": "2342.05000000",
      "2. high": "2524.00000000",
      "3. low": "2296.05000000",
      "4. close": "2370.29000000",
      "5. volume": "22004.43441703"
    },
    "2024-08-11": {
      "1. open": "2464.78000000",
      "2. high": "2496.51000000",
      "3. low": "1941.08000000",
      "4. close": "2341.79000000",
      "5. volume": "58291.03423757"
    },
    "2024-08-04": {
      "1. open": "3012.93000000",
      "2. high": "3133.16000000",
      "3. low": "2416.00000000",
      "4. close": "2464.46000000",
      "5. volume": "27610.29385289"
    },
    "2024-07-28": {
      "1. open": "3242.55000000",
      "2. high": "3268.69000000",
      "3. low": "2847.47000000",
      "4. close": "3012.12000000",
      "5. volume": "24917.80756566"
    },
    "2024-07-21": {
      "1. open": "2981.52000000",
      "2. high": "3256.13000000",
      "3. low": "2971.41000000",
      "4. close": "3243.51000000",
      "5. volume": "17312.39731369"
    },
    "2024-07-14": {
      "1. open": "2705.94000000",
      "2. high": "3004.80000000",
      "3. low": "2608.00000000",
      "4. close": "2982.06000000",
      "5. volume": "23533.68332189"
    },
    "2024-07-07": {
      "1. open": "3199.02000000",
      "2. high": "3275.00000000",
      "3. low": "2597.21000000",
      "4. close": "2707.17000000",
      "5. volume": "24817.40909422"
    },
    "2024-06-30": {
      "1. open": "3198.48000000",
      "2. high": "3260.00000000",
      "3. low": "3014.81000000",
      "4. close": "3198.52000000",
      "5. volume": "18882.05470915"
    },
    "2024-06-23": {
      "1. open": "3385.45000000",
      "2. high": "3397.49000000",
      "3. low": "3126.55000000",
      "4. close": "3198.70000000",
      "5. volume": "18272.96603046"
    },
    "2024-06-16": {
      "1. open": "3440.33000000",
      "2. high": "3455.33000000",
      "3. low": "3145.43000000",
      "4. close": "3385.25000000",
      "5. volume": "23350.32012412"
    },
    "2024-06-09": {
      "1. open": "3482.64000000",
      "2. high": "3572.30000000",
      "3. low": "3315.32000000",
      "4. close": "3440.31000000",
      "5. volume": "19138.04014213"
    },
    "2024-06-02": {
      "1. open": "3526.77000000",
      "2. high": "3658.41000000",
      "3. low": "3424.17000000",
      "4. close": "3484.69000000",
      "5. volume": "20890.42698352"
    },
    "2024-05-26": {
      "1. open": "2823.87000000",
      "2. high": "3636.98000000",
      "3. low": "2802.80000000",
      "4. close": "3526.15000000",
      "5. volume": "41926.94799782"
    },
    "2024-05-19": {
      "1. open": "2721.16000000",
      "2. high": "2896.11000000",
      "3. low": "2644.76000000",
      "4. close": "2823.47000000",
      "5. volume": "24141.81977669"
    },
    "2024-05-12": {
      "1. open": "2915.58000000",
      "2. high": "2990.50000000",
      "3. low": "2673.14000000",
      "4. close": "2719.32000000",
      "5. volume": "19954.11023420"
    },
    "2024-05-05": {
      "1. open": "3047.27000000",
      "2. high": "3068.73000000",
      "3. low": "2636.70000000",
      "4. close": "2915.95000000",
      "5. volume": "32549.15746624"
    },
    "2024-04-28": {
      "1. open": "2955.71000000",
      "2. high": "3140.31000000",
      "3. low": "2865.00000000",
      "4. close": "3047.19000000",
      "5. volume": "22462.60494444"
    }
  }
}
        date      open      high       low     close       volume  \
0 2025-04-03  76102.60  81300.00  75042.00  76365.98  1511.758573
1 2025-03-30  79441.34  82091.43  75432.48  76135.85  2003.058228
2 2025-03-23  75935.10  80150.77  74226.31  79452.90  2004.679257
3 2025-03-16  74334.78  78476.10  70570.00  75928.62  3317.850597
4 2025-03-09  90634.87  90798.09  73680.00  74310.03  4567.157247

  currency_name
0      Ethereum
1      Ethereum
2      Ethereum
3      Ethereum
4      Ethereum

In [16]:
Ethereum

,date,open,high,low,close,volume,currency_name
0,2025-04-03,76102.60,81300.00,75042.00,76365.98,1511.758573,Ethereum
1,2025-03-30,79441.34,82091.43,75432.48,76135.85,2003.058228,Ethereum
2,2025-03-23,75935.10,80150.77,74226.31,79452.90,2004.679257,Ethereum
3,2025-03-16,74334.78,78476.10,70570.00,75928.62,3317.850597,Ethereum
4,2025-03-09,90634.87,90798.09,73680.00,74310.03,4567.157247,Ethereum
5,2025-03-02,91900.51,92078.26,75141.16,90642.23,5817.439540,Ethereum
6,2025-02-23,91620.25,94977.61,89368.01,91874.60,1663.379136,Ethereum
7,2025-02-16,93636.05,95586.34,91150.00,91634.19,1897.108324,Ethereum
8,2025-02-09,95431.64,99421.84,89248.90,93607.15,3166.384578,Ethereum
9,2025-02-02,98050.00,102000.00,93414.78,95427.29,2910.038615,Ethereum
10,2025-01-26,98539.45,105951.19,96436.00,98088.57,3658.556952,Ethereum
11,2025-01-19,92284.22,103599.98,87437.71,98574.14,3343.997587,Ethereum
12,2025-01-12,95456.12,98960.78,88606.32,92337.55,2445.366454,Ethereum
13,2025-01-05,89692.71,96143.44,87834.22,95451.75,2005.555398,Ethereum
14,2024-12-29,91182.16,96129.98,88832.59,89702.09,2344.018261,Ethereum
15,2024-12-22,99120.98,103000.00,88421.18,91204.69,4072.704773,Ethereum
16,2024-12-15,95662.16,99800.00,89217.53,99111.37,2699.639924,Ethereum
17,2024-12-08,92096.25,98456.03,86600.00,95685.97,3394.001764,Ethereum
18,2024-12-01,93388.13,94400.00,86543.90,92099.58,3804.209786,Ethereum
19,2024-11-24,85046.28,95501.25,84594.12,93391.61,5630.824666,Ethereum
20,2024-11-17,74780.73,88000.00,74639.10,85016.99,6663.358494,Ethereum
21,2024-11-10,63408.26,75699.99,61410.68,74757.19,3545.725778,Ethereum
22,2024-11-03,62928.68,68000.00,62351.09,63426.11,2261.177721,Ethereum
23,2024-10-27,63445.78,63900.00,60465.00,62928.34,1786.109662,Ethereum
24,2024-10-20,57516.93,63779.18,57148.57,63433.63,2063.919625,Ethereum
25,2024-10-13,57256.48,58723.00,53904.09,57519.27,1245.490320,Ethereum
26,2024-10-06,58752.02,58757.86,54237.15,57248.79,1637.161104,Ethereum
27,2024-09-29,56988.75,59528.74,56080.15,58742.25,1390.314409,Ethereum
28,2024-09-22,53320.98,57414.44,51650.17,57001.09,1655.130712,Ethereum
29,2024-09-15,49526.79,54781.85,49315.32,53343.95,1707.000856,Ethereum
30,2024-09-08,51911.95,54065.45,47428.66,49505.02,2198.290552,Ethereum
31,2024-09-01,57406.50,57632.29,51802.75,51931.36,1877.162877,Ethereum
32,2024-08-25,53049.34,58113.94,52408.27,57402.19,2010.869248,Ethereum
33,2024-08-18,53822.14,56141.89,51195.03,53046.89,1836.960865,Ethereum
34,2024-08-11,53330.01,57499.00,45021.36,53835.66,5859.416666,Ethereum
35,2024-08-04,62866.50,64749.00,52521.27,53309.69,3522.976055,Ethereum
36,2024-07-28,62526.97,63876.72,58512.00,62854.02,1840.762229,Ethereum
37,2024-07-21,55876.94,62721.17,55750.00,62529.01,2216.336373,Ethereum
38,2024-07-14,51589.15,56400.63,50144.21,55876.86,5468.184149,Ethereum
39,2024-07-07,58416.69,59467.74,49437.20,51589.15,3660.076765,Ethereum
40,2024-06-30,59127.81,59261.30,54419.19,58407.41,2451.792702,Ethereum
41,2024-06-23,62279.16,62696.68,59085.16,59107.12,1526.556657,Ethereum
42,2024-06-16,64664.14,65298.24,60801.06,62262.17,1826.636652,Ethereum
43,2024-06-09,62428.48,66132.47,62283.90,64648.18,1890.770514,Ethereum
44,2024-06-02,63145.80,64989.91,61440.00,62452.47,1558.529962,Ethereum
45,2024-05-26,60930.51,65933.02,60750.00,63138.93,2469.255271,Ethereum
46,2024-05-19,57085.97,62261.43,56418.03,60927.75,2144.931916,Ethereum
47,2024-05-12,59515.05,60834.00,55876.05,57075.98,2126.963162,Ethereum
48,2024-05-05,58965.50,60365.57,52943.49,59506.98,4178.038841,Ethereum
49,2024-04-28,60985.08,63134.63,58411.49,58947.56,2398.396625,Ethereum

# Solana

In [17]:
import requests

urll = f'https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_WEEKLY&symbol=SOL&market=EUR&apikey={api_key}'
response_sol = requests.get(urll)
response_sol

In [18]:
import json

status_co = response_sol.status_code
Solana = response_sol.json()

print(json.dumps(Solana, indent=2))

{
  "Meta Data": {
    "1. Information": "Weekly Prices and Volumes for Digital Currency",
    "2. Digital Currency Code": "SOL",
    "3. Digital Currency Name": "Solana",
    "4. Market Code": "EUR",
    "5. Market Name": "Euro",
    "6. Last Refreshed": "2025-04-03 00:00:00",
    "7. Time Zone": "UTC"
  },
  "Time Series (Digital Currency Weekly)": {
    "2025-04-03": {
      "1. open": "115.33000000",
      "2. high": "124.76000000",
      "3. low": "106.71000000",
      "4. close": "109.91000000",
      "5. volume": "214066.51600000"
    },
    "2025-03-30": {
      "1. open": "122.48000000",
      "2. high": "136.49000000",
      "3. low": "113.39000000",
      "4. close": "115.35000000",
      "5. volume": "284318.81300000"
    },
    "2025-03-23": {
      "1. open": "115.92000000",
      "2. high": "124.75000000",
      "3. low": "111.65000000",
      "4. close": "122.47000000",
      "5. volume": "229466.66100000"
    },
    "2025-03-16": {
      "1. open": "116.52000000",
      "2. high": "125.78000000",
      "3. low": "103.31000000",
      "4. close": "115.94000000",
      "5. volume": "405395.76000000"
    },
    "2025-03-09": {
      "1. open": "171.93000000",
      "2. high": "172.39000000",
      "3. low": "115.56000000",
      "4. close": "116.39000000",
      "5. volume": "611674.47700000"
    },
    "2025-03-02": {
      "1. open": "160.46000000",
      "2. high": "174.29000000",
      "3. low": "120.74000000",
      "4. close": "171.91000000",
      "5. volume": "747086.94800000"
    },
    "2025-02-23": {
      "1. open": "179.66000000",
      "2. high": "180.72000000",
      "3. low": "153.93000000",
      "4. close": "160.39000000",
      "5. volume": "382617.81300000"
    },
    "2025-02-16": {
      "1. open": "194.67000000",
      "2. high": "202.72000000",
      "3. low": "178.00000000",
      "4. close": "179.68000000",
      "5. volume": "301778.53500000"
    },
    "2025-02-09": {
      "1. open": "198.57000000",
      "2. high": "213.51000000",
      "3. low": "172.03000000",
      "4. close": "194.53000000",
      "5. volume": "533328.25300000"
    },
    "2025-02-02": {
      "1. open": "229.70000000",
      "2. high": "234.51000000",
      "3. low": "188.02000000",
      "4. close": "198.71000000",
      "5. volume": "502648.43400000"
    },
    "2025-01-26": {
      "1. open": "245.78000000",
      "2. high": "265.45000000",
      "3. low": "221.90000000",
      "4. close": "229.82000000",
      "5. volume": "524315.33700000"
    },
    "2025-01-19": {
      "1. open": "184.00000000",
      "2. high": "287.00000000",
      "3. low": "165.50000000",
      "4. close": "245.72000000",
      "5. volume": "832442.61800000"
    },
    "2025-01-12": {
      "1. open": "207.15000000",
      "2. high": "214.87000000",
      "3. low": "176.94000000",
      "4. close": "183.92000000",
      "5. volume": "297756.52700000"
    },
    "2025-01-05": {
      "1. open": "181.58000000",
      "2. high": "213.55000000",
      "3. low": "178.70000000",
      "4. close": "207.10000000",
      "5. volume": "201165.97000000"
    },
    "2024-12-29": {
      "1. open": "172.96000000",
      "2. high": "194.02000000",
      "3. low": "169.17000000",
      "4. close": "181.59000000",
      "5. volume": "267478.81500000"
    },
    "2024-12-22": {
      "1. open": "213.00000000",
      "2. high": "217.97000000",
      "3. low": "168.23000000",
      "4. close": "172.99000000",
      "5. volume": "473214.55600000"
    },
    "2024-12-15": {
      "1. open": "224.38000000",
      "2. high": "224.46000000",
      "3. low": "192.00000000",
      "4. close": "212.89000000",
      "5. volume": "350900.69700000"
    },
    "2024-12-08": {
      "1. open": "224.40000000",
      "2. high": "233.70000000",
      "3. low": "204.08000000",
      "4. close": "224.27000000",
      "5. volume": "441957.92100000"
    },
    "2024-12-01": {
      "1. open": "241.09000000",
      "2. high": "244.99000000",
      "3. low": "210.58000000",
      "4. close": "224.42000000",
      "5. volume": "257493.95000000"
    },
    "2024-11-24": {
      "1. open": "224.69000000",
      "2. high": "252.00000000",
      "3. low": "217.94000000",
      "4. close": "240.99000000",
      "5. volume": "451439.46200000"
    },
    "2024-11-17": {
      "1. open": "195.68000000",
      "2. high": "228.60000000",
      "3. low": "185.00000000",
      "4. close": "224.77000000",
      "5. volume": "495033.64600000"
    },
    "2024-11-10": {
      "1. open": "149.69000000",
      "2. high": "200.22000000",
      "3. low": "142.44000000",
      "4. close": "195.41000000",
      "5. volume": "367021.62500000"
    },
    "2024-11-03": {
      "1. open": "163.32000000",
      "2. high": "169.65000000",
      "3. low": "145.88000000",
      "4. close": "149.87000000",
      "5. volume": "189663.70100000"
    },
    "2024-10-27": {
      "1. open": "153.92000000",
      "2. high": "165.44000000",
      "3. low": "147.28000000",
      "4. close": "163.47000000",
      "5. volume": "231039.77400000"
    },
    "2024-10-20": {
      "1. open": "135.29000000",
      "2. high": "154.34000000",
      "3. low": "134.44000000",
      "4. close": "153.75000000",
      "5. volume": "172661.48800000"
    },
    "2024-10-13": {
      "1. open": "133.52000000",
      "2. high": "138.73000000",
      "3. low": "124.00000000",
      "4. close": "135.11000000",
      "5. volume": "160381.02600000"
    },
    "2024-10-06": {
      "1. open": "142.04000000",
      "2. high": "143.00000000",
      "3. low": "120.82000000",
      "4. close": "133.47000000",
      "5. volume": "236562.19200000"
    },
    "2024-09-29": {
      "1. open": "129.65000000",
      "2. high": "144.83000000",
      "3. low": "127.42000000",
      "4. close": "141.94000000",
      "5. volume": "207573.30100000"
    },
    "2024-09-22": {
      "1. open": "118.54000000",
      "2. high": "136.31000000",
      "3. low": "114.39000000",
      "4. close": "129.60000000",
      "5. volume": "201736.61600000"
    },
    "2024-09-15": {
      "1. open": "117.53000000",
      "2. high": "126.34000000",
      "3. low": "115.13000000",
      "4. close": "118.55000000",
      "5. volume": "150943.39500000"
    },
    "2024-09-08": {
      "1. open": "116.39000000",
      "2. high": "124.34000000",
      "3. low": "108.88000000",
      "4. close": "117.31000000",
      "5. volume": "185445.87900000"
    },
    "2024-09-01": {
      "1. open": "142.07000000",
      "2. high": "145.00000000",
      "3. low": "115.74000000",
      "4. close": "116.60000000",
      "5. volume": "197820.24600000"
    },
    "2024-08-25": {
      "1. open": "129.19000000",
      "2. high": "144.96000000",
      "3. low": "124.90000000",
      "4. close": "142.07000000",
      "5. volume": "182775.88400000"
    },
    "2024-08-18": {
      "1. open": "129.71000000",
      "2. high": "138.24000000",
      "3. low": "123.76000000",
      "4. close": "129.31000000",
      "5. volume": "218417.24400000"
    },
    "2024-08-11": {
      "1. open": "127.08000000",
      "2. high": "149.98000000",
      "3. low": "100.07000000",
      "4. close": "129.61000000",
      "5. volume": "457602.54900000"
    },
    "2024-08-04": {
      "1. open": "170.27000000",
      "2. high": "178.44000000",
      "3. low": "120.50000000",
      "4. close": "126.73000000",
      "5. volume": "325362.33200000"
    },
    "2024-07-28": {
      "1. open": "169.24000000",
      "2. high": "173.32000000",
      "3. low": "152.55000000",
      "4. close": "170.36000000",
      "5. volume": "300623.92600000"
    },
    "2024-07-21": {
      "1. open": "135.69000000",
      "2. high": "169.83000000",
      "3. low": "135.16000000",
      "4. close": "169.19000000",
      "5. volume": "262702.88300000"
    },
    "2024-07-14": {
      "1. open": "121.51000000",
      "2. high": "137.58000000",
      "3. low": "118.02000000",
      "4. close": "135.80000000",
      "5. volume": "304746.86700000"
    },
    "2024-07-07": {
      "1. open": "136.50000000",
      "2. high": "144.14000000",
      "3. low": "111.93000000",
      "4. close": "121.42000000",
      "5. volume": "411625.34900000"
    },
    "2024-06-30": {
      "1. open": "120.33000000",
      "2. high": "140.99000000",
      "3. low": "113.99000000",
      "4. close": "136.40000000",
      "5. volume": "306037.73400000"
    },
    "2024-06-23": {
      "1. open": "141.28000000",
      "2. high": "141.70000000",
      "3. low": "119.20000000",
      "4. close": "120.35000000",
      "5. volume": "327539.32900000"
    },
    "2024-06-16": {
      "1. open": "150.56000000",
      "2. high": "151.80000000",
      "3. low": "130.51000000",
      "4. close": "141.27000000",
      "5. volume": "270543.41900000"
    },
    "2024-06-09": {
      "1. open": "150.24000000",
      "2. high": "161.68000000",
      "3. low": "141.72000000",
      "4. close": "150.55000000",
      "5. volume": "234446.06200000"
    },
    "2024-06-02": {
      "1. open": "150.62000000",
      "2. high": "160.07000000",
      "3. low": "148.67000000",
      "4. close": "150.33000000",
      "5. volume": "244817.59300000"
    },
    "2024-05-26": {
      "1. open": "156.47000000",
      "2. high": "173.24000000",
      "3. low": "148.38000000",
      "4. close": "150.61000000",
      "5. volume": "273845.81600000"
    },
    "2024-05-19": {
      "1. open": "133.25000000",
      "2. high": "162.00000000",
      "3. low": "127.98000000",
      "4. close": "156.28000000",
      "5. volume": "280489.70200000"
    },
    "2024-05-12": {
      "1. open": "135.51000000",
      "2. high": "147.89000000",
      "3. low": "130.25000000",
      "4. close": "133.14000000",
      "5. volume": "285577.10900000"
    },
    "2024-05-05": {
      "1. open": "128.69000000",
      "2. high": "138.65000000",
      "3. low": "111.27000000",
      "4. close": "135.49000000",
      "5. volume": "365208.75200000"
    },
    "2024-04-28": {
      "1. open": "139.77000000",
      "2. high": "149.56000000",
      "3. low": "124.47000000",
      "4. close": "128.87000000",
      "5. volume": "317097.18100000"
    }
  }
}

In [19]:
import json
import pandas as pd

# Assuming response_btc is your API response
status_co = response_sol.status_code
Solana = response_eth.json()

# Print the raw data to understand its structure (debugging)
print(json.dumps(Solana, indent=2))

# Initialize lists to store data
dates = []
opens = []
highs = []
lows = []
closes = []
volumes = []

# Extract metadata
meta_data = data.get("Meta Data", {})
digital_currency_name = meta_data.get("Digital Currency Name", "Solana")

# Extract time series data
time_series_key = "Time Series (Digital Currency Weekly)"
time_series = data.get(time_series_key, {})

for date_str, values in time_series.items():
    dates.append(date_str)
    opens.append(float(values.get("1. open", 0)))
    highs.append(float(values.get("2. high", 0)))
    lows.append(float(values.get("3. low", 0)))
    closes.append(float(values.get("4. close", 0)))
    volumes.append(float(values.get("5. volume", 0)))

# Create DataFrame
Solana = pd.DataFrame({
    "date": dates,
    "open": opens,
    "high": highs,
    "low": lows,
    "close": closes,
    "volume": volumes,
    "currency_name": digital_currency_name
})

# Convert date column to datetime and sort
Solana['date'] = pd.to_datetime(Solana['date'])
Solana = Solana.sort_values('date', ascending=False)

# Display the DataFrame
print(Solana.head())

# Optional: Save to CSV
Solana.to_csv('Solana_Weekly_Data.csv', index=False)

{
  "Meta Data": {
    "1. Information": "Weekly Prices and Volumes for Digital Currency",
    "2. Digital Currency Code": "ETH",
    "3. Digital Currency Name": "Ethereum",
    "4. Market Code": "EUR",
    "5. Market Name": "Euro",
    "6. Last Refreshed": "2025-04-03 00:00:00",
    "7. Time Zone": "UTC"
  },
  "Time Series (Digital Currency Weekly)": {
    "2025-04-03": {
      "1. open": "1670.57000000",
      "2. high": "1795.00000000",
      "3. low": "1640.81000000",
      "4. close": "1671.29000000",
      "5. volume": "47624.97437019"
    },
    "2025-03-30": {
      "1. open": "1849.23000000",
      "2. high": "1945.20000000",
      "3. low": "1635.00000000",
      "4. close": "1669.86000000",
      "5. volume": "64432.13343915"
    },
    "2025-03-23": {
      "1. open": "1735.03000000",
      "2. high": "1898.07000000",
      "3. low": "1710.92000000",
      "4. close": "1849.98000000",
      "5. volume": "49409.12563792"
    },
    "2025-03-16": {
      "1. open": "1860.63000000",
      "2. high": "1985.93000000",
      "3. low": "1616.86000000",
      "4. close": "1735.26000000",
      "5. volume": "95653.82797713"
    },
    "2025-03-09": {
      "1. open": "2421.48000000",
      "2. high": "2426.40000000",
      "3. low": "1832.78000000",
      "4. close": "1859.68000000",
      "5. volume": "92640.20045031"
    },
    "2025-03-02": {
      "1. open": "2691.28000000",
      "2. high": "2708.39000000",
      "3. low": "1994.22000000",
      "4. close": "2421.03000000",
      "5. volume": "109277.77896004"
    },
    "2025-02-23": {
      "1. open": "2538.61000000",
      "2. high": "2724.62000000",
      "3. low": "2494.06000000",
      "4. close": "2691.55000000",
      "5. volume": "52440.66009421"
    },
    "2025-02-16": {
      "1. open": "2551.22000000",
      "2. high": "2692.00000000",
      "3. low": "2464.06000000",
      "4. close": "2536.25000000",
      "5. volume": "45791.98430613"
    },
    "2025-02-09": {
      "1. open": "2802.52000000",
      "2. high": "2829.50000000",
      "3. low": "2096.82000000",
      "4. close": "2550.14000000",
      "5. volume": "94397.77872062"
    },
    "2025-02-02": {
      "1. open": "3084.11000000",
      "2. high": "3306.02000000",
      "3. low": "2685.00000000",
      "4. close": "2803.51000000",
      "5. volume": "51950.99674117"
    },
    "2025-01-26": {
      "1. open": "3126.82000000",
      "2. high": "3341.26000000",
      "3. low": "3055.19000000",
      "4. close": "3085.00000000",
      "5. volume": "55300.16186646"
    },
    "2025-01-19": {
      "1. open": "3190.49000000",
      "2. high": "3425.13000000",
      "3. low": "2859.75000000",
      "4. close": "3126.43000000",
      "5. volume": "58397.36166616"
    },
    "2025-01-12": {
      "1. open": "3531.09000000",
      "2. high": "3602.23000000",
      "3. low": "3068.70000000",
      "4. close": "3189.87000000",
      "5. volume": "35437.45312998"
    },
    "2025-01-05": {
      "1. open": "3210.28000000",
      "2. high": "3565.97000000",
      "3. low": "3169.38000000",
      "4. close": "3531.94000000",
      "5. volume": "29072.86905120"
    },
    "2024-12-29": {
      "1. open": "3144.69000000",
      "2. high": "3410.44000000",
      "3. low": "3083.63000000",
      "4. close": "3210.89000000",
      "5. volume": "31716.22005141"
    },
    "2024-12-22": {
      "1. open": "3758.94000000",
      "2. high": "3900.51000000",
      "3. low": "2976.34000000",
      "4. close": "3144.04000000",
      "5. volume": "60183.48100985"
    },
    "2024-12-15": {
      "1. open": "3788.62000000",
      "2. high": "3801.00000000",
      "3. low": "3305.40000000",
      "4. close": "3758.32000000",
      "5. volume": "41451.05880343"
    },
    "2024-12-08": {
      "1. open": "3512.76000000",
      "2. high": "3875.63000000",
      "3. low": "3327.15000000",
      "4. close": "3790.89000000",
      "5. volume": "46606.04831358"
    },
    "2024-12-01": {
      "1. open": "3204.58000000",
      "2. high": "3542.34000000",
      "3. low": "3110.07000000",
      "4. close": "3512.90000000",
      "5. volume": "58897.11908884"
    },
    "2024-11-24": {
      "1. open": "2911.05000000",
      "2. high": "3343.33000000",
      "3. low": "2872.97000000",
      "4. close": "3204.29000000",
      "5. volume": "66091.03495875"
    },
    "2024-11-17": {
      "1. open": "2962.19000000",
      "2. high": "3217.93000000",
      "3. low": "2850.00000000",
      "4. close": "2910.82000000",
      "5. volume": "56577.54048620"
    },
    "2024-11-10": {
      "1. open": "2265.08000000",
      "2. high": "3023.85000000",
      "3. low": "2168.00000000",
      "4. close": "2961.41000000",
      "5. volume": "39263.71150390"
    },
    "2024-11-03": {
      "1. open": "2319.86000000",
      "2. high": "2509.39000000",
      "3. low": "2228.48000000",
      "4. close": "2265.63000000",
      "5. volume": "20718.48257077"
    },
    "2024-10-27": {
      "1. open": "2525.24000000",
      "2. high": "2544.33000000",
      "3. low": "2205.79000000",
      "4. close": "2319.20000000",
      "5. volume": "16856.62731590"
    },
    "2024-10-20": {
      "1. open": "2258.88000000",
      "2. high": "2535.00000000",
      "3. low": "2236.62000000",
      "4. close": "2524.32000000",
      "5. volume": "17876.60600787"
    },
    "2024-10-13": {
      "1. open": "2223.27000000",
      "2. high": "2296.64000000",
      "3. low": "2133.00000000",
      "4. close": "2258.81000000",
      "5. volume": "19058.29908231"
    },
    "2024-10-06": {
      "1. open": "2379.75000000",
      "2. high": "2387.75000000",
      "3. low": "2096.92000000",
      "4. close": "2223.88000000",
      "5. volume": "25750.46005343"
    },
    "2024-09-29": {
      "1. open": "2313.12000000",
      "2. high": "2447.11000000",
      "3. low": "2277.50000000",
      "4. close": "2380.45000000",
      "5. volume": "21648.97035230"
    },
    "2024-09-22": {
      "1. open": "2089.07000000",
      "2. high": "2358.37000000",
      "3. low": "2032.31000000",
      "4. close": "2312.71000000",
      "5. volume": "19909.38317723"
    },
    "2024-09-15": {
      "1. open": "2073.84000000",
      "2. high": "2226.00000000",
      "3. low": "2059.25000000",
      "4. close": "2089.48000000",
      "5. volume": "17736.06546062"
    },
    "2024-09-08": {
      "1. open": "2196.38000000",
      "2. high": "2317.16000000",
      "3. low": "1941.70000000",
      "4. close": "2073.56000000",
      "5. volume": "25619.92768819"
    },
    "2024-09-01": {
      "1. open": "2454.13000000",
      "2. high": "2466.15000000",
      "3. low": "2143.88000000",
      "4. close": "2198.68000000",
      "5. volume": "17929.54490500"
    },
    "2024-08-25": {
      "1. open": "2370.70000000",
      "2. high": "2519.53000000",
      "3. low": "2282.50000000",
      "4. close": "2454.54000000",
      "5. volume": "17860.70373998"
    },
    "2024-08-18": {
      "1. open": "2342.05000000",
      "2. high": "2524.00000000",
      "3. low": "2296.05000000",
      "4. close": "2370.29000000",
      "5. volume": "22004.43441703"
    },
    "2024-08-11": {
      "1. open": "2464.78000000",
      "2. high": "2496.51000000",
      "3. low": "1941.08000000",
      "4. close": "2341.79000000",
      "5. volume": "58291.03423757"
    },
    "2024-08-04": {
      "1. open": "3012.93000000",
      "2. high": "3133.16000000",
      "3. low": "2416.00000000",
      "4. close": "2464.46000000",
      "5. volume": "27610.29385289"
    },
    "2024-07-28": {
      "1. open": "3242.55000000",
      "2. high": "3268.69000000",
      "3. low": "2847.47000000",
      "4. close": "3012.12000000",
      "5. volume": "24917.80756566"
    },
    "2024-07-21": {
      "1. open": "2981.52000000",
      "2. high": "3256.13000000",
      "3. low": "2971.41000000",
      "4. close": "3243.51000000",
      "5. volume": "17312.39731369"
    },
    "2024-07-14": {
      "1. open": "2705.94000000",
      "2. high": "3004.80000000",
      "3. low": "2608.00000000",
      "4. close": "2982.06000000",
      "5. volume": "23533.68332189"
    },
    "2024-07-07": {
      "1. open": "3199.02000000",
      "2. high": "3275.00000000",
      "3. low": "2597.21000000",
      "4. close": "2707.17000000",
      "5. volume": "24817.40909422"
    },
    "2024-06-30": {
      "1. open": "3198.48000000",
      "2. high": "3260.00000000",
      "3. low": "3014.81000000",
      "4. close": "3198.52000000",
      "5. volume": "18882.05470915"
    },
    "2024-06-23": {
      "1. open": "3385.45000000",
      "2. high": "3397.49000000",
      "3. low": "3126.55000000",
      "4. close": "3198.70000000",
      "5. volume": "18272.96603046"
    },
    "2024-06-16": {
      "1. open": "3440.33000000",
      "2. high": "3455.33000000",
      "3. low": "3145.43000000",
      "4. close": "3385.25000000",
      "5. volume": "23350.32012412"
    },
    "2024-06-09": {
      "1. open": "3482.64000000",
      "2. high": "3572.30000000",
      "3. low": "3315.32000000",
      "4. close": "3440.31000000",
      "5. volume": "19138.04014213"
    },
    "2024-06-02": {
      "1. open": "3526.77000000",
      "2. high": "3658.41000000",
      "3. low": "3424.17000000",
      "4. close": "3484.69000000",
      "5. volume": "20890.42698352"
    },
    "2024-05-26": {
      "1. open": "2823.87000000",
      "2. high": "3636.98000000",
      "3. low": "2802.80000000",
      "4. close": "3526.15000000",
      "5. volume": "41926.94799782"
    },
    "2024-05-19": {
      "1. open": "2721.16000000",
      "2. high": "2896.11000000",
      "3. low": "2644.76000000",
      "4. close": "2823.47000000",
      "5. volume": "24141.81977669"
    },
    "2024-05-12": {
      "1. open": "2915.58000000",
      "2. high": "2990.50000000",
      "3. low": "2673.14000000",
      "4. close": "2719.32000000",
      "5. volume": "19954.11023420"
    },
    "2024-05-05": {
      "1. open": "3047.27000000",
      "2. high": "3068.73000000",
      "3. low": "2636.70000000",
      "4. close": "2915.95000000",
      "5. volume": "32549.15746624"
    },
    "2024-04-28": {
      "1. open": "2955.71000000",
      "2. high": "3140.31000000",
      "3. low": "2865.00000000",
      "4. close": "3047.19000000",
      "5. volume": "22462.60494444"
    }
  }
}
        date      open      high       low     close       volume  \
0 2025-04-03  76102.60  81300.00  75042.00  76365.98  1511.758573
1 2025-03-30  79441.34  82091.43  75432.48  76135.85  2003.058228
2 2025-03-23  75935.10  80150.77  74226.31  79452.90  2004.679257
3 2025-03-16  74334.78  78476.10  70570.00  75928.62  3317.850597
4 2025-03-09  90634.87  90798.09  73680.00  74310.03  4567.157247

  currency_name
0        Solana
1        Solana
2        Solana
3        Solana
4        Solana

In [20]:
Solana

,date,open,high,low,close,volume,currency_name
0,2025-04-03,76102.60,81300.00,75042.00,76365.98,1511.758573,Solana
1,2025-03-30,79441.34,82091.43,75432.48,76135.85,2003.058228,Solana
2,2025-03-23,75935.10,80150.77,74226.31,79452.90,2004.679257,Solana
3,2025-03-16,74334.78,78476.10,70570.00,75928.62,3317.850597,Solana
4,2025-03-09,90634.87,90798.09,73680.00,74310.03,4567.157247,Solana
5,2025-03-02,91900.51,92078.26,75141.16,90642.23,5817.439540,Solana
6,2025-02-23,91620.25,94977.61,89368.01,91874.60,1663.379136,Solana
7,2025-02-16,93636.05,95586.34,91150.00,91634.19,1897.108324,Solana
8,2025-02-09,95431.64,99421.84,89248.90,93607.15,3166.384578,Solana
9,2025-02-02,98050.00,102000.00,93414.78,95427.29,2910.038615,Solana
10,2025-01-26,98539.45,105951.19,96436.00,98088.57,3658.556952,Solana
11,2025-01-19,92284.22,103599.98,87437.71,98574.14,3343.997587,Solana
12,2025-01-12,95456.12,98960.78,88606.32,92337.55,2445.366454,Solana
13,2025-01-05,89692.71,96143.44,87834.22,95451.75,2005.555398,Solana
14,2024-12-29,91182.16,96129.98,88832.59,89702.09,2344.018261,Solana
15,2024-12-22,99120.98,103000.00,88421.18,91204.69,4072.704773,Solana
16,2024-12-15,95662.16,99800.00,89217.53,99111.37,2699.639924,Solana
17,2024-12-08,92096.25,98456.03,86600.00,95685.97,3394.001764,Solana
18,2024-12-01,93388.13,94400.00,86543.90,92099.58,3804.209786,Solana
19,2024-11-24,85046.28,95501.25,84594.12,93391.61,5630.824666,Solana
20,2024-11-17,74780.73,88000.00,74639.10,85016.99,6663.358494,Solana
21,2024-11-10,63408.26,75699.99,61410.68,74757.19,3545.725778,Solana
22,2024-11-03,62928.68,68000.00,62351.09,63426.11,2261.177721,Solana
23,2024-10-27,63445.78,63900.00,60465.00,62928.34,1786.109662,Solana
24,2024-10-20,57516.93,63779.18,57148.57,63433.63,2063.919625,Solana
25,2024-10-13,57256.48,58723.00,53904.09,57519.27,1245.490320,Solana
26,2024-10-06,58752.02,58757.86,54237.15,57248.79,1637.161104,Solana
27,2024-09-29,56988.75,59528.74,56080.15,58742.25,1390.314409,Solana
28,2024-09-22,53320.98,57414.44,51650.17,57001.09,1655.130712,Solana
29,2024-09-15,49526.79,54781.85,49315.32,53343.95,1707.000856,Solana
30,2024-09-08,51911.95,54065.45,47428.66,49505.02,2198.290552,Solana
31,2024-09-01,57406.50,57632.29,51802.75,51931.36,1877.162877,Solana
32,2024-08-25,53049.34,58113.94,52408.27,57402.19,2010.869248,Solana
33,2024-08-18,53822.14,56141.89,51195.03,53046.89,1836.960865,Solana
34,2024-08-11,53330.01,57499.00,45021.36,53835.66,5859.416666,Solana
35,2024-08-04,62866.50,64749.00,52521.27,53309.69,3522.976055,Solana
36,2024-07-28,62526.97,63876.72,58512.00,62854.02,1840.762229,Solana
37,2024-07-21,55876.94,62721.17,55750.00,62529.01,2216.336373,Solana
38,2024-07-14,51589.15,56400.63,50144.21,55876.86,5468.184149,Solana
39,2024-07-07,58416.69,59467.74,49437.20,51589.15,3660.076765,Solana
40,2024-06-30,59127.81,59261.30,54419.19,58407.41,2451.792702,Solana
41,2024-06-23,62279.16,62696.68,59085.16,59107.12,1526.556657,Solana
42,2024-06-16,64664.14,65298.24,60801.06,62262.17,1826.636652,Solana
43,2024-06-09,62428.48,66132.47,62283.90,64648.18,1890.770514,Solana
44,2024-06-02,63145.80,64989.91,61440.00,62452.47,1558.529962,Solana
45,2024-05-26,60930.51,65933.02,60750.00,63138.93,2469.255271,Solana
46,2024-05-19,57085.97,62261.43,56418.03,60927.75,2144.931916,Solana
47,2024-05-12,59515.05,60834.00,55876.05,57075.98,2126.963162,Solana
48,2024-05-05,58965.50,60365.57,52943.49,59506.98,4178.038841,Solana
49,2024-04-28,60985.08,63134.63,58411.49,58947.56,2398.396625,Solana

# Merge Both DataSet

In [32]:
# import pandas as pd

# def load_and_merge_crypto_data():
#     # Load datasets with consistent column naming
#     bitcoin = pd.read_csv('Bitcoin_Weekly_Prices.csv').rename(columns=str.lower)
#     ethereum = pd.read_csv('Ethereum_Weekly_Prices.csv').rename(columns=str.lower)
#     solana = pd.read_csv('Solana_Weekly_Data.csv').rename(columns=str.lower)

#     # Add currency identifier (uncommented and corrected)
#     bitcoin['currency'] = 'Bitcoin'
#     ethereum['currency'] = 'Ethereum'
#     solana['currency'] = 'Solana'

#     # Standardize date column names if different
#     for df in [bitcoin, ethereum, solana]:
#         if 'date' not in df.columns:
#             # Handle alternative date column names
#             date_col = [col for col in df.columns if 'date' in col.lower()]
#             if date_col:
#                 df.rename(columns={date_col[0]: 'date'}, inplace=True)

#     # Verify all required columns exist
#     required_columns = ['date', 'currency']
#     for df in [bitcoin, ethereum, solana]:
#         if not all(col in df.columns for col in required_columns):
#             missing = [col for col in required_columns if col not in df.columns]
#             raise ValueError(f"Missing columns {missing} in one of the datasets")

#     # Combine vertically
#     crypto = pd.concat([bitcoin, ethereum, solana], ignore_index=True)

#     # Convert date to datetime and handle potential errors
#     crypto['date'] = pd.to_datetime(crypto['date'], errors='coerce')
    
#     # Drop rows with invalid dates if any
#     crypto = crypto.dropna(subset=['date'])
    
#     # Sort by date and currency
#     crypto = crypto.sort_values(['date', 'currency'])

#     # Reset index
#     crypto = crypto.reset_index(drop=True)

#     # Save to CSV
#     crypto.to_csv('Combined_Crypto_Data.csv', index=False)

#     return crypto

# # Execute the function
# combined_data = load_and_merge_crypto_data()

# # Display verification info
# print("="*50)
# print("Successfully merged cryptocurrency data")
# print("="*50)
# print(f"Total records: {len(combined_data)}")
# print("\nCurrency distribution:")
# print(combined_data['currency'].value_counts())

# print("\nSample data from each currency:")
# for currency in ['Bitcoin', 'Ethereum', 'Solana']:
#     print(f"\n{currency}:")
#     print(combined_data[combined_data['currency'] == currency].head(2))

# Another Way to get my currency API

In [42]:
load_dotenv()
API_KEY = os.getenv("API_KEY")

def fetch_crypto_data(symbol, market="EUR"):
    url = f"https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_DAILY&symbol={symbol}&market={market}&apikey={api_key}"
    
    response = requests.get(url)
    if not response.ok:
        print(f"⚠️ Error: {response.status_code}")
        return None

    data = response.json()

    if "Time Series (Digital Currency Daily)" not in data:
        print("⚠️ Unexpected response structure:")
        print(json.dumps(data, indent=2))
        return None

    time_series = data["Time Series (Digital Currency Daily)"]

    # Transform to list of dicts
    records = []
    for date, values in time_series.items():
        record = {
            "date": date,
            "currency": symbol,
            "open": float(values["1. open"]),
            "high": float(values["2. high"]),
            "low": float(values["3. low"]),
            "close": float(values["4. close"]),
            "volume": float(values["5. volume"])
        }
        records.append(record)

    df = pd.DataFrame(records)
    df["date"] = pd.to_datetime(df["date"])
    return df

In [43]:
crypto_currency = ["BTC", "ETH", "SOL"]

all_data = []

for symbol in crypto_currency:
    print(f"Fetching {symbol}...")
    df = fetch_crypto_data(symbol)
    if df is not None:
        all_data.append(df)

# Concatenate all into one DataFrame
combined_df = pd.concat(all_data, ignore_index=True)
combined_df.to_csv("Crypto_Currency.csv", index=False)
combined_df.head(30)

Fetching BTC...
Fetching ETH...
Fetching SOL...

         date currency      open      high       low     close      volume
0  2025-04-03      BTC  75661.51  76569.68  75371.55  76365.98   22.993658
1  2025-04-02      BTC  78900.68  81300.00  75600.00  75617.59  685.408274
2  2025-04-01      BTC  76229.03  79232.59  76149.07  78902.29  416.949969
3  2025-03-31      BTC  76102.60  77674.07  75042.00  76253.99  386.406672
4  2025-03-30      BTC  76346.00  77221.12  75432.48  76135.85  204.162965
5  2025-03-29      BTC  77978.31  78160.35  75435.91  76375.24  213.260117
6  2025-03-28      BTC  80780.15  81029.40  77212.08  77969.88  466.629894
7  2025-03-27      BTC  80969.75  80989.34  80654.59  80751.73    9.353113
8  2025-03-26      BTC  81050.89  81878.00  79838.51  80976.04  330.751332
9  2025-03-25      BTC  81014.11  82067.90  79916.95  81040.50  339.455582
10 2025-03-24      BTC  79441.34  82091.43  79010.55  81016.58  439.445225
11 2025-03-23      BTC  77476.79  79500.00  77463.93  79452.90  138.706858
12 2025-03-22      BTC  77674.53  78145.93  77340.05  77503.62   69.495530
13 2025-03-21      BTC  77546.74  78290.88  76759.16  77682.19  235.665961
14 2025-03-20      BTC  79652.37  80150.77  77070.74  77571.21  388.584815
15 2025-03-19      BTC  75614.31  79785.51  75474.82  79613.78  407.056354
16 2025-03-18      BTC  76927.51  76938.66  74226.31  75598.98  380.422586
17 2025-03-17      BTC  75935.10  77618.51  75622.90  76931.20  384.747152
18 2025-03-16      BTC  77651.89  78243.70  75363.27  75928.62  252.779928
19 2025-03-15      BTC  77285.51  77866.79  76926.51  77618.38  110.871866
20 2025-03-14      BTC  74720.21  78476.10  74430.74  77250.67  456.338400
21 2025-03-13      BTC  76882.52  77436.99  73589.00  74705.46  405.227530
22 2025-03-12      BTC  76023.03  77449.19  73900.21  76888.29  524.635607
23 2025-03-11      BTC  72520.77  76537.38  70570.00  76054.25  711.783757
24 2025-03-10      BTC  74334.78  77532.58  71385.62  72520.77  856.213510
25 2025-03-09      BTC  79614.63  79905.95  73680.00  74310.03  534.870942
26 2025-03-08      BTC  80102.84  80217.81  78698.00  79646.91  180.374119
27 2025-03-07      BTC  83462.69  84569.77  78484.25  80111.44  910.160191
28 2025-03-06      BTC  83996.36  85900.00  81416.90  83390.93  561.139902
29 2025-03-05      BTC  82137.63  84998.52  81348.44  83984.46  528.640882

In [45]:
combined_df.tail(50)

           date currency    open    high     low   close     volume
1000 2024-06-07      SOL  156.18  158.61  141.72  150.60  60102.353
1001 2024-06-06      SOL  159.49  160.06  153.92  156.16  32636.596
1002 2024-06-05      SOL  157.83  161.68  157.22  159.45  35552.420
1003 2024-06-04      SOL  151.16  157.89  150.68  157.80  42206.405
1004 2024-06-03      SOL  150.24  154.03  148.96  151.20  25673.570
1005 2024-06-02      SOL  153.10  153.98  148.67  150.33  30265.086
1006 2024-06-01      SOL  152.57  154.77  152.51  153.11  12482.903
1007 2024-05-31      SOL  153.99  157.28  150.97  152.55  37524.172
1008 2024-05-30      SOL  155.64  159.09  151.36  154.09  47954.487
1009 2024-05-29      SOL  155.50  160.07  153.96  155.66  39767.257
1010 2024-05-28      SOL  156.39  159.09  151.57  155.31  45275.178
1011 2024-05-27      SOL  150.62  158.50  150.58  156.53  31548.510
1012 2024-05-26      SOL  155.29  155.29  148.38  150.61  32010.049
1013 2024-05-25      SOL  154.58  157.39  153.14  155.33  14862.618
1014 2024-05-24      SOL  162.86  162.87  150.08  154.70  42187.834
1015 2024-05-23      SOL  163.33  167.35  153.00  162.82  47319.311
1016 2024-05-22      SOL  163.58  169.08  160.98  163.38  36633.777
1017 2024-05-21      SOL  171.21  173.00  160.09  163.56  48979.591
1018 2024-05-20      SOL  156.47  173.24  154.18  171.32  51852.636
1019 2024-05-19      SOL  158.78  161.40  152.82  156.28  25654.848
1020 2024-05-18      SOL  155.92  162.00  155.30  158.64  33923.734
1021 2024-05-17      SOL  146.77  158.25  146.66  155.93  50143.616
1022 2024-05-16      SOL  145.59  151.35  142.40  146.58  46650.578
1023 2024-05-15      SOL  131.46  145.75  130.50  145.60  45065.341
1024 2024-05-14      SOL  136.66  138.02  131.11  131.29  36902.489
1025 2024-05-13      SOL  133.25  139.55  127.98  136.70  42149.096
1026 2024-05-12      SOL  134.93  137.18  132.50  133.14  13656.698
1027 2024-05-11      SOL  135.70  137.19  133.09  135.04  16603.975
1028 2024-05-10      SOL  141.67  144.42  134.40  135.82  43852.341
1029 2024-05-09      SOL  132.12  142.21  131.00  141.56  42937.737
1030 2024-05-08      SOL  137.82  139.46  130.25  132.29  49470.810
1031 2024-05-07      SOL  141.94  147.89  137.55  137.90  52173.147
1032 2024-05-06      SOL  135.51  145.63  135.12  141.98  66882.401
1033 2024-05-05      SOL  135.90  137.52  133.18  135.49  21425.675
1034 2024-05-04      SOL  133.75  138.65  132.40  135.80  32106.876
1035 2024-05-03      SOL  128.46  134.83  126.64  133.69  47210.795
1036 2024-05-02      SOL  125.47  131.30  119.57  128.26  64293.624
1037 2024-05-01      SOL  118.72  126.65  111.27  125.69  86829.772
1038 2024-04-30      SOL  128.59  130.35  113.47  118.81  67339.472
1039 2024-04-29      SOL  128.69  129.69  124.38  128.44  46002.538
1040 2024-04-28      SOL  132.19  135.17  128.03  128.87  36549.357
1041 2024-04-27      SOL  130.21  133.77  124.47  132.25  38089.991
1042 2024-04-26      SOL  135.08  136.47  129.84  130.20  39695.980
1043 2024-04-25      SOL  137.74  139.72  132.90  135.09  47208.172
1044 2024-04-24      SOL  144.95  149.32  136.03  138.15  61125.267
1045 2024-04-23      SOL  147.41  149.56  143.43  144.63  49550.062
1046 2024-04-22      SOL  139.77  148.68  137.60  147.39  44878.352
1047 2024-04-21      SOL  142.07  144.22  137.88  139.60  24062.318
1048 2024-04-20      SOL  133.76  143.28  131.34  142.12  37243.208
1049 2024-04-19      SOL  133.59  138.51  121.18  133.93  71908.616

# Web Scraping

## Beatiful Soup

In [24]:
import requests

url = 'import requests'

url = 'https://u.today/search/node?keys=Bitcoin'
response_f = requests.get(url)
response_f

In [25]:
import requests
import bs4

response = requests.get("https://u.today/search/node?keys=Bitcoin")
# soup = bs4.BeautifulSoup(response.text, 'lxml') # with lxml package
document = bs4.BeautifulSoup(response.text, 'html.parser') 
document

 <!DOCTYPE html>

<html class="theme-light" dir="ltr" lang="en" prefix="og: ogp.me/ns#">
<head>
<script async="" crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9245916885225528"></script>
<link href="https://www.google-analytics.com" rel="preconnect"/>
<meta content="width=device-width, initial-scale=1.0, maximum-scale=5" name="viewport"/>
<script src="/core/assets/vendor/jquery/jquery.min.js"></script>
<meta charset="utf-8">
<link href="https://u.today/search/node" rel="canonical">
<meta content="article" property="og:type"/>
<meta content="https://u.today/search/node" property="og:url"/>
<meta content="Search" property="og:title"/>
<meta content="Search" property="og:description"/>
<meta content="https://u.today/img/logo-utoday.png" property="og:image"/>
<meta content="https://u.today/img/logo-utoday.png" property="og:image:url"/>
<meta content="https://u.today/img/logo-utoday.png" property="og:image:secure_url"/>
<meta content="2560796210663191" property="fb:app_id"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@Utoday_en" name="twitter:site"/>
<meta content="https://u.today/img/logo-utoday.png" name="twitter:image"/>
<meta content="Drupal 10 (https://www.drupal.org)" name="Generator"/>
<meta content="width" name="MobileOptimized"/>
<meta content="true" name="HandheldFriendly"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<script type="application/ld+json">{
    "@context": "https://schema.org",
    "@graph": [
        {
            "@type": "Organization",
            "name": "U.Today",
            "url": "https://u.today/search/node",
            "image": {
                "@type": "ImageObject",
                "url": "https://U.today/img/logo-utoday.png"
            }
        }
    ]
}</script>
<!-- end: separate google analytics code -->
<!-- Google Tag Manager -->
<!-- End Google Tag Manager -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-2PE2QV2V0X"></script>
<script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-2PE2QV2V0X');
    </script>
<link color="#263238" href="/img/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
<link href="/img/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/img/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/img/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/img/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/img/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/img/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/img/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/img/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/img/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/img/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/img/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/site.webmanifest" rel="manifest"/>
<link color="#263238" href="/img/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
<link href="/img/favicon/favicon.ico" rel="shortcut icon"/>
<meta content="#263238" name="msapplication-TileColor"/>
<meta content="/img/favicon/browserconfig.xml" name="msapplication-config"/>
<meta content="#263238" name="theme-color"/>
<meta content="2E6EDC1D9A57E69FC6232E905A08CBFA" name="msvalidate.01">
<link href="/manifest.json" rel="manifest">
<meta content="266789420636465" property="fb:pages">
<link href="/modules/contrib/paragraphs/css/paragraphs.unpublished.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/libs/air-datepicker/air-datepicker.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/slick-theme.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/common.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/app.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/push.css?su3fvf" media="all" rel="stylesheet">
<style>.ccc-widget.ccc-list .header-div a img {
                            width: 26px;
                            height: 26px;
                        }
                    </style>
<title>Search | U.Today</title>
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js"></script>
<script>
                        function copyToClipboard(e) {
                            let input = document.body.appendChild(document.createElement("input"));
                            input.value = window.location.href;
                            input.select();
                            document.execCommand('copy');
                            input.parentNode.removeChild(input);

                            let tooltip = document.createElement('div');
                            tooltip.className = 'copy-tooltip';
                            tooltip.innerHTML = 'Copied!';

                            if (!e.querySelector('.copy-tooltip')) {
                                e.append(tooltip);

                                setTimeout(() => {
                                    e.querySelector('.copy-tooltip').remove();
                                }, 2000);
                            }
                        }
                    </script>
<style>
                        @media (max-width: 849px) {
                            body #onesignal-slidedown-container.slide-up {
                                bottom: 60px
                            }
                        }
                    </style>
<script async="" defer="" src="https://www.google.com/recaptcha/api.js"></script>
<style>
                        .captcha-container {
                            display: none; /* CAPTCHA скрыта по умолчанию */
                        }
                    </style>
<script data-cfasync="false" src="https://cmp.gatekeeperconsent.com/min.js"></script>
<script data-cfasync="false" src="https://the.gatekeeperconsent.com/cmp.min.js"></script>
<script async="" src="//www.ezojs.com/ezoic/sa.min.js"></script>
<script>
                        window.ezstandalone = window.ezstandalone || {};
                        ezstandalone.cmd = ezstandalone.cmd || [];
                    </script>
</link></link></link></link></link></link></meta></link></meta></link></meta></head>
<body class="not_logged_in">
<!-- Google Tag Manager (noscript) -->
<!-- End Google Tag Manager (noscript) -->
<div class="something--upper">
<div class="something">
<div class="something__title">Advertisement</div>
<div class="something__nav">
<div class="something__label">AD</div>
<button aria-label="Close ad" class="btn btn--light something__close"></button>
</div>
<div class="something__content">
<div class="something__content--long">
<div>
<!-- Wideheader Fixed Desktop 1150x60 [async] -->
<script type="text/javascript">

if (!window.AdButler){(function(){var s = document.createElement("script"); s.async = true; s.type = "text/javascript"; s.src = 'https://servedbyadbutler.com/app.js'; var n = document.getElementsByTagName("script")[0]; n.parentNode.insertBefore(s, n);}());}

</script>
<script type="text/javascript">
var AdButler = AdButler || {};
AdButler.ads = AdButler.ads || [];
var abkw = window.abkw || '';
var plc602403 = window.plc602403 || 0;
document.write('<'+'div id="placement_602403_'+plc602403+'"></'+'div>');
AdButler.ads.push({handler: function(opt){ AdButler.register(183269, 602403, [1150,60], 'placement_602403_'+opt.place, opt); }, opt: { place: plc602403++, keywords: abkw, domain: 'servedbyadbutler.com', click: 'CLICK_MACRO_PLACEHOLDER' }});

</script>
</div>
</div>
<div class="something__content--square">
<div>
<!-- Wideheader Fixed Mobile 336x60 [async] -->
<script type="text/javascript">
if (document.documentElement.clientWidth < 768) {
if (!window.AdButler){(function(){var s = document.createElement("script"); s.async = true; s.type = "text/javascript"; s.src = 'https://servedbyadbutler.com/app.js'; var n = document.getElementsByTagName("script")[0]; n.parentNode.insertBefore(s, n);}());}
}
</script>
<script type="text/javascript">
if (document.documentElement.clientWidth < 768) {
var AdButler = AdButler || {};
AdButler.ads = AdButler.ads || [];
var abkw = window.abkw || '';
var plc551690 = window.plc551690 || 0;
document.write('<'+'div id="placement_551690_'+plc551690+'"></'+'div>');
AdButler.ads.push({handler: function(opt){ AdButler.register(183269, 551690, [336,60], 'placement_551690_'+opt.place, opt); }, opt: { place: plc551690++, keywords: abkw, domain: 'servedbyadbutler.com', click: 'CLICK_MACRO_PLACEHOLDER' }});
}
</script>
</div>
</div>
</div>
</div>
</div>
<header class="header">
<div class="header__container"><a class="header__logo" href="https://u.today/" title="U.Today logo"></a>
<div class="header__search" style="display: block">
<form action="/search/node" class="header__search-form" method="get">
<button class="header__search-submit btn btn--light btn--search" style="display: none;" type="submit"></button>
<input class="header__search-input" id="search_text" name="keys" type="text"/>
<button class="header__search-close btn btn--light btn--cross"></button>
</form>
</div>
</div>
</header>
<div class="mobile-menu-cover"></div>
<div class="page-container container">
<div class="something--leaderboard">
<div class="something">
<div class="something__title">Advertisement</div>
<div class="something__nav">
<div class="something__label">AD</div>
<button aria-label="Close ad" class="btn btn--light something__close"></button>
</div>
<div class="something__content">
<div class="something__content--long">
<div>
<!-- Leaderboard Desktop 1150x90 [async] -->
<script type="text/javascript">
if (window.innerWidth > 768) {
if (!window.AdButler){(function(){var s = document.createElement("script"); s.async = true; s.type = "text/javascript"; s.src = 'https://servedbyadbutler.com/app.js'; var n = document.getElementsByTagName("script")[0]; n.parentNode.insertBefore(s, n);}());}
}
</script>
<script type="text/javascript">
if (window.innerWidth > 768) {
var AdButler = AdButler || {};
AdButler.ads = AdButler.ads || [];
var abkw = window.abkw || '';
var plc828210 = window.plc828210 || 0;
document.write('<'+'div id="placement_828210_'+plc828210+'"></'+'div>');
AdButler.ads.push({handler: function(opt){ AdButler.register(183269, 828210, [1150,90], 'placement_828210_'+opt.place, opt); }, opt: { place: plc828210++, keywords: abkw, domain: 'servedbyadbutler.com', click: 'CLICK_MACRO_PLACEHOLDER' }});
}
</script>
</div>
</div>
<div class="something__content--square">
</div>
</div>
</div>
</div>
<div class="main-aside-container">
<main class="main-block">
<div class="search-result">
<h1 class="page-bg-title">Search results for “Bitcoin”</h1>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 2, 2025 - 13:03</div>
</div>
<a class="news__item-body" href="https://u.today/bitcoin-btc-controlled-by-bears-but-theres-a-silver-lining">
<div class="news__item-title">Bitcoin (BTC) Controlled by Bears, But There's a Silver Lining</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/vladislav-sopov"><img alt="Vladislav Sopov" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-07/8893.jpg" width="24"/>Vladislav Sopov
            </a></div>
</div>
<div class="something something--content">
<div class="something__content-long">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="1698558466" style="display:inline-block;width:728px;height:90px"></ins>
</div>
<div class="something__content-square">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="4003311693" style="display:inline-block;width:336px;height:280px"></ins>
</div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 2, 2025 - 12:15</div>
</div>
<a class="news__item-body" href="https://u.today/bitcoin-btc-price-sees-very-rare-golden-and-death-cross-duel">
<div class="news__item-title">Bitcoin (BTC) Price Sees Very Rare Golden and Death Cross Duel</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 2, 2025 - 12:12</div>
</div>
<a class="news__item-body" href="https://u.today/bitcoin-mike-mcglones-bearish-10000-outlook-sees-radical-u-turn">
<div class="news__item-title">Bitcoin: Mike McGlone's Bearish $10,000 Outlook Sees Radical U-Turn</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/yuri-molchan"><img alt="Yuri Molchan" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/yuri-ava.jpg" width="24"/>Yuri Molchan
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 2, 2025 - 10:49</div>
</div>
<a class="news__item-body" href="https://u.today/xrp-doge-and-bitcoin-wiped-out-in-287-million-liquidation-tsunami">
<div class="news__item-title">XRP, DOGE and Bitcoin Wiped out in $287 Million Liquidation Tsunami</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 1, 2025 - 22:00</div>
</div>
<a class="news__item-body" href="https://u.today/peter-schiff-to-grow-bitcoin-reserve-on-public-donations">
<div class="news__item-title">Peter Schiff to Grow Bitcoin Reserve on Public Donations</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/caroline-amosun"><img alt="Caroline Amosun" class="humble__img" height="24" src="https://u.today/sites/default/files/2025-03/56827.jpg" width="24"/>Caroline Amosun
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 1, 2025 - 18:18</div>
</div>
<a class="news__item-body" href="https://u.today/canadian-billionaire-says-bitcoin-and-gold-are-very-different">
<div class="news__item-title"> Canadian Billionaire Says Bitcoin and Gold Are Very Different</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
            </a></div>
</div>
<div class="something something--content">
<div class="something__content-long">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="1698558466" style="display:inline-block;width:728px;height:90px"></ins>
</div>
<div class="something__content-square">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="4003311693" style="display:inline-block;width:336px;height:280px"></ins>
</div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 1, 2025 - 16:07</div>
</div>
<a class="news__item-body" href="https://u.today/bitcoin-bulls-buckle-up-bollinger-bands-hint-at-88000-teleport">
<div class="news__item-title">Bitcoin Bulls, Buckle Up: Bollinger Bands Hint at $88,000 Teleport</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 1, 2025 - 15:56</div>
</div>
<a class="news__item-body" href="https://u.today/fidelity-spotlights-8-year-old-bullish-bitcoin-move-from-japan">
<div class="news__item-title">Fidelity Spotlights 8-Year-Old Bullish Bitcoin Move From Japan</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 1, 2025 - 15:31</div>
</div>
<a class="news__item-body" href="https://u.today/bitcoin-btc-records-major-volume-reversal-xrp-doesnt-really-need-2-did-ethereum-eth-forget-about">
<div class="news__item-title">Bitcoin (BTC) Records Major Volume Reversal, XRP Doesn't Really Need $2, Did Ethereum (ETH) Forget About $2,000?</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 1, 2025 - 14:28</div>
</div>
<a class="news__item-body" href="https://u.today/xrp-on-verge-of-big-bitcoin-move-and-its-up">
<div class="news__item-title">XRP on Verge of Big Bitcoin Move, and It's Up</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 1, 2025 - 13:00</div>
</div>
<a class="news__item-body" href="https://u.today/dont-be-fool-buy-bitcoin-michael-saylor-says">
<div class="news__item-title">'Don't Be Fool. Buy Bitcoin,' Michael Saylor Says</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/yuri-molchan"><img alt="Yuri Molchan" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/yuri-ava.jpg" width="24"/>Yuri Molchan
            </a></div>
</div>
<div class="something something--content">
<div class="something__content-long">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="1698558466" style="display:inline-block;width:728px;height:90px"></ins>
</div>
<div class="something__content-square">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="4003311693" style="display:inline-block;width:336px;height:280px"></ins>
</div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 1, 2025 - 8:31</div>
</div>
<a class="news__item-body" href="https://u.today/tether-buys-8888-bitcoin-in-epic-buy-the-dip-strategy">
<div class="news__item-title">Tether Buys 8,888 Bitcoin in Epic Buy-the-Dip Strategy</div>
</a>

In [26]:
# book_cards = soup.select("ol.row li article.product_pod")

In [27]:
# Option 1: Using CSS selectors (similar to your book_cards example)
Bitcoin_date = document.select("body.not_logged_in div.main-aside-container main.main-block div.search-result div.news__item div.news__item-head div.humble")
Bitcoin_date

[<div class="humble">Apr 2, 2025 - 13:03</div>,
 <div class="humble">Apr 2, 2025 - 12:15</div>,
 <div class="humble">Apr 2, 2025 - 12:12</div>,
 <div class="humble">Apr 2, 2025 - 10:49</div>,
 <div class="humble">Apr 1, 2025 - 22:00</div>,
 <div class="humble">Apr 1, 2025 - 18:18</div>,
 <div class="humble">Apr 1, 2025 - 16:07</div>,
 <div class="humble">Apr 1, 2025 - 15:56</div>,
 <div class="humble">Apr 1, 2025 - 15:31</div>,
 <div class="humble">Apr 1, 2025 - 14:28</div>,
 <div class="humble">Apr 1, 2025 - 13:00</div>,
 <div class="humble">Apr 1, 2025 - 8:31</div>,
 <div class="humble">Apr 1, 2025 - 6:30</div>,
 <div class="humble">Mar 31, 2025 - 23:40</div>,
 <div class="humble">Mar 31, 2025 - 22:27</div>,
 <div class="humble">Mar 31, 2025 - 19:49</div>,
 <div class="humble">Mar 31, 2025 - 16:32</div>,
 <div class="humble">Mar 31, 2025 - 13:26</div>,
 <div class="humble">Mar 31, 2025 - 12:47</div>,
 <div class="humble">Mar 31, 2025 - 12:02</div>,
 <div class="humble">Mar 31, 2025 - 10:27</div>,
 <div class="humble">Mar 31, 2025 - 9:05</div>,
 <div class="humble">Mar 31, 2025 - 7:16</div>,
 <div class="humble">Mar 31, 2025 - 0:01</div>,
 <div class="humble">Mar 30, 2025 - 17:54</div>,
 <div class="humble">Mar 30, 2025 - 13:54</div>,
 <div class="humble">Mar 30, 2025 - 13:36</div>,
 <div class="humble">Mar 30, 2025 - 13:21</div>,
 <div class="humble">Mar 30, 2025 - 13:00</div>,
 <div class="humble">Mar 30, 2025 - 12:30</div>,
 <div class="humble">Mar 30, 2025 - 10:40</div>,
 <div class="humble">Mar 30, 2025 - 8:01</div>,
 <div class="humble">Mar 29, 2025 - 20:00</div>,
 <div class="humble">Mar 29, 2025 - 16:30</div>,
 <div class="humble">Mar 29, 2025 - 13:30</div>,
 <div class="humble">Mar 29, 2025 - 8:19</div>,
 <div class="humble">Mar 28, 2025 - 19:38</div>,
 <div class="humble">Mar 28, 2025 - 15:51</div>,
 <div class="humble">Mar 28, 2025 - 15:07</div>,
 <div class="humble">Mar 28, 2025 - 14:54</div>,
 <div class="humble">Mar 28, 2025 - 14:37</div>,
 <div class="humble">Mar 28, 2025 - 14:36</div>,
 <div class="humble">Mar 28, 2025 - 13:18</div>,
 <div class="humble">Mar 28, 2025 - 12:14</div>,
 <div class="humble">Mar 28, 2025 - 11:32</div>,
 <div class="humble">Mar 28, 2025 - 9:46</div>,
 <div class="humble">Mar 28, 2025 - 0:01</div>,
 <div class="humble">Mar 27, 2025 - 20:46</div>,
 <div class="humble">Mar 27, 2025 - 20:04</div>,
 <div class="humble">Mar 27, 2025 - 18:29</div>]

In [28]:
Bitcoin_dt = []
for Bitcoin in Bitcoin_date:
    
  Bitcoin_dt.append(Bitcoin.get_text())
  #print(Bitcoin.get_text())
Bitcoin_dt

['Apr 2, 2025 - 13:03',
 'Apr 2, 2025 - 12:15',
 'Apr 2, 2025 - 12:12',
 'Apr 2, 2025 - 10:49',
 'Apr 1, 2025 - 22:00',
 'Apr 1, 2025 - 18:18',
 'Apr 1, 2025 - 16:07',
 'Apr 1, 2025 - 15:56',
 'Apr 1, 2025 - 15:31',
 'Apr 1, 2025 - 14:28',
 'Apr 1, 2025 - 13:00',
 'Apr 1, 2025 - 8:31',
 'Apr 1, 2025 - 6:30',
 'Mar 31, 2025 - 23:40',
 'Mar 31, 2025 - 22:27',
 'Mar 31, 2025 - 19:49',
 'Mar 31, 2025 - 16:32',
 'Mar 31, 2025 - 13:26',
 'Mar 31, 2025 - 12:47',
 'Mar 31, 2025 - 12:02',
 'Mar 31, 2025 - 10:27',
 'Mar 31, 2025 - 9:05',
 'Mar 31, 2025 - 7:16',
 'Mar 31, 2025 - 0:01',
 'Mar 30, 2025 - 17:54',
 'Mar 30, 2025 - 13:54',
 'Mar 30, 2025 - 13:36',
 'Mar 30, 2025 - 13:21',
 'Mar 30, 2025 - 13:00',
 'Mar 30, 2025 - 12:30',
 'Mar 30, 2025 - 10:40',
 'Mar 30, 2025 - 8:01',
 'Mar 29, 2025 - 20:00',
 'Mar 29, 2025 - 16:30',
 'Mar 29, 2025 - 13:30',
 'Mar 29, 2025 - 8:19',
 'Mar 28, 2025 - 19:38',
 'Mar 28, 2025 - 15:51',
 'Mar 28, 2025 - 15:07',
 'Mar 28, 2025 - 14:54',
 'Mar 28, 2025 - 14:37',
 'Mar 28, 2025 - 14:36',
 'Mar 28, 2025 - 13:18',
 'Mar 28, 2025 - 12:14',
 'Mar 28, 2025 - 11:32',
 'Mar 28, 2025 - 9:46',
 'Mar 28, 2025 - 0:01',
 'Mar 27, 2025 - 20:46',
 'Mar 27, 2025 - 20:04',
 'Mar 27, 2025 - 18:29']

In [29]:
News_cards = document.select('div.news__item')
News_cards

[<div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 2, 2025 - 13:03</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-controlled-by-bears-but-theres-a-silver-lining">
 <div class="news__item-title">Bitcoin (BTC) Controlled by Bears, But There's a Silver Lining</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/vladislav-sopov"><img alt="Vladislav Sopov" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-07/8893.jpg" width="24"/>Vladislav Sopov
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 2, 2025 - 12:15</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-price-sees-very-rare-golden-and-death-cross-duel">
 <div class="news__item-title">Bitcoin (BTC) Price Sees Very Rare Golden and Death Cross Duel</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 2, 2025 - 12:12</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-mike-mcglones-bearish-10000-outlook-sees-radical-u-turn">
 <div class="news__item-title">Bitcoin: Mike McGlone's Bearish $10,000 Outlook Sees Radical U-Turn</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/yuri-molchan"><img alt="Yuri Molchan" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/yuri-ava.jpg" width="24"/>Yuri Molchan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 2, 2025 - 10:49</div>
 </div>
 <a class="news__item-body" href="https://u.today/xrp-doge-and-bitcoin-wiped-out-in-287-million-liquidation-tsunami">
 <div class="news__item-title">XRP, DOGE and Bitcoin Wiped out in $287 Million Liquidation Tsunami</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 22:00</div>
 </div>
 <a class="news__item-body" href="https://u.today/peter-schiff-to-grow-bitcoin-reserve-on-public-donations">
 <div class="news__item-title">Peter Schiff to Grow Bitcoin Reserve on Public Donations</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/caroline-amosun"><img alt="Caroline Amosun" class="humble__img" height="24" src="https://u.today/sites/default/files/2025-03/56827.jpg" width="24"/>Caroline Amosun
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 18:18</div>
 </div>
 <a class="news__item-body" href="https://u.today/canadian-billionaire-says-bitcoin-and-gold-are-very-different">
 <div class="news__item-title"> Canadian Billionaire Says Bitcoin and Gold Are Very Different</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 16:07</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-bulls-buckle-up-bollinger-bands-hint-at-88000-teleport">
 <div class="news__item-title">Bitcoin Bulls, Buckle Up: Bollinger Bands Hint at $88,000 Teleport</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 15:56</div>
 </div>
 <a class="news__item-body" href="https://u.today/fidelity-spotlights-8-year-old-bullish-bitcoin-move-from-japan">
 <div class="news__item-title">Fidelity Spotlights 8-Year-Old Bullish Bitcoin Move From Japan</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 15:31</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-records-major-volume-reversal-xrp-doesnt-really-need-2-did-ethereum-eth-forget-about">
 <div class="news__item-title">Bitcoin (BTC) Records Major Volume Reversal, XRP Doesn't Really Need $2, Did Ethereum (ETH) Forget About $2,000?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 14:28</div>
 </div>
 <a class="news__item-body" href="https://u.today/xrp-on-verge-of-big-bitcoin-move-and-its-up">
 <div class="news__item-title">XRP on Verge of Big Bitcoin Move, and It's Up</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 13:00</div>
 </div>
 <a class="news__item-body" href="https://u.today/dont-be-fool-buy-bitcoin-michael-saylor-says">
 <div class="news__item-title">'Don't Be Fool. Buy Bitcoin,' Michael Saylor Says</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/yuri-molchan"><img alt="Yuri Molchan" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/yuri-ava.jpg" width="24"/>Yuri Molchan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 8:31</div>
 </div>
 <a class="news__item-body" href="https://u.today/tether-buys-8888-bitcoin-in-epic-buy-the-dip-strategy">
 <div class="news__item-title">Tether Buys 8,888 Bitcoin in Epic Buy-the-Dip Strategy</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 6:30</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-mogul-successfully-launched-into-space">
 <div class="news__item-title">Bitcoin Mogul Successfully Launched into Space</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 23:40</div>
 </div>
 <a class="news__item-body" href="https://u.today/1-billion-usdt-minted-as-bitcoin-whales-prepare-to-buy-dip">
 <div class="news__item-title">$1 Billion USDT Minted as Bitcoin Whales Prepare to Buy Dip </div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/dan-burgin"><img alt="Dan Burgin" class="humble__img" height="24" src="https://u.today/sites/default/files/2024-02/45425.jpg" width="24"/>Dan Burgin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 22:27</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-outperforms-gold-amid-macro-uncertainty-bitwise-cio-stays-optimistic">
 <div class="news__item-title">Bitcoin (BTC) Outperforms Gold Amid Macro Uncertainty, Bitwise CIO Stays Optimistic</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/caroline-amosun"><img alt="Caroline Amosun" class="humble__img" height="24" src="https://u.today/sites/default/files/2025-03/56827.jpg" width="24"/>Caroline Amosun
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 19:49</div>
 </div>
 <a class="news__item-body" href="https://u.today/stunning-chart-highlights-strategys-bitcoin-dominance">
 <div class="news__item-title">Stunning Chart Highlights Strategy's Bitcoin Dominance</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 16:32</div>
 </div>
 <a class="news__item-body" href="https://u.today/xrp-army-lambasts-gemini-ceo-649331848-dogecoin-stun-biggest-crypto-exchange-robert-kiyosaki">
 <div class="news__item-title">XRP Army Lambasts Gemini CEO, 649,331,848 Dogecoin Stun Biggest Crypto Exchange, Robert Kiyosaki Predicts New ATH for Second Best Asset to Bitcoin: Crypto News Digest by U.Today</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/valeria-blokhina"><img alt="Valeria Blokhina" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-10/9844.jpg" width="24"/>Valeria Blokhina
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 13:26</div>
 </div>
 <a class="news__item-body" href="https://u.today/blackrock-ceo-warns-us-dollar-could-lose-to-bitcoin">
 <div class="news__item-title">BlackRock CEO Warns US Dollar Could Lose to Bitcoin</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 12:47</div>
 </div>
 <a class="news__item-body" href="https://u.today/litecoin-ltc-decouples-from-bitcoin-in-key-metric-details">
 <div class="news__item-title">Litecoin (LTC) Decouples From Bitcoin in Key Metric: Details</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 12:02</div>
 </div>
 <a class="news__item-body" href="https://u.today/breaking-strategy-buys-nearly-2-billion-worth-of-bitcoin">
 <div class="news__item-title">Breaking: Strategy Buys Nearly $2 Billion Worth of Bitcoin</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 10:27</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-death-cross-appears-on-rare-indicator-what-happens-next">
 <div class="news__item-title">Bitcoin (BTC) 'Death Cross' Appears on Rare Indicator: What Happens Next?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 9:05</div>
 </div>
 <a class="news__item-body" href="https://u.today/spot-bitcoin-etf-inflows-down-73-in-seven-days-details">
 <div class="news__item-title">Spot Bitcoin ETF Inflows Down 73% in Seven Days: Details</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 7:16</div>
 </div>
 <a class="news__item-body" href="https://u.today/metaplanet-issues-more-debt-to-buy-bitcoin">
 <div class="news__item-title">Metaplanet Issues More Debt to Buy Bitcoin</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/xrp-rapidly-diving-below-2-bitcoin-btc-on-verge-of-losing-80000-shiba-inu-shib-loses-all-breakout">
 <div class="news__item-title">XRP Rapidly Diving Below $2, Bitcoin (BTC) on Verge of Losing $80,000, Shiba Inu (SHIB) Loses All Breakout Gains</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 30, 2025 - 17:54</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-magnate-to-fly-into-space-tomorrow">
 <div class="news__item-title">Bitcoin Magnate to Fly into Space Tomorrow</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 30, 2025 - 13:54</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-price-prediction-for-march-30">
 <div class="news__item-title">Bitcoin (BTC) Price Prediction for March 30</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 30, 2025 - 13:36</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-finds-bottom-key-indicator-hints-at-reversal">
 <div class="news__item-title">Bitcoin (BTC) Finds Bottom? Key Indicator Hints at Reversal</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 30, 2025 - 13:21</div>
 </div>
 <a class="news__item-body" href="https://u.today/michael-saylor-teases-another-bitcoin-mega-buy-with-new-cryptic-post">
 <div class="news__item-title">Michael Saylor Teases Another Bitcoin Mega-Buy With New Cryptic Post</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 30, 2025 - 13:00</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-etfs-skyrocket-by-200-million-but-worrying-catch-emerges">
 <div class="news__item-title">Bitcoin ETFs Skyrocket by $200 Million, but Worrying Catch Emerges</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 30, 2025 - 12:30</div>
 </div>
 <a class="news__item-body" href="https://u.today/mysterious-333000000-bitcoin-transfer-stuns-major-us-exchange">
 <div class="news__item-title">Mysterious $333,000,000 Bitcoin Transfer Stuns Major US Exchange</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 30, 2025 - 10:40</div>
 </div>
 <a class="news__item-body" href="https://u.today/has-20000000th-bitcoin-been-mined">
 <div class="news__item-title">Has 20,000,000th Bitcoin Been Mined?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">

In [30]:
from datetime import datetime

Bitcoin_data = []
for card in News_cards:
    data = []
    date_bt = card.select_one('div.news__item-head div.humble')
    if date_bt != None:
        datestr = date_bt.get_text()
        data.append(datetime.strptime(datestr.split(" - ")[0], "%b %d, %Y").date())
    title_bt = card.select_one('div.news__item-title')
    if title_bt != None:
        data.append(title_bt.get_text())
    if len(data) == 2:
     Bitcoin_data.append(tuple(data))
    
Bitcoin_data

[(datetime.date(2025, 4, 2),
  "Bitcoin (BTC) Controlled by Bears, But There's a Silver Lining"),
 (datetime.date(2025, 4, 2),
  'Bitcoin (BTC) Price Sees Very Rare Golden and Death Cross Duel'),
 (datetime.date(2025, 4, 2),
  "Bitcoin: Mike McGlone's Bearish $10,000 Outlook Sees Radical U-Turn"),
 (datetime.date(2025, 4, 2),
  'XRP, DOGE and Bitcoin Wiped out in $287 Million Liquidation Tsunami'),
 (datetime.date(2025, 4, 1),
  'Peter Schiff to Grow Bitcoin Reserve on Public Donations'),
 (datetime.date(2025, 4, 1),
  ' Canadian Billionaire Says Bitcoin and Gold Are Very Different'),
 (datetime.date(2025, 4, 1),
  'Bitcoin Bulls, Buckle Up: Bollinger Bands Hint at $88,000 Teleport'),
 (datetime.date(2025, 4, 1),
  'Fidelity Spotlights 8-Year-Old Bullish Bitcoin Move From Japan'),
 (datetime.date(2025, 4, 1),
  "Bitcoin (BTC) Records Major Volume Reversal, XRP Doesn't Really Need $2, Did Ethereum (ETH) Forget About $2,000?"),
 (datetime.date(2025, 4, 1), "XRP on Verge of Big Bitcoin Move, and It's Up"),
 (datetime.date(2025, 4, 1),
  "'Don't Be Fool. Buy Bitcoin,' Michael Saylor Says"),
 (datetime.date(2025, 4, 1),
  'Tether Buys 8,888 Bitcoin in Epic Buy-the-Dip Strategy'),
 (datetime.date(2025, 4, 1), 'Bitcoin Mogul Successfully Launched into Space'),
 (datetime.date(2025, 3, 31),
  '$1 Billion USDT Minted as Bitcoin Whales Prepare to Buy Dip '),
 (datetime.date(2025, 3, 31),
  'Bitcoin (BTC) Outperforms Gold Amid Macro Uncertainty, Bitwise CIO Stays Optimistic'),
 (datetime.date(2025, 3, 31),
  "Stunning Chart Highlights Strategy's Bitcoin Dominance"),
 (datetime.date(2025, 3, 31),
  'XRP Army Lambasts Gemini CEO, 649,331,848 Dogecoin Stun Biggest Crypto Exchange, Robert Kiyosaki Predicts New ATH for Second Best Asset to Bitcoin: Crypto News Digest by U.Today'),
 (datetime.date(2025, 3, 31),
  'BlackRock CEO Warns US Dollar Could Lose to Bitcoin'),
 (datetime.date(2025, 3, 31),
  'Litecoin (LTC) Decouples From Bitcoin in Key Metric: Details'),
 (datetime.date(2025, 3, 31),
  'Breaking: Strategy Buys Nearly $2 Billion Worth of Bitcoin'),
 (datetime.date(2025, 3, 31),
  "Bitcoin (BTC) 'Death Cross' Appears on Rare Indicator: What Happens Next?"),
 (datetime.date(2025, 3, 31),
  'Spot Bitcoin ETF Inflows Down 73% in Seven Days: Details'),
 (datetime.date(2025, 3, 31), 'Metaplanet Issues More Debt to Buy Bitcoin'),
 (datetime.date(2025, 3, 31),
  'XRP Rapidly Diving Below $2, Bitcoin (BTC) on Verge of Losing $80,000, Shiba Inu (SHIB) Loses All Breakout Gains'),
 (datetime.date(2025, 3, 30), 'Bitcoin Magnate to Fly into Space Tomorrow'),
 (datetime.date(2025, 3, 30), 'Bitcoin (BTC) Price Prediction for March 30'),
 (datetime.date(2025, 3, 30),
  'Bitcoin (BTC) Finds Bottom? Key Indicator Hints at Reversal'),
 (datetime.date(2025, 3, 30),
  'Michael Saylor Teases Another Bitcoin Mega-Buy With New Cryptic Post'),
 (datetime.date(2025, 3, 30),
  'Bitcoin ETFs Skyrocket by $200 Million, but Worrying Catch Emerges'),
 (datetime.date(2025, 3, 30),
  'Mysterious $333,000,000 Bitcoin Transfer Stuns Major US Exchange'),
 (datetime.date(2025, 3, 30), 'Has 20,000,000th Bitcoin Been Mined?'),
 (datetime.date(2025, 3, 30),
  'Legendary Trader Brandt Warns This Bitcoin Pattern Could Be a Trap'),
 (datetime.date(2025, 3, 29),
  '15 Years Since Huge Bitcoin Bug Satoshi Had to Fix ASAP'),
 (datetime.date(2025, 3, 29),
  "Bitcoin (BTC) Price to $72,000: Top Trader on 'Dead Cat Bounce'"),
 (datetime.date(2025, 3, 29),
  'Bitcoin (BTC) Bleeds, but Price History Says April Could Be Fire'),
 (datetime.date(2025, 3, 29),
  "Bitcoin Shows Bear Trap, '$1 Million BTC' Samson Mow Claims"),
 (datetime.date(2025, 3, 28),
  "Fidelity Says It's 'Possible' for Bitcoin to Overtake Gold"),
 (datetime.date(2025, 3, 28),
  "$1.5 Billion: BlackRock Celebrates New Crypto Milestone, And It's Not Bitcoin"),
 (datetime.date(2025, 3, 28),
  'Bitcoin (BTC) Loses Crucial 200-Day Moving Average Amid Inflation Report'),
 (datetime.date(2025, 3, 28),
  'Ethereum Crashes 74% Against Bitcoin; Is Reversal Imminent?'),
 (datetime.date(2025, 3, 28), 'Schiff: Bitcoin (BTC) to Collapse to $10K'),
 (datetime.date(2025, 3, 28), 'Bitcoin (BTC) Price Prediction for March 28'),
 (datetime.date(2025, 3, 28),
  'Breaking: Tether Mints 1 Billion USDT Tokens as Bitcoin Plunges Below $85K'),
 (datetime.date(2025, 3, 28),
  'Bitcoin (BTC) Major Core Update: Key Changes Revealed'),
 (datetime.date(2025, 3, 28),
  'Bitcoin (BTC) Faces Brutal Drop, Confirms Legendary Trader Peter Brandt'),
 (datetime.date(2025, 3, 28),
  "'Rich Dad Poor Dad' Author Predicts New ATH for Second Best Asset to Bitcoin"),
 (datetime.date(2025, 3, 28),
  "Shiba Inu (SHIB): Bulls in Control Now? Bitcoin (BTC) in Great Spot, Ethereum (ETH): Major Bearish Signal, But There's Silver Lining "),
 (datetime.date(2025, 3, 27),
  "Buying Bitcoin 'Not Viable Long-Term Business Model', Says Peter Schiff"),
 (datetime.date(2025, 3, 27),
  'US Government Moving Millions of Dollars Worth of Bitcoin'),
 (datetime.date(2025, 3, 27),
  'GameStop Shares Getting Annihilated Following Bitcoin Pivot'),
 (datetime.date(2025, 4, 1), 'Top Crypto Exchanges 2025: Full Guide'),
 (datetime.date(2025, 2, 2),
  'Ripple v. SEC: How Will New Developments Affect XRP Price?'),
 (datetime.date(2025, 1, 18), 'Stellar Lumen (XLM) Price Prediction 2025'),
 (datetime.date(2025, 1, 16),
  'What is DeSci: Guide on Decentralized Science in Crypto'),
 (datetime.date(2025, 1, 15),
  'Top 10 Crypto Media Outlets Enter 2025: Latest Similarweb Data Update')]

In [31]:
Bitcoin_Dataf = pd.DataFrame(Bitcoin_data, columns = ['date', 'title'])
Bitcoin_Dataf

          date                                              title
0   2025-04-02  Bitcoin (BTC) Controlled by Bears, But There's...
1   2025-04-02  Bitcoin (BTC) Price Sees Very Rare Golden and ...
2   2025-04-02  Bitcoin: Mike McGlone's Bearish $10,000 Outloo...
3   2025-04-02  XRP, DOGE and Bitcoin Wiped out in $287 Millio...
4   2025-04-01  Peter Schiff to Grow Bitcoin Reserve on Public...
5   2025-04-01   Canadian Billionaire Says Bitcoin and Gold Ar...
6   2025-04-01  Bitcoin Bulls, Buckle Up: Bollinger Bands Hint...
7   2025-04-01  Fidelity Spotlights 8-Year-Old Bullish Bitcoin...
8   2025-04-01  Bitcoin (BTC) Records Major Volume Reversal, X...
9   2025-04-01      XRP on Verge of Big Bitcoin Move, and It's Up
10  2025-04-01  'Don't Be Fool. Buy Bitcoin,' Michael Saylor Says
11  2025-04-01  Tether Buys 8,888 Bitcoin in Epic Buy-the-Dip ...
12  2025-04-01     Bitcoin Mogul Successfully Launched into Space
13  2025-03-31  $1 Billion USDT Minted as Bitcoin Whales Prepa...
14  2025-03-31  Bitcoin (BTC) Outperforms Gold Amid Macro Unce...
15  2025-03-31  Stunning Chart Highlights Strategy's Bitcoin D...
16  2025-03-31  XRP Army Lambasts Gemini CEO, 649,331,848 Doge...
17  2025-03-31  BlackRock CEO Warns US Dollar Could Lose to Bi...
18  2025-03-31  Litecoin (LTC) Decouples From Bitcoin in Key M...
19  2025-03-31  Breaking: Strategy Buys Nearly $2 Billion Wort...
20  2025-03-31  Bitcoin (BTC) 'Death Cross' Appears on Rare In...
21  2025-03-31  Spot Bitcoin ETF Inflows Down 73% in Seven Day...
22  2025-03-31         Metaplanet Issues More Debt to Buy Bitcoin
23  2025-03-31  XRP Rapidly Diving Below $2, Bitcoin (BTC) on ...
24  2025-03-30         Bitcoin Magnate to Fly into Space Tomorrow
25  2025-03-30        Bitcoin (BTC) Price Prediction for March 30
26  2025-03-30  Bitcoin (BTC) Finds Bottom? Key Indicator Hint...
27  2025-03-30  Michael Saylor Teases Another Bitcoin Mega-Buy...
28  2025-03-30  Bitcoin ETFs Skyrocket by $200 Million, but Wo...
29  2025-03-30  Mysterious $333,000,000 Bitcoin Transfer Stuns...
30  2025-03-30               Has 20,000,000th Bitcoin Been Mined?
31  2025-03-30  Legendary Trader Brandt Warns This Bitcoin Pat...
32  2025-03-29  15 Years Since Huge Bitcoin Bug Satoshi Had to...
33  2025-03-29  Bitcoin (BTC) Price to $72,000: Top Trader on ...
34  2025-03-29  Bitcoin (BTC) Bleeds, but Price History Says A...
35  2025-03-29  Bitcoin Shows Bear Trap, '$1 Million BTC' Sams...
36  2025-03-28  Fidelity Says It's 'Possible' for Bitcoin to O...
37  2025-03-28  $1.5 Billion: BlackRock Celebrates New Crypto ...
38  2025-03-28  Bitcoin (BTC) Loses Crucial 200-Day Moving Ave...
39  2025-03-28  Ethereum Crashes 74% Against Bitcoin; Is Rever...
40  2025-03-28          Schiff: Bitcoin (BTC) to Collapse to $10K
41  2025-03-28        Bitcoin (BTC) Price Prediction for March 28
42  2025-03-28  Breaking: Tether Mints 1 Billion USDT Tokens a...
43  2025-03-28  Bitcoin (BTC) Major Core Update: Key Changes R...
44  2025-03-28  Bitcoin (BTC) Faces Brutal Drop, Confirms Lege...
45  2025-03-28  'Rich Dad Poor Dad' Author Predicts New ATH fo...
46  2025-03-28  Shiba Inu (SHIB): Bulls in Control Now? Bitcoi...
47  2025-03-27  Buying Bitcoin 'Not Viable Long-Term Business ...
48  2025-03-27  US Government Moving Millions of Dollars Worth...
49  2025-03-27  GameStop Shares Getting Annihilated Following ...
50  2025-04-01              Top Crypto Exchanges 2025: Full Guide
51  2025-02-02  Ripple v. SEC: How Will New Developments Affec...
52  2025-01-18          Stellar Lumen (XLM) Price Prediction 2025
53  2025-01-16  What is DeSci: Guide on Decentralized Science ...
54  2025-01-15  Top 10 Crypto Media Outlets Enter 2025: Latest...

In [32]:
Bitcoin_Dataf['currency'] = "Bitcoin"
Bitcoin_Dataf

          date                                              title currency
0   2025-04-02  Bitcoin (BTC) Controlled by Bears, But There's...  Bitcoin
1   2025-04-02  Bitcoin (BTC) Price Sees Very Rare Golden and ...  Bitcoin
2   2025-04-02  Bitcoin: Mike McGlone's Bearish $10,000 Outloo...  Bitcoin
3   2025-04-02  XRP, DOGE and Bitcoin Wiped out in $287 Millio...  Bitcoin
4   2025-04-01  Peter Schiff to Grow Bitcoin Reserve on Public...  Bitcoin
5   2025-04-01   Canadian Billionaire Says Bitcoin and Gold Ar...  Bitcoin
6   2025-04-01  Bitcoin Bulls, Buckle Up: Bollinger Bands Hint...  Bitcoin
7   2025-04-01  Fidelity Spotlights 8-Year-Old Bullish Bitcoin...  Bitcoin
8   2025-04-01  Bitcoin (BTC) Records Major Volume Reversal, X...  Bitcoin
9   2025-04-01      XRP on Verge of Big Bitcoin Move, and It's Up  Bitcoin
10  2025-04-01  'Don't Be Fool. Buy Bitcoin,' Michael Saylor Says  Bitcoin
11  2025-04-01  Tether Buys 8,888 Bitcoin in Epic Buy-the-Dip ...  Bitcoin
12  2025-04-01     Bitcoin Mogul Successfully Launched into Space  Bitcoin
13  2025-03-31  $1 Billion USDT Minted as Bitcoin Whales Prepa...  Bitcoin
14  2025-03-31  Bitcoin (BTC) Outperforms Gold Amid Macro Unce...  Bitcoin
15  2025-03-31  Stunning Chart Highlights Strategy's Bitcoin D...  Bitcoin
16  2025-03-31  XRP Army Lambasts Gemini CEO, 649,331,848 Doge...  Bitcoin
17  2025-03-31  BlackRock CEO Warns US Dollar Could Lose to Bi...  Bitcoin
18  2025-03-31  Litecoin (LTC) Decouples From Bitcoin in Key M...  Bitcoin
19  2025-03-31  Breaking: Strategy Buys Nearly $2 Billion Wort...  Bitcoin
20  2025-03-31  Bitcoin (BTC) 'Death Cross' Appears on Rare In...  Bitcoin
21  2025-03-31  Spot Bitcoin ETF Inflows Down 73% in Seven Day...  Bitcoin
22  2025-03-31         Metaplanet Issues More Debt to Buy Bitcoin  Bitcoin
23  2025-03-31  XRP Rapidly Diving Below $2, Bitcoin (BTC) on ...  Bitcoin
24  2025-03-30         Bitcoin Magnate to Fly into Space Tomorrow  Bitcoin
25  2025-03-30        Bitcoin (BTC) Price Prediction for March 30  Bitcoin
26  2025-03-30  Bitcoin (BTC) Finds Bottom? Key Indicator Hint...  Bitcoin
27  2025-03-30  Michael Saylor Teases Another Bitcoin Mega-Buy...  Bitcoin
28  2025-03-30  Bitcoin ETFs Skyrocket by $200 Million, but Wo...  Bitcoin
29  2025-03-30  Mysterious $333,000,000 Bitcoin Transfer Stuns...  Bitcoin
30  2025-03-30               Has 20,000,000th Bitcoin Been Mined?  Bitcoin
31  2025-03-30  Legendary Trader Brandt Warns This Bitcoin Pat...  Bitcoin
32  2025-03-29  15 Years Since Huge Bitcoin Bug Satoshi Had to...  Bitcoin
33  2025-03-29  Bitcoin (BTC) Price to $72,000: Top Trader on ...  Bitcoin
34  2025-03-29  Bitcoin (BTC) Bleeds, but Price History Says A...  Bitcoin
35  2025-03-29  Bitcoin Shows Bear Trap, '$1 Million BTC' Sams...  Bitcoin
36  2025-03-28  Fidelity Says It's 'Possible' for Bitcoin to O...  Bitcoin
37  2025-03-28  $1.5 Billion: BlackRock Celebrates New Crypto ...  Bitcoin
38  2025-03-28  Bitcoin (BTC) Loses Crucial 200-Day Moving Ave...  Bitcoin
39  2025-03-28  Ethereum Crashes 74% Against Bitcoin; Is Rever...  Bitcoin
40  2025-03-28          Schiff: Bitcoin (BTC) to Collapse to $10K  Bitcoin
41  2025-03-28        Bitcoin (BTC) Price Prediction for March 28  Bitcoin
42  2025-03-28  Breaking: Tether Mints 1 Billion USDT Tokens a...  Bitcoin
43  2025-03-28  Bitcoin (BTC) Major Core Update: Key Changes R...  Bitcoin
44  2025-03-28  Bitcoin (BTC) Faces Brutal Drop, Confirms Lege...  Bitcoin
45  2025-03-28  'Rich Dad Poor Dad' Author Predicts New ATH fo...  Bitcoin
46  2025-03-28  Shiba Inu (SHIB): Bulls in Control Now? Bitcoi...  Bitcoin
47  2025-03-27  Buying Bitcoin 'Not Viable Long-Term Business ...  Bitcoin
48  2025-03-27  US Government Moving Millions of Dollars Worth...  Bitcoin
49  2025-03-27  GameStop Shares Getting Annihilated Following ...  Bitcoin
50  2025-04-01              Top Crypto Exchanges 2025: Full Guide  Bitcoin
51  2025-02-02  Ripple v. SEC: How Will New Developments Affec...  Bitcoin
52  2025-01-18          Stellar Lumen (XLM) Price Prediction 2025  Bitcoin
53  2025-01-16  What is DeSci: Guide on Decentralized Science ...  Bitcoin
54  2025-01-15  Top 10 Crypto Media Outlets Enter 2025: Latest...  Bitcoin

In [33]:
# Optional: Save to CSV
Bitcoin_Dataf.to_csv('Bitcoin_Daily_News.csv', index=False)

# Ethereum scrapping

In [34]:
import requests

url = 'import requests'

url = 'https://u.today/search/node?keys=Ethereum'
response_e = requests.get(url)
response_e

In [35]:
import requests
import bs4

response = requests.get("https://u.today/search/node?keys=Ethereum")
# soup = bs4.BeautifulSoup(response.text, 'lxml') # with lxml package
doc = bs4.BeautifulSoup(response.text, 'html.parser') 
doc

 <!DOCTYPE html>

<html class="theme-light" dir="ltr" lang="en" prefix="og: ogp.me/ns#">
<head>
<script async="" crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9245916885225528"></script>
<link href="https://www.google-analytics.com" rel="preconnect"/>
<meta content="width=device-width, initial-scale=1.0, maximum-scale=5" name="viewport"/>
<script src="/core/assets/vendor/jquery/jquery.min.js"></script>
<meta charset="utf-8">
<link href="https://u.today/search/node" rel="canonical">
<meta content="article" property="og:type"/>
<meta content="https://u.today/search/node" property="og:url"/>
<meta content="Search" property="og:title"/>
<meta content="Search" property="og:description"/>
<meta content="https://u.today/img/logo-utoday.png" property="og:image"/>
<meta content="https://u.today/img/logo-utoday.png" property="og:image:url"/>
<meta content="https://u.today/img/logo-utoday.png" property="og:image:secure_url"/>
<meta content="2560796210663191" property="fb:app_id"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@Utoday_en" name="twitter:site"/>
<meta content="https://u.today/img/logo-utoday.png" name="twitter:image"/>
<meta content="Drupal 10 (https://www.drupal.org)" name="Generator"/>
<meta content="width" name="MobileOptimized"/>
<meta content="true" name="HandheldFriendly"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<script type="application/ld+json">{
    "@context": "https://schema.org",
    "@graph": [
        {
            "@type": "Organization",
            "name": "U.Today",
            "url": "https://u.today/search/node",
            "image": {
                "@type": "ImageObject",
                "url": "https://U.today/img/logo-utoday.png"
            }
        }
    ]
}</script>
<!-- end: separate google analytics code -->
<!-- Google Tag Manager -->
<!-- End Google Tag Manager -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-2PE2QV2V0X"></script>
<script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-2PE2QV2V0X');
    </script>
<link color="#263238" href="/img/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
<link href="/img/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/img/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/img/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/img/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/img/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/img/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/img/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/img/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/img/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/img/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/img/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/site.webmanifest" rel="manifest"/>
<link color="#263238" href="/img/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
<link href="/img/favicon/favicon.ico" rel="shortcut icon"/>
<meta content="#263238" name="msapplication-TileColor"/>
<meta content="/img/favicon/browserconfig.xml" name="msapplication-config"/>
<meta content="#263238" name="theme-color"/>
<meta content="2E6EDC1D9A57E69FC6232E905A08CBFA" name="msvalidate.01">
<link href="/manifest.json" rel="manifest">
<meta content="266789420636465" property="fb:pages">
<link href="/modules/contrib/paragraphs/css/paragraphs.unpublished.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/libs/air-datepicker/air-datepicker.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/slick-theme.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/common.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/app.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/push.css?su3fvf" media="all" rel="stylesheet">
<style>.ccc-widget.ccc-list .header-div a img {
                            width: 26px;
                            height: 26px;
                        }
                    </style>
<title>Search | U.Today</title>
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js"></script>
<script>
                        function copyToClipboard(e) {
                            let input = document.body.appendChild(document.createElement("input"));
                            input.value = window.location.href;
                            input.select();
                            document.execCommand('copy');
                            input.parentNode.removeChild(input);

                            let tooltip = document.createElement('div');
                            tooltip.className = 'copy-tooltip';
                            tooltip.innerHTML = 'Copied!';

                            if (!e.querySelector('.copy-tooltip')) {
                                e.append(tooltip);

                                setTimeout(() => {
                                    e.querySelector('.copy-tooltip').remove();
                                }, 2000);
                            }
                        }
                    </script>
<style>
                        @media (max-width: 849px) {
                            body #onesignal-slidedown-container.slide-up {
                                bottom: 60px
                            }
                        }
                    </style>
<script async="" defer="" src="https://www.google.com/recaptcha/api.js"></script>
<style>
                        .captcha-container {
                            display: none; /* CAPTCHA скрыта по умолчанию */
                        }
                    </style>
<script data-cfasync="false" src="https://cmp.gatekeeperconsent.com/min.js"></script>
<script data-cfasync="false" src="https://the.gatekeeperconsent.com/cmp.min.js"></script>
<script async="" src="//www.ezojs.com/ezoic/sa.min.js"></script>
<script>
                        window.ezstandalone = window.ezstandalone || {};
                        ezstandalone.cmd = ezstandalone.cmd || [];
                    </script>
</link></link></link></link></link></link></meta></link></meta></link></meta></head>
<body class="not_logged_in">
<!-- Google Tag Manager (noscript) -->
<!-- End Google Tag Manager (noscript) -->
<div class="something--upper">
<div class="something">
<div class="something__title">Advertisement</div>
<div class="something__nav">
<div class="something__label">AD</div>
<button aria-label="Close ad" class="btn btn--light something__close"></button>
</div>
<div class="something__content">
<div class="something__content--long">
<div>
<!-- Wideheader Fixed Desktop 1150x60 [async] -->
<script type="text/javascript">

if (!window.AdButler){(function(){var s = document.createElement("script"); s.async = true; s.type = "text/javascript"; s.src = 'https://servedbyadbutler.com/app.js'; var n = document.getElementsByTagName("script")[0]; n.parentNode.insertBefore(s, n);}());}

</script>
<script type="text/javascript">
var AdButler = AdButler || {};
AdButler.ads = AdButler.ads || [];
var abkw = window.abkw || '';
var plc602403 = window.plc602403 || 0;
document.write('<'+'div id="placement_602403_'+plc602403+'"></'+'div>');
AdButler.ads.push({handler: function(opt){ AdButler.register(183269, 602403, [1150,60], 'placement_602403_'+opt.place, opt); }, opt: { place: plc602403++, keywords: abkw, domain: 'servedbyadbutler.com', click: 'CLICK_MACRO_PLACEHOLDER' }});

</script>
</div>
</div>
<div class="something__content--square">
<div>
<!-- Wideheader Fixed Mobile 336x60 [async] -->
<script type="text/javascript">
if (document.documentElement.clientWidth < 768) {
if (!window.AdButler){(function(){var s = document.createElement("script"); s.async = true; s.type = "text/javascript"; s.src = 'https://servedbyadbutler.com/app.js'; var n = document.getElementsByTagName("script")[0]; n.parentNode.insertBefore(s, n);}());}
}
</script>
<script type="text/javascript">
if (document.documentElement.clientWidth < 768) {
var AdButler = AdButler || {};
AdButler.ads = AdButler.ads || [];
var abkw = window.abkw || '';
var plc551690 = window.plc551690 || 0;
document.write('<'+'div id="placement_551690_'+plc551690+'"></'+'div>');
AdButler.ads.push({handler: function(opt){ AdButler.register(183269, 551690, [336,60], 'placement_551690_'+opt.place, opt); }, opt: { place: plc551690++, keywords: abkw, domain: 'servedbyadbutler.com', click: 'CLICK_MACRO_PLACEHOLDER' }});
}
</script>
</div>
</div>
</div>
</div>
</div>
<header class="header">
<div class="header__container"><a class="header__logo" href="https://u.today/" title="U.Today logo"></a>
<div class="header__search" style="display: block">
<form action="/search/node" class="header__search-form" method="get">
<button class="header__search-submit btn btn--light btn--search" style="display: none;" type="submit"></button>
<input class="header__search-input" id="search_text" name="keys" type="text"/>
<button class="header__search-close btn btn--light btn--cross"></button>
</form>
</div>
</div>
</header>
<div class="mobile-menu-cover"></div>
<div class="page-container container">
<div class="something--leaderboard">
<div class="something">
<div class="something__title">Advertisement</div>
<div class="something__nav">
<div class="something__label">AD</div>
<button aria-label="Close ad" class="btn btn--light something__close"></button>
</div>
<div class="something__content">
<div class="something__content--long">
<div>
<!-- Leaderboard Desktop 1150x90 [async] -->
<script type="text/javascript">
if (window.innerWidth > 768) {
if (!window.AdButler){(function(){var s = document.createElement("script"); s.async = true; s.type = "text/javascript"; s.src = 'https://servedbyadbutler.com/app.js'; var n = document.getElementsByTagName("script")[0]; n.parentNode.insertBefore(s, n);}());}
}
</script>
<script type="text/javascript">
if (window.innerWidth > 768) {
var AdButler = AdButler || {};
AdButler.ads = AdButler.ads || [];
var abkw = window.abkw || '';
var plc828210 = window.plc828210 || 0;
document.write('<'+'div id="placement_828210_'+plc828210+'"></'+'div>');
AdButler.ads.push({handler: function(opt){ AdButler.register(183269, 828210, [1150,90], 'placement_828210_'+opt.place, opt); }, opt: { place: plc828210++, keywords: abkw, domain: 'servedbyadbutler.com', click: 'CLICK_MACRO_PLACEHOLDER' }});
}
</script>
</div>
</div>
<div class="something__content--square">
</div>
</div>
</div>
</div>
<div class="main-aside-container">
<main class="main-block">
<div class="search-result">
<h1 class="page-bg-title">Search results for “Ethereum”</h1>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 2, 2025 - 14:20</div>
</div>
<a class="news__item-body" href="https://u.today/ethereum-eth-price-prediction-for-april-2">
<div class="news__item-title">Ethereum (ETH) Price Prediction for April 2</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
            </a></div>
</div>
<div class="something something--content">
<div class="something__content-long">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="1698558466" style="display:inline-block;width:728px;height:90px"></ins>
</div>
<div class="something__content-square">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="4003311693" style="display:inline-block;width:336px;height:280px"></ins>
</div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 1, 2025 - 15:31</div>
</div>
<a class="news__item-body" href="https://u.today/bitcoin-btc-records-major-volume-reversal-xrp-doesnt-really-need-2-did-ethereum-eth-forget-about">
<div class="news__item-title">Bitcoin (BTC) Records Major Volume Reversal, XRP Doesn't Really Need $2, Did Ethereum (ETH) Forget About $2,000?</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 30, 2025 - 14:43</div>
</div>
<a class="news__item-body" href="https://u.today/ethereum-eth-price-prediction-for-march-30">
<div class="news__item-title">Ethereum (ETH) Price Prediction for March 30</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 30, 2025 - 12:00</div>
</div>
<a class="news__item-body" href="https://u.today/pre-mine-ethereum-address-suddenly-activated">
<div class="news__item-title">Pre-Mine Ethereum Address Suddenly Activated</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 30, 2025 - 11:00</div>
</div>
<a class="news__item-body" href="https://u.today/ethereum-eth-awaiting-crucial-crossover-details">
<div class="news__item-title">Ethereum (ETH) Awaiting Crucial Crossover: Details</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 29, 2025 - 14:54</div>
</div>
<a class="news__item-body" href="https://u.today/ethereum-eth-price-prediction-for-march-29">
<div class="news__item-title">Ethereum (ETH) Price Prediction for March 29</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
            </a></div>
</div>
<div class="something something--content">
<div class="something__content-long">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="1698558466" style="display:inline-block;width:728px;height:90px"></ins>
</div>
<div class="something__content-square">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="4003311693" style="display:inline-block;width:336px;height:280px"></ins>
</div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 29, 2025 - 14:36</div>
</div>
<a class="news__item-body" href="https://u.today/ethereum-eth-founder-vitalik-buterin-bets-on-open-source-funding-not-public-goods">
<div class="news__item-title">Ethereum (ETH) Founder Vitalik Buterin Bets on Open Source Funding, Not Public Goods</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/vladislav-sopov"><img alt="Vladislav Sopov" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-07/8893.jpg" width="24"/>Vladislav Sopov
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 29, 2025 - 11:16</div>
</div>
<a class="news__item-body" href="https://u.today/ethereum-eth-whales-close-to-liquidation-238-million-to-be-erased">
<div class="news__item-title">Ethereum (ETH) Whales Close to Liquidation, $238 Million to Be Erased</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/vladislav-sopov"><img alt="Vladislav Sopov" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-07/8893.jpg" width="24"/>Vladislav Sopov
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 28, 2025 - 15:00</div>
</div>
<a class="news__item-body" href="https://u.today/is-1000-next-bloombergs-mcglone-queries-latest-ethereum-sell-off">
<div class="news__item-title">'Is $1,000 Next?': Bloomberg's McGlone Queries Latest Ethereum Sell-Off</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 28, 2025 - 14:54</div>
</div>
<a class="news__item-body" href="https://u.today/ethereum-crashes-74-against-bitcoin-is-reversal-imminent">
<div class="news__item-title">Ethereum Crashes 74% Against Bitcoin; Is Reversal Imminent?</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 28, 2025 - 0:01</div>
</div>
<a class="news__item-body" href="https://u.today/shiba-inu-shib-bulls-in-control-now-bitcoin-btc-in-great-spot-ethereum-eth-major-bearish-signal-but">
<div class="news__item-title">Shiba Inu (SHIB): Bulls in Control Now? Bitcoin (BTC) in Great Spot, Ethereum (ETH): Major Bearish Signal, But There's Silver Lining </div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
            </a></div>
</div>
<div class="something something--content">
<div class="something__content-long">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="1698558466" style="display:inline-block;width:728px;height:90px"></ins>
</div>
<div class="something__content-square">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="4003311693" style="display:inline-block;width:336px;height:280px"></ins>
</div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 27, 2025 - 17:11</div>
</div>
<a class="news__item-body" href="https://u.today/blockdag-bdag-pre-sale-hits-beta-testnet-launch-as-ethereum-eth-shiba-inu-shib-struggling-with">

In [36]:
# Option 1: Using CSS selectors (similar to your book_cards example)
ethereum_date = doc.select("body.not_logged_in div.main-aside-container main.main-block div.search-result div.news__item div.news__item-head div.humble")
ethereum_date

[<div class="humble">Apr 2, 2025 - 14:20</div>,
 <div class="humble">Apr 1, 2025 - 15:31</div>,
 <div class="humble">Mar 30, 2025 - 14:43</div>,
 <div class="humble">Mar 30, 2025 - 12:00</div>,
 <div class="humble">Mar 30, 2025 - 11:00</div>,
 <div class="humble">Mar 29, 2025 - 14:54</div>,
 <div class="humble">Mar 29, 2025 - 14:36</div>,
 <div class="humble">Mar 29, 2025 - 11:16</div>,
 <div class="humble">Mar 28, 2025 - 15:00</div>,
 <div class="humble">Mar 28, 2025 - 14:54</div>,
 <div class="humble">Mar 28, 2025 - 0:01</div>,
 <div class="humble">Mar 27, 2025 - 17:11</div>,
 <div class="humble">Mar 27, 2025 - 12:52</div>,
 <div class="humble">Mar 27, 2025 - 0:01</div>,
 <div class="humble">Mar 25, 2025 - 22:14</div>,
 <div class="humble">Mar 24, 2025 - 15:20</div>,
 <div class="humble">Mar 24, 2025 - 0:01</div>,
 <div class="humble">Mar 22, 2025 - 14:02</div>,
 <div class="humble">Mar 21, 2025 - 21:05</div>,
 <div class="humble">Mar 21, 2025 - 15:58</div>,
 <div class="humble">Mar 21, 2025 - 0:01</div>,
 <div class="humble">Mar 20, 2025 - 18:53</div>,
 <div class="humble">Mar 20, 2025 - 15:13</div>,
 <div class="humble">Mar 20, 2025 - 10:49</div>,
 <div class="humble">Mar 19, 2025 - 17:00</div>,
 <div class="humble">Mar 19, 2025 - 15:05</div>,
 <div class="humble">Mar 19, 2025 - 5:54</div>,
 <div class="humble">Mar 18, 2025 - 14:17</div>,
 <div class="humble">Mar 18, 2025 - 0:01</div>,
 <div class="humble">Mar 17, 2025 - 15:43</div>,
 <div class="humble">Mar 17, 2025 - 15:14</div>,
 <div class="humble">Mar 15, 2025 - 13:34</div>,
 <div class="humble">Mar 15, 2025 - 0:01</div>,
 <div class="humble">Mar 14, 2025 - 15:31</div>,
 <div class="humble">Mar 14, 2025 - 10:05</div>,
 <div class="humble">Mar 13, 2025 - 15:09</div>,
 <div class="humble">Mar 12, 2025 - 22:49</div>,
 <div class="humble">Mar 12, 2025 - 5:40</div>,
 <div class="humble">Mar 12, 2025 - 0:01</div>,
 <div class="humble">Mar 11, 2025 - 16:30</div>,
 <div class="humble">Mar 11, 2025 - 15:59</div>,
 <div class="humble">Mar 11, 2025 - 15:22</div>,
 <div class="humble">Mar 11, 2025 - 11:53</div>,
 <div class="humble">Mar 10, 2025 - 15:16</div>,
 <div class="humble">Mar 10, 2025 - 8:42</div>,
 <div class="humble">Mar 10, 2025 - 8:16</div>,
 <div class="humble">Mar 7, 2025 - 13:35</div>,
 <div class="humble">Mar 7, 2025 - 0:01</div>,
 <div class="humble">Mar 5, 2025 - 13:57</div>]

In [37]:
ethereum_dt = []
for ethereum in ethereum_date:
    
  ethereum_dt.append(ethereum.get_text())
  #print(Bitcoin.get_text())
ethereum_dt

['Apr 2, 2025 - 14:20',
 'Apr 1, 2025 - 15:31',
 'Mar 30, 2025 - 14:43',
 'Mar 30, 2025 - 12:00',
 'Mar 30, 2025 - 11:00',
 'Mar 29, 2025 - 14:54',
 'Mar 29, 2025 - 14:36',
 'Mar 29, 2025 - 11:16',
 'Mar 28, 2025 - 15:00',
 'Mar 28, 2025 - 14:54',
 'Mar 28, 2025 - 0:01',
 'Mar 27, 2025 - 17:11',
 'Mar 27, 2025 - 12:52',
 'Mar 27, 2025 - 0:01',
 'Mar 25, 2025 - 22:14',
 'Mar 24, 2025 - 15:20',
 'Mar 24, 2025 - 0:01',
 'Mar 22, 2025 - 14:02',
 'Mar 21, 2025 - 21:05',
 'Mar 21, 2025 - 15:58',
 'Mar 21, 2025 - 0:01',
 'Mar 20, 2025 - 18:53',
 'Mar 20, 2025 - 15:13',
 'Mar 20, 2025 - 10:49',
 'Mar 19, 2025 - 17:00',
 'Mar 19, 2025 - 15:05',
 'Mar 19, 2025 - 5:54',
 'Mar 18, 2025 - 14:17',
 'Mar 18, 2025 - 0:01',
 'Mar 17, 2025 - 15:43',
 'Mar 17, 2025 - 15:14',
 'Mar 15, 2025 - 13:34',
 'Mar 15, 2025 - 0:01',
 'Mar 14, 2025 - 15:31',
 'Mar 14, 2025 - 10:05',
 'Mar 13, 2025 - 15:09',
 'Mar 12, 2025 - 22:49',
 'Mar 12, 2025 - 5:40',
 'Mar 12, 2025 - 0:01',
 'Mar 11, 2025 - 16:30',
 'Mar 11, 2025 - 15:59',
 'Mar 11, 2025 - 15:22',
 'Mar 11, 2025 - 11:53',
 'Mar 10, 2025 - 15:16',
 'Mar 10, 2025 - 8:42',
 'Mar 10, 2025 - 8:16',
 'Mar 7, 2025 - 13:35',
 'Mar 7, 2025 - 0:01',
 'Mar 5, 2025 - 13:57']

In [38]:
News_card = doc.select('div.news__item')
News_card

[<div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 2, 2025 - 14:20</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-price-prediction-for-april-2">
 <div class="news__item-title">Ethereum (ETH) Price Prediction for April 2</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 15:31</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-records-major-volume-reversal-xrp-doesnt-really-need-2-did-ethereum-eth-forget-about">
 <div class="news__item-title">Bitcoin (BTC) Records Major Volume Reversal, XRP Doesn't Really Need $2, Did Ethereum (ETH) Forget About $2,000?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 30, 2025 - 14:43</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-price-prediction-for-march-30">
 <div class="news__item-title">Ethereum (ETH) Price Prediction for March 30</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 30, 2025 - 12:00</div>
 </div>
 <a class="news__item-body" href="https://u.today/pre-mine-ethereum-address-suddenly-activated">
 <div class="news__item-title">Pre-Mine Ethereum Address Suddenly Activated</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 30, 2025 - 11:00</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-awaiting-crucial-crossover-details">
 <div class="news__item-title">Ethereum (ETH) Awaiting Crucial Crossover: Details</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 29, 2025 - 14:54</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-price-prediction-for-march-29">
 <div class="news__item-title">Ethereum (ETH) Price Prediction for March 29</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 29, 2025 - 14:36</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-founder-vitalik-buterin-bets-on-open-source-funding-not-public-goods">
 <div class="news__item-title">Ethereum (ETH) Founder Vitalik Buterin Bets on Open Source Funding, Not Public Goods</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/vladislav-sopov"><img alt="Vladislav Sopov" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-07/8893.jpg" width="24"/>Vladislav Sopov
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 29, 2025 - 11:16</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-whales-close-to-liquidation-238-million-to-be-erased">
 <div class="news__item-title">Ethereum (ETH) Whales Close to Liquidation, $238 Million to Be Erased</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/vladislav-sopov"><img alt="Vladislav Sopov" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-07/8893.jpg" width="24"/>Vladislav Sopov
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 28, 2025 - 15:00</div>
 </div>
 <a class="news__item-body" href="https://u.today/is-1000-next-bloombergs-mcglone-queries-latest-ethereum-sell-off">
 <div class="news__item-title">'Is $1,000 Next?': Bloomberg's McGlone Queries Latest Ethereum Sell-Off</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 28, 2025 - 14:54</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-crashes-74-against-bitcoin-is-reversal-imminent">
 <div class="news__item-title">Ethereum Crashes 74% Against Bitcoin; Is Reversal Imminent?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 28, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/shiba-inu-shib-bulls-in-control-now-bitcoin-btc-in-great-spot-ethereum-eth-major-bearish-signal-but">
 <div class="news__item-title">Shiba Inu (SHIB): Bulls in Control Now? Bitcoin (BTC) in Great Spot, Ethereum (ETH): Major Bearish Signal, But There's Silver Lining </div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 27, 2025 - 17:11</div>
 </div>
 <a class="news__item-body" href="https://u.today/blockdag-bdag-pre-sale-hits-beta-testnet-launch-as-ethereum-eth-shiba-inu-shib-struggling-with">
 <div class="news__item-title">BlockDAG (BDAG) Pre-Sale Hits Beta Testnet Launch as Ethereum (ETH), Shiba Inu (SHIB) Struggling with Pressure</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/guest-author"><img alt="Guest Author" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/10896.jpg" width="24"/>Guest Author
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 27, 2025 - 12:52</div>
 </div>
 <a class="news__item-body" href="https://u.today/1084-million-ethereum-eth-in-24-hours-what-are-bulls-up-to">
 <div class="news__item-title">10.84 Million Ethereum (ETH) in 24 Hours, What Are Bulls up To?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 27, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/is-xrp-price-ready-for-3-ethereum-eth-seeing-2000-test-shiba-inu-shib-15-trillion-whale-pump">
 <div class="news__item-title">Is XRP Price Ready for $3? Ethereum (ETH) Seeing $2,000 Test, Shiba Inu (SHIB) 1.5 Trillion Whale Pump Recorded</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 25, 2025 - 22:14</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-adoption-grows-with-launch-of-bank-issued-stablecoin">
 <div class="news__item-title">Ethereum Adoption Grows With Launch of Bank-Issued Stablecoin</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/caroline-amosun"><img alt="Caroline Amosun" class="humble__img" height="24" src="https://u.today/sites/default/files/2025-03/56827.jpg" width="24"/>Caroline Amosun
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 24, 2025 - 15:20</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-price-prediction-for-march-24">
 <div class="news__item-title">Ethereum (ETH) Price Prediction for March 24</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 24, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-invalidates-crucial-price-setup-xrp-faces-50-and-100-day-squeeze-ethereum-eth-finally">
 <div class="news__item-title">Bitcoin (BTC) Invalidates Crucial Price Setup, XRP Faces 50 and 100 Day Squeeze, Ethereum (ETH) Finally Bounces Back?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 22, 2025 - 14:02</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-price-prediction-for-march-22">
 <div class="news__item-title">Ethereum (ETH) Price Prediction for March 22</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 21, 2025 - 21:05</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-fees-plummet-50-as-network-activity-slowdown-sparks-concerns">
 <div class="news__item-title">Ethereum (ETH) Fees Plummet 50% as Network Activity Slowdown Sparks Concerns</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/andy-sawa"><img alt="Andy Sawa" class="humble__img" height="24" src="https://u.today/sites/default/files/2025-03/56809.jpg" width="24"/>Andy Sawa
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 21, 2025 - 15:58</div>
 </div>
 <a class="news__item-body" href="https://u.today/new-key-date-for-xrp-holders-just-emerged-major-exchange-lists-ada-and-coinbase-ethereum-for">
 <div class="news__item-title">New Key Date for XRP Holders Just Emerged, Major Exchange Lists ADA and Coinbase Ethereum for Futures Collateral, Billions of SHIB Purchased by Major Dormant ETH Whale: Crypto News Digest by U.Today</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/valeria-blokhina"><img alt="Valeria Blokhina" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-10/9844.jpg" width="24"/>Valeria Blokhina
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 21, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/is-3-xrp-possible-bitcoin-btc-makes-biggest-breakout-in-2025-ethereum-eth-finally-above-2000">
 <div class="news__item-title">Is $3 XRP Possible? Bitcoin (BTC) Makes Biggest Breakout in 2025, Ethereum (ETH) Finally Above $2,000</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 20, 2025 - 18:53</div>
 </div>
 <a class="news__item-body" href="https://u.today/new-ethereum-etf-staking-proposal-filed-by-nyse">
 <div class="news__item-title">New Ethereum ETF Staking Proposal Filed by NYSE </div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 20, 2025 - 15:13</div>
 </div>
 <a class="news__item-body" href="https://u.today/billions-of-shiba-inu-shib-acquired-by-major-dormant-ethereum-whale">
 <div class="news__item-title">Billions of Shiba Inu (SHIB) Acquired by Major Dormant Ethereum Whale</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 20, 2025 - 10:49</div>
 </div>
 <a class="news__item-body" href="https://u.today/major-exchange-lists-cardano-ada-and-coinbase-ethereum-for-futures-collateral">
 <div class="news__item-title">Major Exchange Lists Cardano (ADA) and Coinbase Ethereum for Futures Collateral</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 19, 2025 - 17:00</div>
 </div>
 <a class="news__item-body" href="https://u.today/blockdag-bdag-enters-new-roadmap-phase-as-shiba-inu-shib-ethereum-eth-price-metrics-consolidate">
 <div class="news__item-title">BlockDAG (BDAG) Enters New Roadmap Phase as Shiba Inu (SHIB), Ethereum (ETH) Price Metrics Consolidate</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/guest-author"><img alt="Guest Author" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/10896.jpg" width="24"/>Guest Author
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 19, 2025 - 15:05</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-price-prediction-for-march-19">
 <div class="news__item-title">Ethereum (ETH) Price Prediction for March 19</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/events">Event</a></div>
 <a class="news__item-body" href="https://u.today/events/consensus-2025">
 <div class="news__item-title">Consensus 2025</div>
 </a>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 19, 2025 - 5:54</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-etfs-hemorrhage-50-million">
 <div class="news__item-title">Ethereum ETFs Hemorrhage $50 Million </div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 18, 2025 - 14:17</div>
 </div>
 <a class="news__item-body" href="https://u.today/ethereum-eth-developers-launch-hoodi-testnet-and-prepare-pectra-for-mainnet-launch-in-may">
 <div class="news__item-title">Ethereum (ETH) Developers Launch Hoodi Testnet and Prepare Pectra for Mainnet Launch in May</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/vladislav-sopov"><img alt="Vladislav Sopov" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-07/8893.jpg" width="24"/>Vladislav Sopov
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 18, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/shiba-inu-shib-reaches-crucial-price-test-ethereum-eth-eyeing-2000-again-can-xrp-avoid-this-grim">
 <div class="news__item-title">Shiba Inu (SHIB) Reaches Crucial Price Test, Ethereum (ETH) Eyeing $2,000 Again, Can XRP Avoid This Grim Movement?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 17, 2025 - 15:43</div>
 </div>
 <a class="news__item-body" href="https://u.today/standard-chartered-dramatically-reduces-ethereum-eth-price-target">
 <div class="news__item-title">Standard Chartered Dramatically Reduces Ethereum (ETH) Price Target </div>
 </a>

In [39]:
ethereum_data = []
for cards in News_card:
    data = []
    date_eth = card.select_one('div.news__item-head div.humble')
    if date_eth != None:
        datestr = date_eth.get_text()
        data.append(datetime.strptime(datestr.split(" - ")[0], "%b %d, %Y").date())
    title_eth = cards.select_one('div.news__item-title')
    if title_eth != None:
        data.append(title_eth.get_text())
    if len(data) == 2:
        ethereum_data.append(tuple(data))
    
ethereum_data

[(datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for April 2'),
 (datetime.date(2025, 1, 15),
  "Bitcoin (BTC) Records Major Volume Reversal, XRP Doesn't Really Need $2, Did Ethereum (ETH) Forget About $2,000?"),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for March 30'),
 (datetime.date(2025, 1, 15), 'Pre-Mine Ethereum Address Suddenly Activated'),
 (datetime.date(2025, 1, 15),
  'Ethereum (ETH) Awaiting Crucial Crossover: Details'),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for March 29'),
 (datetime.date(2025, 1, 15),
  'Ethereum (ETH) Founder Vitalik Buterin Bets on Open Source Funding, Not Public Goods'),
 (datetime.date(2025, 1, 15),
  'Ethereum (ETH) Whales Close to Liquidation, $238 Million to Be Erased'),
 (datetime.date(2025, 1, 15),
  "'Is $1,000 Next?': Bloomberg's McGlone Queries Latest Ethereum Sell-Off"),
 (datetime.date(2025, 1, 15),
  'Ethereum Crashes 74% Against Bitcoin; Is Reversal Imminent?'),
 (datetime.date(2025, 1, 15),
  "Shiba Inu (SHIB): Bulls in Control Now? Bitcoin (BTC) in Great Spot, Ethereum (ETH): Major Bearish Signal, But There's Silver Lining "),
 (datetime.date(2025, 1, 15),
  'BlockDAG (BDAG) Pre-Sale Hits Beta Testnet Launch as Ethereum (ETH), Shiba Inu (SHIB) Struggling with Pressure'),
 (datetime.date(2025, 1, 15),
  '10.84 Million Ethereum (ETH) in 24 Hours, What Are Bulls up To?'),
 (datetime.date(2025, 1, 15),
  'Is XRP Price Ready for $3? Ethereum (ETH) Seeing $2,000 Test, Shiba Inu (SHIB) 1.5 Trillion Whale Pump Recorded'),
 (datetime.date(2025, 1, 15),
  'Ethereum Adoption Grows With Launch of Bank-Issued Stablecoin'),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for March 24'),
 (datetime.date(2025, 1, 15),
  'Bitcoin (BTC) Invalidates Crucial Price Setup, XRP Faces 50 and 100 Day Squeeze, Ethereum (ETH) Finally Bounces Back?'),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for March 22'),
 (datetime.date(2025, 1, 15),
  'Ethereum (ETH) Fees Plummet 50% as Network Activity Slowdown Sparks Concerns'),
 (datetime.date(2025, 1, 15),
  'New Key Date for XRP Holders Just Emerged, Major Exchange Lists ADA and Coinbase Ethereum for Futures Collateral, Billions of SHIB Purchased by Major Dormant ETH Whale: Crypto News Digest by U.Today'),
 (datetime.date(2025, 1, 15),
  'Is $3 XRP Possible? Bitcoin (BTC) Makes Biggest Breakout in 2025, Ethereum (ETH) Finally Above $2,000'),
 (datetime.date(2025, 1, 15),
  'New Ethereum ETF Staking Proposal Filed by NYSE '),
 (datetime.date(2025, 1, 15),
  'Billions of Shiba Inu (SHIB) Acquired by Major Dormant Ethereum Whale'),
 (datetime.date(2025, 1, 15),
  'Major Exchange Lists Cardano (ADA) and Coinbase Ethereum for Futures Collateral'),
 (datetime.date(2025, 1, 15),
  'BlockDAG (BDAG) Enters New Roadmap Phase as Shiba Inu (SHIB), Ethereum (ETH) Price Metrics Consolidate'),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for March 19'),
 (datetime.date(2025, 1, 15), 'Consensus 2025'),
 (datetime.date(2025, 1, 15), 'Ethereum ETFs Hemorrhage $50 Million '),
 (datetime.date(2025, 1, 15),
  'Ethereum (ETH) Developers Launch Hoodi Testnet and Prepare Pectra for Mainnet Launch in May'),
 (datetime.date(2025, 1, 15),
  'Shiba Inu (SHIB) Reaches Crucial Price Test, Ethereum (ETH) Eyeing $2,000 Again, Can XRP Avoid This Grim Movement?'),
 (datetime.date(2025, 1, 15),
  'Standard Chartered Dramatically Reduces Ethereum (ETH) Price Target '),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for March 17'),
 (datetime.date(2025, 1, 15),
  'Solana vs. Ethereum: Eight Parameters Compared by Crypto Expert'),
 (datetime.date(2025, 1, 15),
  'XRP Already Recovered 20%, Enormous Ethereum (ETH) Selling Volume Before $2,000, Sixth Shiba Inu (SHIB) Recovery Attempt: Another Crash?'),
 (datetime.date(2025, 1, 15),
  "XRP Flips Ethereum in Fully Diluted Valuation, Here's Implication"),
 (datetime.date(2025, 1, 15),
  'XRP vs. Ethereum (ETH): Ripple CTO Clears up Major Sale Misconception'),
 (datetime.date(2025, 1, 15),
  'No, Ethereum (ETH) Is Not Dead, Says Top Analyst'),
 (datetime.date(2025, 1, 15),
  'Ethereum Risks Drop to $1,400, Mirroring 2020 Crash, Crypto Trader Warns'),
 (datetime.date(2025, 1, 15),
  'Ethereum ETFs Log Nearly $22 Million Worth of Outflows'),
 (datetime.date(2025, 1, 15),
  'Solana (SOL) Death Cross Incoming, Dogecoin (DOGE) Hits Last Possible Support, Ethereum (ETH) Says Goodbye to $2,000 '),
 (datetime.date(2025, 1, 15),
  'Fidelity Files for Staking on Ethereum ETF Product'),
 (datetime.date(2025, 1, 15),
  'Ethereum Foundation Makes 30,098 ETH Liquidation Play on Maker: Details'),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for March 11'),
 (datetime.date(2025, 1, 15),
  'Tron Founder Justin Sun Issues Crucial Ethereum Warning: Details'),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for March 10'),
 (datetime.date(2025, 1, 15),
  'Consensys CEO Says Ethereum Must Remain Neutral '),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH): $2,000 Might Be Lost Today'),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for March 7'),
 (datetime.date(2025, 1, 15),
  "XRP's $2.50 Price Breakout Still Questionable, Dogecoin (DOGE) Hits Major Support Again, Ethereum (ETH) Not Okay"),
 (datetime.date(2025, 1, 15), 'Ethereum (ETH) Price Prediction for March 5'),
 (datetime.date(2025, 1, 15),
  'DePIN Summit Africa 2025 Announced for July 2nd in Mombasa and July 4-5th in Zanzibar'),
 (datetime.date(2025, 1, 15),
  'Rivalz AI partners with 51nodes to drive AI-Powered Transformation Across German Industry'),
 (datetime.date(2025, 1, 15),
  'New hybrid exchange EVEDEX Secures Funding from Exclusive $10 Billion Dollar Club'),
 (datetime.date(2025, 1, 15), 'Top Crypto Exchanges 2025: Full Guide'),
 (datetime.date(2025, 1, 15),
  'Ripple v. SEC: How Will New Developments Affect XRP Price?'),
 (datetime.date(2025, 1, 15), 'Stellar Lumen (XLM) Price Prediction 2025'),
 (datetime.date(2025, 1, 15),
  'What is DeSci: Guide on Decentralized Science in Crypto'),
 (datetime.date(2025, 1, 15),
  'Top 10 Crypto Media Outlets Enter 2025: Latest Similarweb Data Update')]

In [40]:
ethereum_DFM = pd.DataFrame(ethereum_data, columns = ['date', 'title'])
ethereum_DFM

          date                                              title
0   2025-01-15        Ethereum (ETH) Price Prediction for April 2
1   2025-01-15  Bitcoin (BTC) Records Major Volume Reversal, X...
2   2025-01-15       Ethereum (ETH) Price Prediction for March 30
3   2025-01-15       Pre-Mine Ethereum Address Suddenly Activated
4   2025-01-15  Ethereum (ETH) Awaiting Crucial Crossover: Det...
5   2025-01-15       Ethereum (ETH) Price Prediction for March 29
6   2025-01-15  Ethereum (ETH) Founder Vitalik Buterin Bets on...
7   2025-01-15  Ethereum (ETH) Whales Close to Liquidation, $2...
8   2025-01-15  'Is $1,000 Next?': Bloomberg's McGlone Queries...
9   2025-01-15  Ethereum Crashes 74% Against Bitcoin; Is Rever...
10  2025-01-15  Shiba Inu (SHIB): Bulls in Control Now? Bitcoi...
11  2025-01-15  BlockDAG (BDAG) Pre-Sale Hits Beta Testnet Lau...
12  2025-01-15  10.84 Million Ethereum (ETH) in 24 Hours, What...
13  2025-01-15  Is XRP Price Ready for $3? Ethereum (ETH) Seei...
14  2025-01-15  Ethereum Adoption Grows With Launch of Bank-Is...
15  2025-01-15       Ethereum (ETH) Price Prediction for March 24
16  2025-01-15  Bitcoin (BTC) Invalidates Crucial Price Setup,...
17  2025-01-15       Ethereum (ETH) Price Prediction for March 22
18  2025-01-15  Ethereum (ETH) Fees Plummet 50% as Network Act...
19  2025-01-15  New Key Date for XRP Holders Just Emerged, Maj...
20  2025-01-15  Is $3 XRP Possible? Bitcoin (BTC) Makes Bigges...
21  2025-01-15   New Ethereum ETF Staking Proposal Filed by NYSE
22  2025-01-15  Billions of Shiba Inu (SHIB) Acquired by Major...
23  2025-01-15  Major Exchange Lists Cardano (ADA) and Coinbas...
24  2025-01-15  BlockDAG (BDAG) Enters New Roadmap Phase as Sh...
25  2025-01-15       Ethereum (ETH) Price Prediction for March 19
26  2025-01-15                                     Consensus 2025
27  2025-01-15              Ethereum ETFs Hemorrhage $50 Million
28  2025-01-15  Ethereum (ETH) Developers Launch Hoodi Testnet...
29  2025-01-15  Shiba Inu (SHIB) Reaches Crucial Price Test, E...
30  2025-01-15  Standard Chartered Dramatically Reduces Ethere...
31  2025-01-15       Ethereum (ETH) Price Prediction for March 17
32  2025-01-15  Solana vs. Ethereum: Eight Parameters Compared...
33  2025-01-15  XRP Already Recovered 20%, Enormous Ethereum (...
34  2025-01-15  XRP Flips Ethereum in Fully Diluted Valuation,...
35  2025-01-15  XRP vs. Ethereum (ETH): Ripple CTO Clears up M...
36  2025-01-15   No, Ethereum (ETH) Is Not Dead, Says Top Analyst
37  2025-01-15  Ethereum Risks Drop to $1,400, Mirroring 2020 ...
38  2025-01-15  Ethereum ETFs Log Nearly $22 Million Worth of ...
39  2025-01-15  Solana (SOL) Death Cross Incoming, Dogecoin (D...
40  2025-01-15  Fidelity Files for Staking on Ethereum ETF Pro...
41  2025-01-15  Ethereum Foundation Makes 30,098 ETH Liquidati...
42  2025-01-15       Ethereum (ETH) Price Prediction for March 11
43  2025-01-15  Tron Founder Justin Sun Issues Crucial Ethereu...
44  2025-01-15       Ethereum (ETH) Price Prediction for March 10
45  2025-01-15   Consensys CEO Says Ethereum Must Remain Neutral
46  2025-01-15         Ethereum (ETH): $2,000 Might Be Lost Today
47  2025-01-15        Ethereum (ETH) Price Prediction for March 7
48  2025-01-15  XRP's $2.50 Price Breakout Still Questionable,...
49  2025-01-15        Ethereum (ETH) Price Prediction for March 5
50  2025-01-15  DePIN Summit Africa 2025 Announced for July 2n...
51  2025-01-15  Rivalz AI partners with 51nodes to drive AI-Po...
52  2025-01-15  New hybrid exchange EVEDEX Secures Funding fro...
53  2025-01-15              Top Crypto Exchanges 2025: Full Guide
54  2025-01-15  Ripple v. SEC: How Will New Developments Affec...
55  2025-01-15          Stellar Lumen (XLM) Price Prediction 2025
56  2025-01-15  What is DeSci: Guide on Decentralized Science ...
57  2025-01-15  Top 10 Crypto Media Outlets Enter 2025: Latest...

In [41]:
ethereum_DFM['currency'] = "Ethereum"

In [42]:
#save to csv
ethereum_DFM.to_csv('ethereum_Daily_News.csv', index=False)

## Solana Sraping

In [43]:
import requests

url = 'import requests'

url = 'https://u.today/search/node?keys=Solana'
response_s = requests.get(url)
response_s

In [44]:
import requests
import bs4

response = requests.get("https://u.today/search/node?keys=Solana")
# soup = bs4.BeautifulSoup(response.text, 'lxml') # with lxml package
docu = bs4.BeautifulSoup(response.text, 'html.parser') 
docu

 <!DOCTYPE html>

<html class="theme-light" dir="ltr" lang="en" prefix="og: ogp.me/ns#">
<head>
<script async="" crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9245916885225528"></script>
<link href="https://www.google-analytics.com" rel="preconnect"/>
<meta content="width=device-width, initial-scale=1.0, maximum-scale=5" name="viewport"/>
<script src="/core/assets/vendor/jquery/jquery.min.js"></script>
<meta charset="utf-8">
<link href="https://u.today/search/node" rel="canonical">
<meta content="article" property="og:type"/>
<meta content="https://u.today/search/node" property="og:url"/>
<meta content="Search" property="og:title"/>
<meta content="Search" property="og:description"/>
<meta content="https://u.today/img/logo-utoday.png" property="og:image"/>
<meta content="https://u.today/img/logo-utoday.png" property="og:image:url"/>
<meta content="https://u.today/img/logo-utoday.png" property="og:image:secure_url"/>
<meta content="2560796210663191" property="fb:app_id"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@Utoday_en" name="twitter:site"/>
<meta content="https://u.today/img/logo-utoday.png" name="twitter:image"/>
<meta content="Drupal 10 (https://www.drupal.org)" name="Generator"/>
<meta content="width" name="MobileOptimized"/>
<meta content="true" name="HandheldFriendly"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<script type="application/ld+json">{
    "@context": "https://schema.org",
    "@graph": [
        {
            "@type": "Organization",
            "name": "U.Today",
            "url": "https://u.today/search/node",
            "image": {
                "@type": "ImageObject",
                "url": "https://U.today/img/logo-utoday.png"
            }
        }
    ]
}</script>
<!-- end: separate google analytics code -->
<!-- Google Tag Manager -->
<!-- End Google Tag Manager -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-2PE2QV2V0X"></script>
<script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-2PE2QV2V0X');
    </script>
<link color="#263238" href="/img/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
<link href="/img/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/img/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/img/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/img/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/img/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/img/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/img/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/img/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/img/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/img/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/img/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/site.webmanifest" rel="manifest"/>
<link color="#263238" href="/img/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
<link href="/img/favicon/favicon.ico" rel="shortcut icon"/>
<meta content="#263238" name="msapplication-TileColor"/>
<meta content="/img/favicon/browserconfig.xml" name="msapplication-config"/>
<meta content="#263238" name="theme-color"/>
<meta content="2E6EDC1D9A57E69FC6232E905A08CBFA" name="msvalidate.01">
<link href="/manifest.json" rel="manifest">
<meta content="266789420636465" property="fb:pages">
<link href="/modules/contrib/paragraphs/css/paragraphs.unpublished.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/libs/air-datepicker/air-datepicker.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/slick-theme.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/common.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/app.css?su3fvf" media="all" rel="stylesheet">
<link href="/themes/cryptod/styles/push.css?su3fvf" media="all" rel="stylesheet">
<style>.ccc-widget.ccc-list .header-div a img {
                            width: 26px;
                            height: 26px;
                        }
                    </style>
<title>Search | U.Today</title>
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js"></script>
<script>
                        function copyToClipboard(e) {
                            let input = document.body.appendChild(document.createElement("input"));
                            input.value = window.location.href;
                            input.select();
                            document.execCommand('copy');
                            input.parentNode.removeChild(input);

                            let tooltip = document.createElement('div');
                            tooltip.className = 'copy-tooltip';
                            tooltip.innerHTML = 'Copied!';

                            if (!e.querySelector('.copy-tooltip')) {
                                e.append(tooltip);

                                setTimeout(() => {
                                    e.querySelector('.copy-tooltip').remove();
                                }, 2000);
                            }
                        }
                    </script>
<style>
                        @media (max-width: 849px) {
                            body #onesignal-slidedown-container.slide-up {
                                bottom: 60px
                            }
                        }
                    </style>
<script async="" defer="" src="https://www.google.com/recaptcha/api.js"></script>
<style>
                        .captcha-container {
                            display: none; /* CAPTCHA скрыта по умолчанию */
                        }
                    </style>
<script data-cfasync="false" src="https://cmp.gatekeeperconsent.com/min.js"></script>
<script data-cfasync="false" src="https://the.gatekeeperconsent.com/cmp.min.js"></script>
<script async="" src="//www.ezojs.com/ezoic/sa.min.js"></script>
<script>
                        window.ezstandalone = window.ezstandalone || {};
                        ezstandalone.cmd = ezstandalone.cmd || [];
                    </script>
</link></link></link></link></link></link></meta></link></meta></link></meta></head>
<body class="not_logged_in">
<!-- Google Tag Manager (noscript) -->
<!-- End Google Tag Manager (noscript) -->
<div class="something--upper">
<div class="something">
<div class="something__title">Advertisement</div>
<div class="something__nav">
<div class="something__label">AD</div>
<button aria-label="Close ad" class="btn btn--light something__close"></button>
</div>
<div class="something__content">
<div class="something__content--long">
<div>
<!-- Wideheader Fixed Desktop 1150x60 [async] -->
<script type="text/javascript">

if (!window.AdButler){(function(){var s = document.createElement("script"); s.async = true; s.type = "text/javascript"; s.src = 'https://servedbyadbutler.com/app.js'; var n = document.getElementsByTagName("script")[0]; n.parentNode.insertBefore(s, n);}());}

</script>
<script type="text/javascript">
var AdButler = AdButler || {};
AdButler.ads = AdButler.ads || [];
var abkw = window.abkw || '';
var plc602403 = window.plc602403 || 0;
document.write('<'+'div id="placement_602403_'+plc602403+'"></'+'div>');
AdButler.ads.push({handler: function(opt){ AdButler.register(183269, 602403, [1150,60], 'placement_602403_'+opt.place, opt); }, opt: { place: plc602403++, keywords: abkw, domain: 'servedbyadbutler.com', click: 'CLICK_MACRO_PLACEHOLDER' }});

</script>
</div>
</div>
<div class="something__content--square">
<div>
<!-- Wideheader Fixed Mobile 336x60 [async] -->
<script type="text/javascript">
if (document.documentElement.clientWidth < 768) {
if (!window.AdButler){(function(){var s = document.createElement("script"); s.async = true; s.type = "text/javascript"; s.src = 'https://servedbyadbutler.com/app.js'; var n = document.getElementsByTagName("script")[0]; n.parentNode.insertBefore(s, n);}());}
}
</script>
<script type="text/javascript">
if (document.documentElement.clientWidth < 768) {
var AdButler = AdButler || {};
AdButler.ads = AdButler.ads || [];
var abkw = window.abkw || '';
var plc551690 = window.plc551690 || 0;
document.write('<'+'div id="placement_551690_'+plc551690+'"></'+'div>');
AdButler.ads.push({handler: function(opt){ AdButler.register(183269, 551690, [336,60], 'placement_551690_'+opt.place, opt); }, opt: { place: plc551690++, keywords: abkw, domain: 'servedbyadbutler.com', click: 'CLICK_MACRO_PLACEHOLDER' }});
}
</script>
</div>
</div>
</div>
</div>
</div>
<header class="header">
<div class="header__container"><a class="header__logo" href="https://u.today/" title="U.Today logo"></a>
<div class="header__search" style="display: block">
<form action="/search/node" class="header__search-form" method="get">
<button class="header__search-submit btn btn--light btn--search" style="display: none;" type="submit"></button>
<input class="header__search-input" id="search_text" name="keys" type="text"/>
<button class="header__search-close btn btn--light btn--cross"></button>
</form>
</div>
</div>
</header>
<div class="mobile-menu-cover"></div>
<div class="page-container container">
<div class="something--leaderboard">
<div class="something">
<div class="something__title">Advertisement</div>
<div class="something__nav">
<div class="something__label">AD</div>
<button aria-label="Close ad" class="btn btn--light something__close"></button>
</div>
<div class="something__content">
<div class="something__content--long">
<div>
<!-- Leaderboard Desktop 1150x90 [async] -->
<script type="text/javascript">
if (window.innerWidth > 768) {
if (!window.AdButler){(function(){var s = document.createElement("script"); s.async = true; s.type = "text/javascript"; s.src = 'https://servedbyadbutler.com/app.js'; var n = document.getElementsByTagName("script")[0]; n.parentNode.insertBefore(s, n);}());}
}
</script>
<script type="text/javascript">
if (window.innerWidth > 768) {
var AdButler = AdButler || {};
AdButler.ads = AdButler.ads || [];
var abkw = window.abkw || '';
var plc828210 = window.plc828210 || 0;
document.write('<'+'div id="placement_828210_'+plc828210+'"></'+'div>');
AdButler.ads.push({handler: function(opt){ AdButler.register(183269, 828210, [1150,90], 'placement_828210_'+opt.place, opt); }, opt: { place: plc828210++, keywords: abkw, domain: 'servedbyadbutler.com', click: 'CLICK_MACRO_PLACEHOLDER' }});
}
</script>
</div>
</div>
<div class="something__content--square">
</div>
</div>
</div>
</div>
<div class="main-aside-container">
<main class="main-block">
<div class="search-result">
<h1 class="page-bg-title">Search results for “Solana”</h1>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 2, 2025 - 11:42</div>
</div>
<a class="news__item-body" href="https://u.today/solana-sol-erases-gains-amid-13-drop-what-comes-next">
<div class="news__item-title">Solana (SOL) Erases Gains Amid 13% Drop: What Comes Next?</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
            </a></div>
</div>
<div class="something something--content">
<div class="something__content-long">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="1698558466" style="display:inline-block;width:728px;height:90px"></ins>
</div>
<div class="something__content-square">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="4003311693" style="display:inline-block;width:336px;height:280px"></ins>
</div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Apr 1, 2025 - 13:53</div>
</div>
<a class="news__item-body" href="https://u.today/solana-meme-coin-crashes-49-in-minutes-on-binance-whats-going-on">
<div class="news__item-title">Solana Meme Coin Crashes 49% in Minutes on Binance; What's Going On?</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 31, 2025 - 15:32</div>
</div>
<a class="news__item-body" href="https://u.today/solana-sol-price-prediction-for-march-31-0">
<div class="news__item-title">Solana (SOL) Price Prediction for March 31</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 26, 2025 - 14:16</div>
</div>
<a class="news__item-body" href="https://u.today/solana-sol-price-prediction-for-march-26">
<div class="news__item-title">Solana (SOL) Price Prediction for March 26</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/press-releases">Press release</a>
<div class="humble">Mar 26, 2025 - 7:16</div>
</div>
<a class="news__item-body" href="https://u.today/press-releases/solpot-emerges-as-solanas-premier-on-chain-platform-distributes-over-400k-in-free">
<div class="news__item-title">Solpot Emerges as Solana's Premier On-Chain Platform, Distributes Over $400K in Free Rewards</div>
</a>
<div class="news__item-desc"></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 25, 2025 - 16:29</div>
</div>
<a class="news__item-body" href="https://u.today/breaking-fidelity-officially-joins-solana-etf-race">
<div class="news__item-title">Breaking: Fidelity Officially Joins Solana ETF Race</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
            </a></div>
</div>
<div class="something something--content">
<div class="something__content-long">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="1698558466" style="display:inline-block;width:728px;height:90px"></ins>
</div>
<div class="something__content-square">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="4003311693" style="display:inline-block;width:336px;height:280px"></ins>
</div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 25, 2025 - 16:01</div>
</div>
<a class="news__item-body" href="https://u.today/blackrock-expands-blockchain-footprint-to-solana">
<div class="news__item-title">BlackRock Expands Blockchain Footprint to Solana</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 25, 2025 - 15:42</div>
</div>
<a class="news__item-body" href="https://u.today/solana-dog-coin-bonk-rallies-35-unnoticed-whats-behind-it">
<div class="news__item-title">Solana Dog-Coin BONK Rallies 35% Unnoticed – What's Behind It?</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/press-releases">Press release</a>
<div class="humble">Mar 25, 2025 - 11:13</div>
</div>
<a class="news__item-body" href="https://u.today/press-releases/whaleio-to-bridge-nft-collection-from-ton-blockchain-to-solana">
<div class="news__item-title">Whale.io to Bridge NFT Collection from TON Blockchain to Solana</div>
</a>
<div class="news__item-desc"></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 23, 2025 - 18:12</div>
</div>
<a class="news__item-body" href="https://u.today/solana-co-founder-trashes-l2s-says-l1s-are-faster-and-more-secure">
<div class="news__item-title"> Solana Co-Founder Trashes L2s, Says L1s Are Faster and More Secure</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 23, 2025 - 14:41</div>
</div>
<a class="news__item-body" href="https://u.today/solana-sol-price-prediction-for-march-23">
<div class="news__item-title">Solana (SOL) Price Prediction for March 23</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
            </a></div>
</div>
<div class="something something--content">
<div class="something__content-long">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="1698558466" style="display:inline-block;width:728px;height:90px"></ins>
</div>
<div class="something__content-square">
<ins class="adsbygoogle" data-ad-client="ca-pub-4834169448759613" data-ad-slot="4003311693" style="display:inline-block;width:336px;height:280px"></ins>
</div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 20, 2025 - 21:58</div>
</div>
<a class="news__item-body" href="https://u.today/justin-sun-sparks-tron-etf-rumors-as-trx-expands-to-solana">
<div class="news__item-title">Justin Sun Sparks Tron ETF Rumors as TRX Expands to Solana</div>
</a>
<div class="news__item-footer"><a class="humble humble--author" href="/andy-sawa"><img alt="Andy Sawa" class="humble__img" height="24" src="https://u.today/sites/default/files/2025-03/56809.jpg" width="24"/>Andy Sawa
            </a></div>
</div>
<div class="news__item">
<div class="news__item-head humble__row"><a href="/stories">Stories</a>
<div class="humble">Mar 19, 2025 - 0:01</div>
</div>

In [45]:
# Option 1: Using CSS selectors (similar to your book_cards example)
Sol_date = docu.select("body.not_logged_in div.main-aside-container main.main-block div.search-result div.news__item div.news__item-head div.humble")
Sol_date

[<div class="humble">Apr 2, 2025 - 11:42</div>,
 <div class="humble">Apr 1, 2025 - 13:53</div>,
 <div class="humble">Mar 31, 2025 - 15:32</div>,
 <div class="humble">Mar 26, 2025 - 14:16</div>,
 <div class="humble">Mar 26, 2025 - 7:16</div>,
 <div class="humble">Mar 25, 2025 - 16:29</div>,
 <div class="humble">Mar 25, 2025 - 16:01</div>,
 <div class="humble">Mar 25, 2025 - 15:42</div>,
 <div class="humble">Mar 25, 2025 - 11:13</div>,
 <div class="humble">Mar 23, 2025 - 18:12</div>,
 <div class="humble">Mar 23, 2025 - 14:41</div>,
 <div class="humble">Mar 20, 2025 - 21:58</div>,
 <div class="humble">Mar 19, 2025 - 0:01</div>,
 <div class="humble">Mar 18, 2025 - 16:03</div>,
 <div class="humble">Mar 17, 2025 - 15:02</div>,
 <div class="humble">Mar 17, 2025 - 10:02</div>,
 <div class="humble">Mar 17, 2025 - 0:01</div>,
 <div class="humble">Mar 16, 2025 - 15:09</div>,
 <div class="humble">Mar 15, 2025 - 13:34</div>,
 <div class="humble">Mar 14, 2025 - 15:17</div>,
 <div class="humble">Mar 14, 2025 - 11:22</div>,
 <div class="humble">Mar 14, 2025 - 0:01</div>,
 <div class="humble">Mar 13, 2025 - 11:43</div>,
 <div class="humble">Mar 12, 2025 - 18:55</div>,
 <div class="humble">Mar 12, 2025 - 15:05</div>,
 <div class="humble">Mar 12, 2025 - 12:24</div>,
 <div class="humble">Mar 12, 2025 - 0:01</div>,
 <div class="humble">Mar 11, 2025 - 11:18</div>,
 <div class="humble">Mar 10, 2025 - 16:22</div>,
 <div class="humble">Mar 10, 2025 - 0:01</div>,
 <div class="humble">Mar 8, 2025 - 15:16</div>,
 <div class="humble">Mar 8, 2025 - 14:29</div>,
 <div class="humble">Mar 8, 2025 - 10:43</div>,
 <div class="humble">Mar 8, 2025 - 0:01</div>,
 <div class="humble">Mar 7, 2025 - 15:56</div>,
 <div class="humble">Mar 6, 2025 - 9:41</div>,
 <div class="humble">Mar 6, 2025 - 0:01</div>,
 <div class="humble">Mar 5, 2025 - 18:51</div>,
 <div class="humble">Mar 5, 2025 - 9:30</div>,
 <div class="humble">Mar 5, 2025 - 6:07</div>,
 <div class="humble">Mar 4, 2025 - 12:24</div>,
 <div class="humble">Mar 4, 2025 - 0:01</div>,
 <div class="humble">Mar 3, 2025 - 14:51</div>,
 <div class="humble">Mar 3, 2025 - 14:39</div>,
 <div class="humble">Mar 1, 2025 - 12:56</div>,
 <div class="humble">Feb 28, 2025 - 15:42</div>,
 <div class="humble">Feb 28, 2025 - 12:51</div>,
 <div class="humble">Feb 28, 2025 - 0:01</div>,
 <div class="humble">Feb 26, 2025 - 0:01</div>,
 <div class="humble">Feb 24, 2025 - 12:01</div>]

In [46]:
New_cards = docu.select('div.news__item')
New_cards

[<div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 2, 2025 - 11:42</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-erases-gains-amid-13-drop-what-comes-next">
 <div class="news__item-title">Solana (SOL) Erases Gains Amid 13% Drop: What Comes Next?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Apr 1, 2025 - 13:53</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-meme-coin-crashes-49-in-minutes-on-binance-whats-going-on">
 <div class="news__item-title">Solana Meme Coin Crashes 49% in Minutes on Binance; What's Going On?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 31, 2025 - 15:32</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-price-prediction-for-march-31-0">
 <div class="news__item-title">Solana (SOL) Price Prediction for March 31</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 26, 2025 - 14:16</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-price-prediction-for-march-26">
 <div class="news__item-title">Solana (SOL) Price Prediction for March 26</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/press-releases">Press release</a>
 <div class="humble">Mar 26, 2025 - 7:16</div>
 </div>
 <a class="news__item-body" href="https://u.today/press-releases/solpot-emerges-as-solanas-premier-on-chain-platform-distributes-over-400k-in-free">
 <div class="news__item-title">Solpot Emerges as Solana's Premier On-Chain Platform, Distributes Over $400K in Free Rewards</div>
 </a>
 <div class="news__item-desc"></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 25, 2025 - 16:29</div>
 </div>
 <a class="news__item-body" href="https://u.today/breaking-fidelity-officially-joins-solana-etf-race">
 <div class="news__item-title">Breaking: Fidelity Officially Joins Solana ETF Race</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 25, 2025 - 16:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/blackrock-expands-blockchain-footprint-to-solana">
 <div class="news__item-title">BlackRock Expands Blockchain Footprint to Solana</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 25, 2025 - 15:42</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-dog-coin-bonk-rallies-35-unnoticed-whats-behind-it">
 <div class="news__item-title">Solana Dog-Coin BONK Rallies 35% Unnoticed – What's Behind It?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/press-releases">Press release</a>
 <div class="humble">Mar 25, 2025 - 11:13</div>
 </div>
 <a class="news__item-body" href="https://u.today/press-releases/whaleio-to-bridge-nft-collection-from-ton-blockchain-to-solana">
 <div class="news__item-title">Whale.io to Bridge NFT Collection from TON Blockchain to Solana</div>
 </a>
 <div class="news__item-desc"></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 23, 2025 - 18:12</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-co-founder-trashes-l2s-says-l1s-are-faster-and-more-secure">
 <div class="news__item-title"> Solana Co-Founder Trashes L2s, Says L1s Are Faster and More Secure</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 23, 2025 - 14:41</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-price-prediction-for-march-23">
 <div class="news__item-title">Solana (SOL) Price Prediction for March 23</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 20, 2025 - 21:58</div>
 </div>
 <a class="news__item-body" href="https://u.today/justin-sun-sparks-tron-etf-rumors-as-trx-expands-to-solana">
 <div class="news__item-title">Justin Sun Sparks Tron ETF Rumors as TRX Expands to Solana</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/andy-sawa"><img alt="Andy Sawa" class="humble__img" height="24" src="https://u.today/sites/default/files/2025-03/56809.jpg" width="24"/>Andy Sawa
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 19, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-make-or-break-support-reached-dogecoin-doge-price-at-breaking-point-secret-bullish">
 <div class="news__item-title">Bitcoin (BTC): Make or Break Support Reached, Dogecoin (DOGE) Price at Breaking Point, Secret Bullish Solana (SOL) Pattern Formed?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 18, 2025 - 16:03</div>
 </div>
 <a class="news__item-body" href="https://u.today/did-cmes-solana-futures-flop-not-really">
 <div class="news__item-title">Did CME's Solana Futures Flop? Not Really</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 17, 2025 - 15:02</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-at-127-what-to-expect-from-sol-price-this-week">
 <div class="news__item-title">Solana at $127: What to Expect From SOL Price This Week</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 17, 2025 - 10:02</div>
 </div>
 <a class="news__item-body" href="https://u.today/59-million-solana-sol-in-7-days-whats-going-to-happen">
 <div class="news__item-title">$59 Million Solana (SOL) in 7 Days: What's Going to Happen?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 17, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/bitcoin-btc-must-break-this-to-reach-100000-dogecoin-doge-coming-closer-to-bull-market-solana-sol">
 <div class="news__item-title">Bitcoin (BTC) Must Break This to Reach $100,000, Dogecoin (DOGE) Coming Closer to Bull Market, Solana (SOL) Death Cross Complications</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 16, 2025 - 15:09</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-celebrates-5th-birthday-details">
 <div class="news__item-title">Solana (SOL) Celebrates 5th Birthday: Details</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/gamza-khanzadaev"><img alt="Gamza Khanzadaev" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-05/14694.jpg" width="24"/>Gamza Khanzadaev
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 15, 2025 - 13:34</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-vs-ethereum-eight-parameters-compared-by-crypto-expert">
 <div class="news__item-title">Solana vs. Ethereum: Eight Parameters Compared by Crypto Expert</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/vladislav-sopov"><img alt="Vladislav Sopov" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-07/8893.jpg" width="24"/>Vladislav Sopov
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 14, 2025 - 15:17</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-price-prediction-for-march-14">
 <div class="news__item-title">Solana (SOL) Price Prediction for March 14</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 14, 2025 - 11:22</div>
 </div>
 <a class="news__item-body" href="https://u.today/solanas-sol-legendary-cup-and-handle-pattern-shaping-up-heres-target">
 <div class="news__item-title">Solana's (SOL) Legendary Cup and Handle Pattern Shaping Up, Here's Target</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 14, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/dogecoin-death-cross-confirmed-solana-sol-joins-doge-with-its-own-death-cross-xrp-recovery">
 <div class="news__item-title">Dogecoin Death Cross Confirmed, Solana (SOL): Joins DOGE With Its Own Death Cross, XRP Recovery Continues: Next Level to Watch</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 13, 2025 - 11:43</div>
 </div>
 <a class="news__item-body" href="https://u.today/201755-solana-sol-stun-worlds-largest-crypto-exchange">
 <div class="news__item-title">201,755 Solana (SOL) Stun World's Largest Crypto Exchange</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 12, 2025 - 18:55</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-etf-proposed-by-15-trillion-investment-titan">
 <div class="news__item-title">Solana ETF Proposed by $1.5 Trillion Investment Titan </div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/alex-dovbnya"><img alt="Alex Dovbnya" class="humble__img" height="24" src="https://u.today/sites/default/files/2019-11/alex-m-ava.jpg" width="24"/>Alex Dovbnya
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 12, 2025 - 15:05</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-revenue-falls-93-from-january-high">
 <div class="news__item-title">Solana (SOL) Revenue Falls 93% From January High</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 12, 2025 - 12:24</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-price-prediction-for-march-12-0">
 <div class="news__item-title">Solana (SOL) Price Prediction for March 12</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 12, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-death-cross-incoming-dogecoin-doge-hits-last-possible-support-ethereum-eth-says-goodbye">
 <div class="news__item-title">Solana (SOL) Death Cross Incoming, Dogecoin (DOGE) Hits Last Possible Support, Ethereum (ETH) Says Goodbye to $2,000 </div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 11, 2025 - 11:18</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-reclaims-123-is-sell-off-over">
 <div class="news__item-title">Solana (SOL) Reclaims $123, Is Sell-off Over?</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/godfrey-benjamin"><img alt="Godfrey Benjamin" class="humble__img" height="24" src="https://u.today/sites/default/files/2022-12/29302.jpg" width="24"/>Godfrey Benjamin
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 10, 2025 - 16:22</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-on-verge-of-death-cross-amid-market-sell-off-potential-scenarios">
 <div class="news__item-title">Solana (SOL) on Verge of Death Cross Amid Market Sell-off: Potential Scenarios</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/tomiwabold-olajide"><img alt="Tomiwabold Olajide" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-11/8944.jpg" width="24"/>Tomiwabold Olajide
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 10, 2025 - 0:01</div>
 </div>
 <a class="news__item-body" href="https://u.today/xrp-movement-to-death-cross-begins-shiba-inu-shib-bulls-gave-up-solana-sol-bullish-reversal-might">
 <div class="news__item-title">XRP: Movement to Death Cross Begins, Shiba Inu (SHIB) Bulls Gave Up? Solana (SOL) Bullish Reversal Might Be Around Corner</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/arman-shirinyan"><img alt="Arman Shirinyan" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8993.jpg" width="24"/>Arman Shirinyan
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 8, 2025 - 15:16</div>
 </div>
 <a class="news__item-body" href="https://u.today/solana-sol-price-prediction-for-march-8">
 <div class="news__item-title">Solana (SOL) Price Prediction for March 8</div>
 </a>
 <div class="news__item-footer"><a class="humble humble--author" href="/denys-serhiichuk"><img alt="Denys Serhiichuk" class="humble__img" height="24" src="https://u.today/sites/default/files/2021-08/8942.jpg" width="24"/>Denys Serhiichuk
             </a></div>
 </div>,
 <div class="news__item">
 <div class="news__item-head humble__row"><a href="/stories">Stories</a>
 <div class="humble">Mar 8, 2025 - 14:29</div>
 </div>
 <a class="news__item-body" href="https://u.today/518-billion-solana-sol-stun-market-bulls-heres-why">

In [47]:
Sol_data = []
for card in New_cards:
    data = []
    date_sol = card.select_one('div.news__item-head div.humble')
    if date_sol != None:
        datestr = date_eth.get_text()
        data.append(datetime.strptime(datestr.split(" - ")[0], "%b %d, %Y").date())
    title_sol = card.select_one('div.news__item-title')
    if title_sol != None:
        data.append(title_sol.get_text())
    if len(data) == 2:
        Sol_data.append(tuple(data))
    
Sol_data

[(datetime.date(2025, 1, 15),
  'Solana (SOL) Erases Gains Amid 13% Drop: What Comes Next?'),
 (datetime.date(2025, 1, 15),
  "Solana Meme Coin Crashes 49% in Minutes on Binance; What's Going On?"),
 (datetime.date(2025, 1, 15), 'Solana (SOL) Price Prediction for March 31'),
 (datetime.date(2025, 1, 15), 'Solana (SOL) Price Prediction for March 26'),
 (datetime.date(2025, 1, 15),
  "Solpot Emerges as Solana's Premier On-Chain Platform, Distributes Over $400K in Free Rewards"),
 (datetime.date(2025, 1, 15),
  'Breaking: Fidelity Officially Joins Solana ETF Race'),
 (datetime.date(2025, 1, 15),
  'BlackRock Expands Blockchain Footprint to Solana'),
 (datetime.date(2025, 1, 15),
  "Solana Dog-Coin BONK Rallies 35% Unnoticed – What's Behind It?"),
 (datetime.date(2025, 1, 15),
  'Whale.io to Bridge NFT Collection from TON Blockchain to Solana'),
 (datetime.date(2025, 1, 15),
  ' Solana Co-Founder Trashes L2s, Says L1s Are Faster and More Secure'),
 (datetime.date(2025, 1, 15), 'Solana (SOL) Price Prediction for March 23'),
 (datetime.date(2025, 1, 15),
  'Justin Sun Sparks Tron ETF Rumors as TRX Expands to Solana'),
 (datetime.date(2025, 1, 15),
  'Bitcoin (BTC): Make or Break Support Reached, Dogecoin (DOGE) Price at Breaking Point, Secret Bullish Solana (SOL) Pattern Formed?'),
 (datetime.date(2025, 1, 15), "Did CME's Solana Futures Flop? Not Really"),
 (datetime.date(2025, 1, 15),
  'Solana at $127: What to Expect From SOL Price This Week'),
 (datetime.date(2025, 1, 15),
  "$59 Million Solana (SOL) in 7 Days: What's Going to Happen?"),
 (datetime.date(2025, 1, 15),
  'Bitcoin (BTC) Must Break This to Reach $100,000, Dogecoin (DOGE) Coming Closer to Bull Market, Solana (SOL) Death Cross Complications'),
 (datetime.date(2025, 1, 15), 'Solana (SOL) Celebrates 5th Birthday: Details'),
 (datetime.date(2025, 1, 15),
  'Solana vs. Ethereum: Eight Parameters Compared by Crypto Expert'),
 (datetime.date(2025, 1, 15), 'Solana (SOL) Price Prediction for March 14'),
 (datetime.date(2025, 1, 15),
  "Solana's (SOL) Legendary Cup and Handle Pattern Shaping Up, Here's Target"),
 (datetime.date(2025, 1, 15),
  'Dogecoin Death Cross Confirmed, Solana (SOL): Joins DOGE With Its Own Death Cross, XRP Recovery Continues: Next Level to Watch'),
 (datetime.date(2025, 1, 15),
  "201,755 Solana (SOL) Stun World's Largest Crypto Exchange"),
 (datetime.date(2025, 1, 15),
  'Solana ETF Proposed by $1.5 Trillion Investment Titan '),
 (datetime.date(2025, 1, 15),
  'Solana (SOL) Revenue Falls 93% From January High'),
 (datetime.date(2025, 1, 15), 'Solana (SOL) Price Prediction for March 12'),
 (datetime.date(2025, 1, 15),
  'Solana (SOL) Death Cross Incoming, Dogecoin (DOGE) Hits Last Possible Support, Ethereum (ETH) Says Goodbye to $2,000 '),
 (datetime.date(2025, 1, 15), 'Solana (SOL) Reclaims $123, Is Sell-off Over?'),
 (datetime.date(2025, 1, 15),
  'Solana (SOL) on Verge of Death Cross Amid Market Sell-off: Potential Scenarios'),
 (datetime.date(2025, 1, 15),
  'XRP: Movement to Death Cross Begins, Shiba Inu (SHIB) Bulls Gave Up? Solana (SOL) Bullish Reversal Might Be Around Corner'),
 (datetime.date(2025, 1, 15), 'Solana (SOL) Price Prediction for March 8'),
 (datetime.date(2025, 1, 15),
  "$5.18 Billion Solana (SOL) Stun Market Bulls, Here's Why"),
 (datetime.date(2025, 1, 15),
  'Peter Schiff Creates His Own BTC Reserve, Receives Solana Instead'),
 (datetime.date(2025, 1, 15),
  'Bitcoin (BTC) $100,000 Momentum Gone, Solana (SOL): Surprising Move Incoming? Shiba Inu (SHIB) Heating up for Skyrocketing?'),
 (datetime.date(2025, 1, 15),
  "BlackRock's IBIT Makes First BTC Purchase in 7 Days, Solana Founder Presents 3 Major Scenarios for US Strategic Reserve, Texas Senate Passes Bitcoin Reserve Bill: Crypto News Digest by U.Today"),
 (datetime.date(2025, 1, 15),
  'Solana (SOL) Founder Presents 3 Major Scenarios for US Strategic Reserve'),
 (datetime.date(2025, 1, 15),
  'Shiba Inu (SHIB) Delivers Grim Volume Signal, Bitcoin (BTC): Is it Trying to Break $90,000? Solana (SOL): Days Before Recovery?'),
 (datetime.date(2025, 1, 15), "Solana's Growth Falls by 88% "),
 (datetime.date(2025, 1, 15),
  "Solana (SOL) Whales Capitulate? Here's How Much Will Be Sold"),
 (datetime.date(2025, 1, 15),
  'Top Satoshi Candidate Says XRP and Solana Parts of Reserve Are ‘Obvious Scams’'),
 (datetime.date(2025, 1, 15),
  "Dogecoin, Solana, XRP: Up to 20% Tumbling, What's Happening?"),
 (datetime.date(2025, 1, 15),
  'Is Bitcoin (BTC) Ready for $100,000? Solana (SOL) Skyrockets, But in Wrong Way, Shiba Inu (SHIB): Is There Any Hope? '),
 (datetime.date(2025, 1, 15),
  'Solana Flips Ethereum Again as DEX Volume Hits $3.99 Billion'),
 (datetime.date(2025, 1, 15), 'Solana (SOL) Price Prediction for March 3'),
 (datetime.date(2025, 1, 15),
  "Solana Price Rebounds 10%, Here's Impact on SOL Liquidations"),
 (datetime.date(2025, 1, 15),
  'Solana (SOL) Futures Launch Date Confirmed by CME Group: Details'),
 (datetime.date(2025, 1, 15),
  '96,180 Solana (SOL) Exit Binance, Staked by Whale'),
 (datetime.date(2025, 1, 15),
  '3 Major Dogecoin (DOGE) Support Levels, Shiba Inu (SHIB) Attempts Solid Recovery, Solana (SOL) Sees Secret Whale Accumulation'),
 (datetime.date(2025, 1, 15),
  'Bitcoin (BTC) on Yearly Low, Shiba Inu (SHIB) Plummeting Aggravated, Solana (SOL) Far Too Close to $100'),
 (datetime.date(2025, 1, 15),
  "Solana (SOL) Lost 45%: Bitcoin Domination Isn't Stopping?"),
 (datetime.date(2025, 1, 15), 'Top Crypto Exchanges 2025: Full Guide'),
 (datetime.date(2025, 1, 15),
  'Ripple v. SEC: How Will New Developments Affect XRP Price?'),
 (datetime.date(2025, 1, 15), 'Stellar Lumen (XLM) Price Prediction 2025'),
 (datetime.date(2025, 1, 15),
  'What is DeSci: Guide on Decentralized Science in Crypto'),
 (datetime.date(2025, 1, 15),
  'Top 10 Crypto Media Outlets Enter 2025: Latest Similarweb Data Update')]

In [48]:
Sol_DFM = pd.DataFrame(Sol_data, columns = ['date', 'title'])
Sol_DFM

          date                                              title
0   2025-01-15  Solana (SOL) Erases Gains Amid 13% Drop: What ...
1   2025-01-15  Solana Meme Coin Crashes 49% in Minutes on Bin...
2   2025-01-15         Solana (SOL) Price Prediction for March 31
3   2025-01-15         Solana (SOL) Price Prediction for March 26
4   2025-01-15  Solpot Emerges as Solana's Premier On-Chain Pl...
5   2025-01-15  Breaking: Fidelity Officially Joins Solana ETF...
6   2025-01-15   BlackRock Expands Blockchain Footprint to Solana
7   2025-01-15  Solana Dog-Coin BONK Rallies 35% Unnoticed – W...
8   2025-01-15  Whale.io to Bridge NFT Collection from TON Blo...
9   2025-01-15   Solana Co-Founder Trashes L2s, Says L1s Are F...
10  2025-01-15         Solana (SOL) Price Prediction for March 23
11  2025-01-15  Justin Sun Sparks Tron ETF Rumors as TRX Expan...
12  2025-01-15  Bitcoin (BTC): Make or Break Support Reached, ...
13  2025-01-15          Did CME's Solana Futures Flop? Not Really
14  2025-01-15  Solana at $127: What to Expect From SOL Price ...
15  2025-01-15  $59 Million Solana (SOL) in 7 Days: What's Goi...
16  2025-01-15  Bitcoin (BTC) Must Break This to Reach $100,00...
17  2025-01-15      Solana (SOL) Celebrates 5th Birthday: Details
18  2025-01-15  Solana vs. Ethereum: Eight Parameters Compared...
19  2025-01-15         Solana (SOL) Price Prediction for March 14
20  2025-01-15  Solana's (SOL) Legendary Cup and Handle Patter...
21  2025-01-15  Dogecoin Death Cross Confirmed, Solana (SOL): ...
22  2025-01-15  201,755 Solana (SOL) Stun World's Largest Cryp...
23  2025-01-15  Solana ETF Proposed by $1.5 Trillion Investmen...
24  2025-01-15   Solana (SOL) Revenue Falls 93% From January High
25  2025-01-15         Solana (SOL) Price Prediction for March 12
26  2025-01-15  Solana (SOL) Death Cross Incoming, Dogecoin (D...
27  2025-01-15      Solana (SOL) Reclaims $123, Is Sell-off Over?
28  2025-01-15  Solana (SOL) on Verge of Death Cross Amid Mark...
29  2025-01-15  XRP: Movement to Death Cross Begins, Shiba Inu...
30  2025-01-15          Solana (SOL) Price Prediction for March 8
31  2025-01-15  $5.18 Billion Solana (SOL) Stun Market Bulls, ...
32  2025-01-15  Peter Schiff Creates His Own BTC Reserve, Rece...
33  2025-01-15  Bitcoin (BTC) $100,000 Momentum Gone, Solana (...
34  2025-01-15  BlackRock's IBIT Makes First BTC Purchase in 7...
35  2025-01-15  Solana (SOL) Founder Presents 3 Major Scenario...
36  2025-01-15  Shiba Inu (SHIB) Delivers Grim Volume Signal, ...
37  2025-01-15                      Solana's Growth Falls by 88%
38  2025-01-15  Solana (SOL) Whales Capitulate? Here's How Muc...
39  2025-01-15  Top Satoshi Candidate Says XRP and Solana Part...
40  2025-01-15  Dogecoin, Solana, XRP: Up to 20% Tumbling, Wha...
41  2025-01-15  Is Bitcoin (BTC) Ready for $100,000? Solana (S...
42  2025-01-15  Solana Flips Ethereum Again as DEX Volume Hits...
43  2025-01-15          Solana (SOL) Price Prediction for March 3
44  2025-01-15  Solana Price Rebounds 10%, Here's Impact on SO...
45  2025-01-15  Solana (SOL) Futures Launch Date Confirmed by ...
46  2025-01-15  96,180 Solana (SOL) Exit Binance, Staked by Whale
47  2025-01-15  3 Major Dogecoin (DOGE) Support Levels, Shiba ...
48  2025-01-15  Bitcoin (BTC) on Yearly Low, Shiba Inu (SHIB) ...
49  2025-01-15  Solana (SOL) Lost 45%: Bitcoin Domination Isn'...
50  2025-01-15              Top Crypto Exchanges 2025: Full Guide
51  2025-01-15  Ripple v. SEC: How Will New Developments Affec...
52  2025-01-15          Stellar Lumen (XLM) Price Prediction 2025
53  2025-01-15  What is DeSci: Guide on Decentralized Science ...
54  2025-01-15  Top 10 Crypto Media Outlets Enter 2025: Latest...

In [49]:
Sol_DFM['currency'] = "Solana"
Sol_DFM

          date                                              title currency
0   2025-01-15  Solana (SOL) Erases Gains Amid 13% Drop: What ...   Solana
1   2025-01-15  Solana Meme Coin Crashes 49% in Minutes on Bin...   Solana
2   2025-01-15         Solana (SOL) Price Prediction for March 31   Solana
3   2025-01-15         Solana (SOL) Price Prediction for March 26   Solana
4   2025-01-15  Solpot Emerges as Solana's Premier On-Chain Pl...   Solana
5   2025-01-15  Breaking: Fidelity Officially Joins Solana ETF...   Solana
6   2025-01-15   BlackRock Expands Blockchain Footprint to Solana   Solana
7   2025-01-15  Solana Dog-Coin BONK Rallies 35% Unnoticed – W...   Solana
8   2025-01-15  Whale.io to Bridge NFT Collection from TON Blo...   Solana
9   2025-01-15   Solana Co-Founder Trashes L2s, Says L1s Are F...   Solana
10  2025-01-15         Solana (SOL) Price Prediction for March 23   Solana
11  2025-01-15  Justin Sun Sparks Tron ETF Rumors as TRX Expan...   Solana
12  2025-01-15  Bitcoin (BTC): Make or Break Support Reached, ...   Solana
13  2025-01-15          Did CME's Solana Futures Flop? Not Really   Solana
14  2025-01-15  Solana at $127: What to Expect From SOL Price ...   Solana
15  2025-01-15  $59 Million Solana (SOL) in 7 Days: What's Goi...   Solana
16  2025-01-15  Bitcoin (BTC) Must Break This to Reach $100,00...   Solana
17  2025-01-15      Solana (SOL) Celebrates 5th Birthday: Details   Solana
18  2025-01-15  Solana vs. Ethereum: Eight Parameters Compared...   Solana
19  2025-01-15         Solana (SOL) Price Prediction for March 14   Solana
20  2025-01-15  Solana's (SOL) Legendary Cup and Handle Patter...   Solana
21  2025-01-15  Dogecoin Death Cross Confirmed, Solana (SOL): ...   Solana
22  2025-01-15  201,755 Solana (SOL) Stun World's Largest Cryp...   Solana
23  2025-01-15  Solana ETF Proposed by $1.5 Trillion Investmen...   Solana
24  2025-01-15   Solana (SOL) Revenue Falls 93% From January High   Solana
25  2025-01-15         Solana (SOL) Price Prediction for March 12   Solana
26  2025-01-15  Solana (SOL) Death Cross Incoming, Dogecoin (D...   Solana
27  2025-01-15      Solana (SOL) Reclaims $123, Is Sell-off Over?   Solana
28  2025-01-15  Solana (SOL) on Verge of Death Cross Amid Mark...   Solana
29  2025-01-15  XRP: Movement to Death Cross Begins, Shiba Inu...   Solana
30  2025-01-15          Solana (SOL) Price Prediction for March 8   Solana
31  2025-01-15  $5.18 Billion Solana (SOL) Stun Market Bulls, ...   Solana
32  2025-01-15  Peter Schiff Creates His Own BTC Reserve, Rece...   Solana
33  2025-01-15  Bitcoin (BTC) $100,000 Momentum Gone, Solana (...   Solana
34  2025-01-15  BlackRock's IBIT Makes First BTC Purchase in 7...   Solana
35  2025-01-15  Solana (SOL) Founder Presents 3 Major Scenario...   Solana
36  2025-01-15  Shiba Inu (SHIB) Delivers Grim Volume Signal, ...   Solana
37  2025-01-15                      Solana's Growth Falls by 88%    Solana
38  2025-01-15  Solana (SOL) Whales Capitulate? Here's How Muc...   Solana
39  2025-01-15  Top Satoshi Candidate Says XRP and Solana Part...   Solana
40  2025-01-15  Dogecoin, Solana, XRP: Up to 20% Tumbling, Wha...   Solana
41  2025-01-15  Is Bitcoin (BTC) Ready for $100,000? Solana (S...   Solana
42  2025-01-15  Solana Flips Ethereum Again as DEX Volume Hits...   Solana
43  2025-01-15          Solana (SOL) Price Prediction for March 3   Solana
44  2025-01-15  Solana Price Rebounds 10%, Here's Impact on SO...   Solana
45  2025-01-15  Solana (SOL) Futures Launch Date Confirmed by ...   Solana
46  2025-01-15  96,180 Solana (SOL) Exit Binance, Staked by Whale   Solana
47  2025-01-15  3 Major Dogecoin (DOGE) Support Levels, Shiba ...   Solana
48  2025-01-15  Bitcoin (BTC) on Yearly Low, Shiba Inu (SHIB) ...   Solana
49  2025-01-15  Solana (SOL) Lost 45%: Bitcoin Domination Isn'...   Solana
50  2025-01-15              Top Crypto Exchanges 2025: Full Guide   Solana
51  2025-01-15  Ripple v. SEC: How Will New Developments Affec...   Solana
52  2025-01-15          Stellar Lumen (XLM) Price Prediction 2025   Solana
53  2025-01-15  What is DeSci: Guide on Decentralized Science ...   Solana
54  2025-01-15  Top 10 Crypto Media Outlets Enter 2025: Latest...   Solana

In [50]:
#save to csv
Sol_DFM.to_csv('Solana_Daily_News.csv', index=False)

In [51]:
import pandas as pd

# Load datasets
bitcoin_ddf = pd.read_csv('Bitcoin_Daily_News.csv')
ethereum_ddf = pd.read_csv('Ethereum_Daily_News.csv')
Sol_ddf = pd.read_csv('Solana_Daily_News.csv')

# Add currency identifier
#bitcoin['currency'] = 'Bitcoin'
#ethereum['currency'] = 'Ethereum'

# Combine vertically
crypto_news = pd.concat([bitcoin_ddf, ethereum_ddf, Sol_ddf], ignore_index=True)

# Convert date to datetime and sort
crypto_news['date'] = pd.to_datetime(crypto_news['date'])
crypto_news = crypto_news.sort_values(['date'])

# Reset index
crypto_news = crypto_news.reset_index(drop=True)

# Save to CSV
crypto_news.to_csv('Crypto_News.csv', index=False)

# Display result
print(crypto_news.head(10))

        date                                              title  currency
0 2025-01-15  Ethereum (ETH) Developers Launch Hoodi Testnet...  Ethereum
1 2025-01-15  New hybrid exchange EVEDEX Secures Funding fro...  Ethereum
2 2025-01-15              Top Crypto Exchanges 2025: Full Guide  Ethereum
3 2025-01-15  Ripple v. SEC: How Will New Developments Affec...  Ethereum
4 2025-01-15          Stellar Lumen (XLM) Price Prediction 2025  Ethereum
5 2025-01-15  What is DeSci: Guide on Decentralized Science ...  Ethereum
6 2025-01-15  Top 10 Crypto Media Outlets Enter 2025: Latest...  Ethereum
7 2025-01-15  Solana (SOL) Erases Gains Amid 13% Drop: What ...    Solana
8 2025-01-15  Solana Meme Coin Crashes 49% in Minutes on Bin...    Solana
9 2025-01-15         Solana (SOL) Price Prediction for March 31    Solana

In [52]:
crypto_news.head(10)

        date                                              title  currency
0 2025-01-15  Ethereum (ETH) Developers Launch Hoodi Testnet...  Ethereum
1 2025-01-15  New hybrid exchange EVEDEX Secures Funding fro...  Ethereum
2 2025-01-15              Top Crypto Exchanges 2025: Full Guide  Ethereum
3 2025-01-15  Ripple v. SEC: How Will New Developments Affec...  Ethereum
4 2025-01-15          Stellar Lumen (XLM) Price Prediction 2025  Ethereum
5 2025-01-15  What is DeSci: Guide on Decentralized Science ...  Ethereum
6 2025-01-15  Top 10 Crypto Media Outlets Enter 2025: Latest...  Ethereum
7 2025-01-15  Solana (SOL) Erases Gains Amid 13% Drop: What ...    Solana
8 2025-01-15  Solana Meme Coin Crashes 49% in Minutes on Bin...    Solana
9 2025-01-15         Solana (SOL) Price Prediction for March 31    Solana

# Railway

In [50]:
from dotenv import load_dotenv
import os
load_dotenv()

dbconn = os.getenv("DBCONN")

In [51]:
import psycopg

In [75]:
# establish database connection using connection string from .env
conn = psycopg.connect(dbconn)

# create a cursor
cur = conn.cursor()

In [33]:
combined_df.head()

        date symbol      open      high       low     close      volume
0 2025-04-03    BTC  75661.51  76569.68  75371.55  76365.98   22.993658
1 2025-04-02    BTC  78900.68  81300.00  75600.00  75617.59  685.408274
2 2025-04-01    BTC  76229.03  79232.59  76149.07  78902.29  416.949969
3 2025-03-31    BTC  76102.60  77674.07  75042.00  76253.99  386.406672
4 2025-03-30    BTC  76346.00  77221.12  75432.48  76135.85  204.162965

In [70]:
cur.execute("DROP TABLE crypto;")

In [76]:
cur.execute('''
    CREATE TABLE IF NOT EXISTS crypto(
        date TIMESTAMP NOT NULL,
        symbol VARCHAR(50) NOT NULL,
        open DOUBLE PRECISION,
        high DOUBLE PRECISION,
        low DOUBLE PRECISION,
        close DOUBLE PRECISION,
        volume DOUBLE PRECISION,
        PRIMARY KEY(date, symbol)
    );
''')

In [77]:
# commit to all executed queries
conn.commit()

In [78]:
# close the cursor and sever connection
cur.close()
conn.close()

In [ ]:
api_key = os.getenv("API_KEY")

In [83]:
conn = psycopg.connect(dbconn)

# create a cursor
cur = conn.cursor()

In [84]:
#  Load CSV into Pandas DataFrame
crypto_df = pd.read_csv("Crypto_Currency.csv")
#  Insert Data Row by Row
for _, row in crypto_df.iterrows():
    cur.execute('''
        INSERT INTO crypto (date, symbol, open, high, low, close, volume)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (date, symbol) DO NOTHING;
    ''', tuple(row))  # Convert row to tuple

conn.commit()
cur.close()
conn.close()

## For Crypto News

In [85]:
# establish database connection using connection string from .env
conn = psycopg.connect(dbconn)

# create a cursor
cur = conn.cursor()

In [86]:
#crypto_news.head(50)

In [87]:
crypto_news[crypto_news.duplicated("title")]

NameError: name 'crypto_news' is not defined

In [ ]:
cur.execute("DROP TABLE crypto_news;")

In [ ]:
cur.execute('''
    CREATE TABLE IF NOT EXISTS crypto_news(
        date TIMESTAMP NOT NULL,
        title TEXT,
        currency VARCHAR(50) NOT NULL,
        PRIMARY KEY(date, title)
    );
''')

In [ ]:
# commit to all executed queries
conn.commit()

In [ ]:
# close the cursor and sever connection
cur.close()
conn.close()

In [ ]:
import pandas as pd

In [ ]:
conn = psycopg.connect(dbconn)

# create a cursor
cur = conn.cursor()

In [ ]:
#  Load CSV into Pandas DataFrame
crypto_nw = pd.read_csv("Crypto_News.csv")
#  Insert Data Row by Row
for _, row in crypto_nw.iterrows():
    print(tuple(row))
    cur.execute('''
        INSERT INTO crypto_news (date, title, currency)
        VALUES (%s, %s, %s)
        ON CONFLICT (date, title) DO NOTHING;
    ''', tuple(row))  # Convert row to tuple

conn.commit()
cur.close()
conn.close()